"use client";
import { useId } from "react";
import { LockKeyhole, UnlockKeyhole, Minus, Plus, RotateCcw } from "lucide-react";
import { Slider } from "radix-ui";
import { Switch } from "@/components/ui/switch";
import { normalizeRotation, resizeAxis, type AccessoryLayout, type AccessoryPosition } from "@/lib/avatar-positions";

export function AccessoryTransformControls({label,layout,disabled,onChange}:{label:string;layout:AccessoryLayout;disabled:boolean;onChange:(position:AccessoryPosition)=>void}){
  const id=useId();
  const change=(patch:Partial<AccessoryPosition>)=>onChange({x:layout.x,y:layout.y,...patch});
  return <div className="accessory-transform-controls"><div className="outfit-switch"><label htmlFor={id}>{layout.lockRatio?<LockKeyhole size={16}/>:<UnlockKeyhole size={16}/>}Conserver les proportions</label><Switch id={id} checked={layout.lockRatio} disabled={disabled} onCheckedChange={lockRatio=>change({lockRatio})}/></div><p className="transform-summary" aria-live="polite">{Math.round(layout.scaleX*100)} % × {Math.round(layout.scaleY*100)} % <span>·</span> {Math.round(layout.rotation)}°</p><p className="transform-help" id="avatar-transform-help">Tire un bord ou un coin. La poignée ronde fait tourner l’accessoire. Les flèches du clavier fonctionnent aussi.</p><details className="transform-precise"><summary>Réglages précis</summary>{(["scaleX","scaleY"] as const).map(axis=><Range key={axis} label={(axis==="scaleX"?"Largeur":"Hauteur")+" de "+label} value={Math.round(layout[axis]*100)} unit="%" min={50} max={180} step={5} disabled={disabled} onChange={value=>onChange(resizeAxis(layout,axis,value/100))}/>)}<button type="button" className="accessory-size-reset" disabled={disabled} onClick={()=>change({scale:1,scaleX:1,scaleY:1})}><RotateCcw size={14}/>Taille d’origine</button><Range label={"Rotation de "+label} value={Math.round(layout.rotation)} unit="°" min={-180} max={180} step={1} disabled={disabled} onChange={value=>change({rotation:normalizeRotation(value)})}/><button type="button" className="accessory-size-reset" disabled={disabled||layout.rotation===0} onClick={()=>change({rotation:0})}><RotateCcw size={14}/>Remettre droit</button></details></div>;
}
function Range({label,value,unit,min,max,step,disabled,onChange}:{label:string;value:number;unit:string;min:number;max:number;step:number;disabled:boolean;onChange:(value:number)=>void}){
  return <div className="accessory-size-control"><div className="accessory-size-label"><span>{label}</span><output>{value}{unit}</output></div><div className="accessory-size-row"><button type="button" disabled={disabled||value<=min} aria-label={"Réduire "+label} onClick={()=>onChange(Math.max(min,value-step))}><Minus size={18}/></button><Slider.Root className="accessory-size-slider" value={[value]} min={min} max={max} step={step} disabled={disabled} onValueChange={([n])=>onChange(n)}><Slider.Track className="accessory-size-track"><Slider.Range className="accessory-size-range"/></Slider.Track><Slider.Thumb className="accessory-size-thumb" aria-label={label} aria-valuetext={value+unit}/></Slider.Root><button type="button" disabled={disabled||value>=max} aria-label={"Agrandir "+label} onClick={()=>onChange(Math.min(max,value+step))}><Plus size={18}/></button></div></div>;
}
