"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowUpRight,Clapperboard,LoaderCircle,Ticket } from "lucide-react";
import { dateLabel,timeLabel,type SelectedPlan } from "@/lib/club";
import type { SocialProps } from "@/components/crew-social";
import { CrewAvatar } from "@/components/crew-avatar";
import { reactAvatar } from "@/lib/appearance";
import type { CinemaPresentation } from "@/lib/cinema-three";
import { toast } from "sonner";
export function CinemaLounge({onReveal,...s}:SocialProps&{onReveal:(id:string)=>void}){
  const plans=s.state.plans.filter(plan=>s.state.proposals.some(p=>p.id===plan.proposalId&&p.kind==="movie"));const [selected,setSelected]=useState(""),[status,setStatus]=useState("loading"),[busy,setBusy]=useState(false);const guard=useRef(false),host=useRef<HTMLDivElement>(null),scene=useRef<{update:(d:CinemaPresentation)=>Promise<void>;dispose:()=>void}|null>(null);
  const plan=plans.find(p=>p.id===selected)||plans[0],proposal=s.state.proposals.find(p=>p.id===plan?.proposalId),participants=s.state.participants.filter(p=>p.planId===plan?.id&&p.attending),names=participants.map(p=>p.author),attending=participants.some(p=>p.authorKey===s.person.trim().normalize("NFKC").toLocaleLowerCase("fr"));
  const signature=JSON.stringify({plan:plan?.id,title:proposal?.title,start:plan?.start,names,profiles:s.state.profiles});
  const data=useMemo(()=>({title:proposal?.title||"LE PROCHAIN GRAND FILM",subtitle:plan?`${dateLabel(plan.start)} · ${timeLabel(plan.start)} · ${names.length} présence(s)` :"Retiens un film pour ouvrir une séance",names,profiles:s.state.profiles}),[signature]);const latest=useRef(data);latest.current=data;
  useEffect(()=>{let stopped=false;void import("@/lib/cinema-three").then(({buildCinema})=>{if(stopped||!host.current)return;scene.current=buildCinema(host.current,ready=>setStatus(ready?"ready":"fallback"));setStatus("ready");void scene.current.update(latest.current);}).catch(()=>{if(!stopped)setStatus("fallback");});return()=>{stopped=true;scene.current?.dispose();scene.current=null;};},[]);
  useEffect(()=>{if(scene.current)void scene.current.update(data);},[data]);
  const attend=(chosen:SelectedPlan)=>s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);const was=s.state.participants.some(p=>p.planId===chosen.id&&p.authorKey===author.trim().normalize("NFKC").toLocaleLowerCase("fr")&&p.attending);try{await s.save({action:"attend",planId:chosen.id,author,attending:!was});reactAvatar(author,was?"no":"yes");toast.success(was?"Ta place est libérée.":"Ta place est confirmée !");}catch(e){toast.error((e as Error).message);}finally{guard.current=false;setBusy(false);}});
  return <section className="cinema-lounge" aria-label="La salle de cinéma du crew"><div className="lounge-heading"><div><span className="eyebrow"><Clapperboard size={17}/>JACUZZI PICTURES</span><h2>Vos places vous attendent.</h2></div>{plans.length>0&&<label className="session-picker">La séance<select value={plan.id} onChange={e=>setSelected(e.target.value)} disabled={busy}>{plans.map(p=><option key={p.id} value={p.id}>{s.state.proposals.find(x=>x.id===p.proposalId)?.title} · {dateLabel(p.start,{day:"numeric",month:"short"})} {timeLabel(p.start)}</option>)}</select></label>}</div><div className={`lounge-stage scene-${status}`} data-scene-status={status}><div className="cinema-fallback" aria-hidden="true"><Clapperboard size={46}/><strong>{proposal?.title||"La prochaine séance se prépare."}</strong><span>{names.length} présence{names.length!==1?"s":""} confirmée{names.length!==1?"s":""}</span></div><div ref={host} className="lounge-canvas"/><span className="lounge-seat-count"><Ticket size={17}/>{names.length} place{names.length!==1?"s":""} occupée{names.length!==1?"s":""}</span></div><div className="lounge-bottom">{plan?<><div><strong>{proposal?.title}</strong><span>{dateLabel(plan.start)} · {timeLabel(plan.start)} — {timeLabel(plan.end)}</span></div><div className="lounge-actions"><button className={`button ${attending?"secondary":"primary"}`} disabled={busy} onClick={()=>attend(plan)}>{busy?<LoaderCircle size={17} className="spin"/>:<Ticket size={17}/>} {attending?"Libérer ma place":"Prendre ma place"}</button><button className="button secondary" onClick={()=>onReveal(plan.id)}>L’affiche<ArrowUpRight size={16}/></button></div></>:<p>Ouvre la fiche d’un film ci-dessous, puis « Retenir ce film pour une soirée ». Les personnes qui confirment leur présence apparaîtront dans la salle.</p>}</div>{names.length>0&&<ul className="cinema-attendees" aria-label="Personnes présentes à cette séance">{names.map(name=><li key={name}><CrewAvatar name={name}/><span>{name}</span></li>)}</ul>}</section>;
}
