"use client";
import { Crown,Star,MousePointer2,TrendingUp } from "lucide-react";
import { CrewAvatar } from "@/components/crew-avatar";
import { CREW,type CookieStanding } from "@/lib/club";
import { voterKey } from "@/lib/identity";
import { formatCookies as fmt } from "@/lib/cookie-game";
export function CookieLeaderboard({standings,person}:{standings:CookieStanding[];person:string}){
 const people=new Map<string,CookieStanding>(CREW.map(author=>[voterKey(author),{authorKey:voterKey(author),author,lifetime:0,clicks:0,prestige:0}]));
 for(const row of standings)people.set(row.authorKey,{...row,author:people.get(row.authorKey)?.author??row.author});
 const ranked=[...people.values()].sort((a,b)=>b.lifetime-a.lifetime||b.clicks-a.clicks||a.author.localeCompare(b.author,"fr")),position=ranked.findIndex(p=>p.authorKey===voterKey(person));
 return <section className="cookie-leaderboard"><div className="cookie-section-intro"><span className="eyebrow">LA COURSE AUX MIETTES</span><h2>Onze copains. Des empires croustillants.</h2><p>Classement par cookies produits depuis le début, même après un prestige. À égalité : nombre de clics, puis prénom. Actualisation toutes les 15 secondes.</p></div>{person&&position>=0&&<div className="cookie-my-rank"><TrendingUp size={21}/><span>Ta position <strong>#{position+1}</strong></span><span>{fmt(ranked[position].lifetime)} cookies produits</span></div>}<div className="cookie-podium">{ranked.slice(0,3).map((row,i)=><article key={row.authorKey} className={"cookie-podium-place place-"+(i+1)}><span className="cookie-podium-rank">{i===0?<Crown size={29}/>:"#"+(i+1)}</span><CrewAvatar name={row.author}/><h3>{row.author}</h3><strong>{fmt(row.lifetime)}</strong><small>cookies produits</small><span className="cookie-podium-stars"><Star size={14}/>{row.prestige} étoiles</span></article>)}</div><div className="cookie-ranking-list" role="list" aria-label="Classement Cookie Jacuzzi">{ranked.map((row,i)=><div role="listitem" key={row.authorKey} className={row.authorKey===voterKey(person)?"is-me":""}><span className="cookie-rank-number">#{i+1}</span><CrewAvatar name={row.author} small/><div className="cookie-rank-person"><strong>{row.author}{row.authorKey===voterKey(person)&&<small>TOI</small>}</strong><span><MousePointer2 size={12}/>{fmt(row.clicks)} clics <Star size={12}/>{row.prestige} étoiles</span></div><b>{fmt(row.lifetime)}<small>cookies</small></b></div>)}</div><p className="cookie-rules">Ce classement est indépendant des votes et de leurs récompenses. Chaque prénom normalisé possède une seule partie.</p></section>;
}
