"use client";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {Activity,ArrowRight,Check,Headphones,Play,RotateCcw,Target,Trophy,Volume2,VolumeX,X} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {RHYTHM_CHARTS,RHYTHM_WINDOW,RHYTHM_MISS,rhythmChart,rhythmRecord,rhythmScore,type RhythmChartId,type CookiePlayer,type CookieAction} from "@/lib/cookie-game";

type Mode="practice"|"challenge";
type Run={chart:ReturnType<typeof rhythmChart>;mode:Mode;id:number;start:number;speed:number;hits:(number|null)[];strays:number;combo:number;bestCombo:number;feedback:string;feedbackAt:number;done:boolean};
type Props={player:CookiePlayer|null;now:number;busy:boolean;onAction:(a:CookieAction)=>void;saveError?:string;onRetry?:()=>void};
const toneNames=["Parfait","Bien","Touché"];
const duration=(ms:number)=>{const minutes=Math.ceil(Math.max(0,ms)/60000);return minutes>=60?Math.floor(minutes/60)+" h "+String(minutes%60).padStart(2,"0"):minutes+" min";};

export function CookieRhythm({player,now,busy,onAction,saveError,onRetry}:Props){
 const [selected,setSelected]=useState<RhythmChartId>("groove"),[open,setOpen]=useState(false),[phase,setPhase]=useState<"idle"|"waiting"|"playing"|"result"|"aborted">("idle"),[elapsed,setElapsed]=useState(0),[muted,setMuted]=useState(false),[audioFailed,setAudioFailed]=useState(false);
 const run=useRef<Run|null>(null),waiting=useRef<{id:number;chart:RhythmChartId}|null>(null),sent=useRef(false),arena=useRef<HTMLDivElement>(null),pointer=useRef<{x:number;y:number}|null>(null);
 const audio=useRef<AudioContext|null>(null),voices=useRef(new Set<OscillatorNode>()),muteRef=useRef(muted);muteRef.current=muted;
 const stopAudio=()=>{for(const voice of voices.current){try{voice.stop();}catch{}}voices.current.clear();};
 const armAudio=()=>{try{if(!audio.current||audio.current.state==="closed")audio.current=new AudioContext({latencyHint:"interactive"});void audio.current.resume().catch(()=>setAudioFailed(true));}catch{setAudioFailed(true);}};
 const tone=(frequency:number,at:number,length:number,volume:number,type:OscillatorType="sine")=>{
  const ctx=audio.current;if(!ctx||ctx.state!=="running"||muteRef.current)return;
  const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,at);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(volume,at+.008);gain.gain.exponentialRampToValueAtTime(.001,at+length);osc.connect(gain).connect(ctx.destination);voices.current.add(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();voices.current.delete(osc);};osc.start(at);osc.stop(at+length+.01);
 };
 const begin=(mode:Mode,id:number,chartId:RhythmChartId)=>{stopAudio();sent.current=false;run.current={chart:rhythmChart(chartId),mode,id,start:performance.now(),speed:mode==="practice"?.7:1,hits:Array(64).fill(null),strays:0,combo:0,bestCombo:0,feedback:"",feedbackAt:0,done:false};setElapsed(0);setPhase("playing");setOpen(true);requestAnimationFrame(()=>arena.current?.focus());};
 const launch=(mode:Mode)=>{armAudio();if(mode==="practice"){begin(mode,0,selected);return;}if(!player||busy)return;waiting.current={id:(player.rhythm?.cycle??0)+1,chart:selected};setPhase("waiting");setOpen(true);onAction({kind:"rhythmStart",cycle:player.rhythm?.cycle??0,chart:selected});};
 useEffect(()=>{if(phase==="waiting"&&waiting.current?.id===player?.rhythm?.active?.id){const expected=waiting.current!;waiting.current=null;const acknowledged=player!.rhythm!.active!.chart??"groove";if(acknowledged!==expected.chart){setPhase("aborted");return;}begin("challenge",expected.id,acknowledged);}},[player?.rhythm?.active?.id,phase]); // The acknowledged server run owns the reward.
 const abort=()=>{waiting.current=null;if(run.current)run.current.done=true;stopAudio();setPhase("aborted");};
 useEffect(()=>{if(phase!=="playing")return;let frame=0,lastPaint=0,nextNote=0,nextBeat=0;
  const tick=(time:number)=>{const r=run.current;if(!r||r.done)return;const chart=r.chart,t=(time-r.start)*r.speed;
   for(let i=0;i<64;i++)if(r.hits[i]===null&&t>chart.notes[i].at+RHYTHM_WINDOW){r.hits[i]=RHYTHM_MISS;r.combo=0;r.feedback="Raté";r.feedbackAt=t;}
   // Schedule against the audio clock ahead of rendering, avoiding frame-rate drift.
   const ctx=audio.current,lookahead=t+120*r.speed;if(ctx){while(nextNote<64&&chart.notes[nextNote].at<=lookahead){const note=chart.notes[nextNote],delay=(note.at-t)/r.speed/1000;if(delay>=0)tone(chart.melody[nextNote%chart.melody.length],ctx.currentTime+delay,.13,.045,"triangle");nextNote++;}while(3000+nextBeat*60000/chart.bpm<=lookahead){const at=3000+nextBeat*60000/chart.bpm,delay=(at-t)/r.speed/1000;if(delay>=0)tone(nextBeat%4?180:100,ctx.currentTime+delay,.045,.055);nextBeat++;}}
   if(t>=chart.duration){r.done=true;stopAudio();setElapsed(chart.duration);setPhase("result");return;}
   if(time-lastPaint>30){setElapsed(t);lastPaint=time;}frame=requestAnimationFrame(tick);
  };frame=requestAnimationFrame(tick);
  const hide=()=>{if(document.hidden)abort();};document.addEventListener("visibilitychange",hide);
  return()=>{cancelAnimationFrame(frame);document.removeEventListener("visibilitychange",hide);stopAudio();};
 },[phase]);
 useEffect(()=>{const r=run.current;if(phase==="result"&&r?.mode==="challenge"&&!sent.current&&!busy){sent.current=true;onAction({kind:"rhythmFinish",runId:r.id,hits:r.hits.map(h=>h??RHYTHM_MISS),strays:r.strays});}},[phase,busy,onAction]);
 useEffect(()=>()=>{stopAudio();void audio.current?.close().catch(()=>{});window.dispatchEvent(new CustomEvent("cookie-rhythm-playing",{detail:false}));},[]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent("cookie-rhythm-playing",{detail:phase==="playing"}));return()=>{window.dispatchEvent(new CustomEvent("cookie-rhythm-playing",{detail:false}));};},[phase]);
 const press=(x:number,y:number)=>{const r=run.current;if(!r||r.done)return;const t=(performance.now()-r.start)*r.speed;if(t<2200)return;const i=r.hits.findIndex(h=>h===null);if(i<0)return;const note=r.chart.notes[i],rect=arena.current?.getBoundingClientRect();if(!rect)return;
  const radius=Math.max(27,Math.min(36,rect.width*.047)),distance=Math.hypot(x-note.x/100*rect.width,y-note.y/100*rect.height),delta=Math.round(t-note.at);
  if(Math.abs(delta)<=RHYTHM_WINDOW&&distance<=radius+4){r.hits[i]=delta;r.bestCombo=Math.max(r.bestCombo,++r.combo);r.feedback=toneNames[Math.abs(delta)<=80?0:Math.abs(delta)<=145?1:2];if(audio.current)tone(1100,audio.current.currentTime,.055,.025);}
  else{r.strays=Math.min(1000,r.strays+1);r.combo=0;r.feedback=delta< -RHYTHM_WINDOW&&distance<=radius+4?"Trop tôt":"À côté";}r.feedbackAt=t;setElapsed(t);
 };
 const selection=rhythmChart(selected),record=rhythmRecord(player?.rhythm,selected),current=run.current,chart=phase==="waiting"?selection:current?.chart??selection,result=current?rhythmScore(current.hits.map(h=>h??RHYTHM_MISS),current.strays):null,saved=current?.mode==="challenge"&&player?.rhythm?.last?.runId===current.id?player.rhythm.last:null;
 const active=(player?.rhythm?.boostUntil??0)>now,first=current?.hits.findIndex(h=>h===null)??-1,hitCount=current?.hits.filter(h=>h!==null&&h!==RHYTHM_MISS).length??0;
 return <section className="rhythm-hub" aria-label="Mini-jeu de rythme">
  <header className="rhythm-heading"><div><span className="eyebrow">LE DÉFI RYTHMIQUE</span><h2>Tempo du jacuzzi<span>.</span></h2><p>Quatre pistes. Quatre façons de trouver le rythme.</p></div><div className={"rhythm-reward "+(active?"active":"")}><Activity size={24}/><div><strong>+25 % pendant 24 h</strong><span>{active?"Actif · encore "+duration((player?.rhythm?.boostUntil??0)-now):"Production et gains par clic"}</span></div>{active&&<Check size={19}/>}</div></header>
  <div className="rhythm-chart-picker" role="group" aria-label="Choisir une piste">{RHYTHM_CHARTS.map((c,i)=>{const best=rhythmRecord(player?.rhythm,c.id);return <button key={c.id} aria-pressed={selected===c.id} onClick={()=>setSelected(c.id)} style={{"--chart-color":c.color} as CSSProperties}><span className="rhythm-chart-number">0{i+1}</span><span><small>{c.level} · {c.bpm} BPM</small><strong>{c.name}</strong><span>{Math.ceil(c.duration/1000)} s · 64 cercles</span></span><b>{best?best.best.toLocaleString("fr-FR")+" %":"À découvrir"}</b></button>;})}</div>
  <div className="rhythm-launchpad" style={{"--rhythm-accent":selection.color} as CSSProperties}><div className="rhythm-preview" aria-hidden="true"><div className="rhythm-preview-path"/><span className="rhythm-demo-note first" style={{left:selection.notes[0].x+"%",top:selection.notes[0].y+"%"}}><i/>1</span><span className="rhythm-demo-note second" style={{left:selection.notes[1].x+"%",top:selection.notes[1].y+"%"}}><i/>2</span><span className="rhythm-demo-note third" style={{left:selection.notes[2].x+"%",top:selection.notes[2].y+"%"}}>3</span><span className="rhythm-track-label">{selection.name} <b>{selection.bpm} BPM</b></span></div><div className="rhythm-brief"><span className="rhythm-level">{selection.level}</span><h3>{selection.name}.</h3><p>{selection.description} Touche les cercles dans l’ordre, au rythme des anneaux.</p><div className="rhythm-targets"><span><b>64</b>cercles</span><span><b>82 %</b>précision minimum</span><span><b>8</b>ratés maximum</span></div><button className="button primary full" disabled={!player||busy} onClick={()=>launch("challenge")}><Play size={18}/>Jouer le défi · {Math.ceil(selection.duration/1000)} s<ArrowRight size={18}/></button><button className="button secondary full" onClick={()=>launch("practice")}><RotateCcw size={17}/>Entraînement · vitesse 70 %</button>{!player&&<p className="rhythm-small">Choisis ton prénom dans l’Arcade pour gagner le bonus. L’entraînement est déjà disponible.</p>}</div></div>
  <div className="rhythm-tips"><p><Target size={20}/><span><strong>Souris, tactile ou Z / X</strong>Vise à la souris et clique, ou appuie sur Z / X. Sur mobile, touche directement les cercles.</span></p><p><Headphones size={20}/><span><strong>Écoute la pulsation</strong>Chaque note indique le bon instant. L’anneau permet aussi de jouer sans son.</span></p><p><Trophy size={20}/><span><strong>Apprends sans rien perdre</strong>Essais gratuits et illimités. Les frappes à côté coûtent 1 point de précision. L’entraînement ne donne pas de bonus.</span></p></div>
  <div className="rhythm-record"><span>Record de {selection.name} <b>{record?record.best.toLocaleString("fr-FR")+" %":"À toi de jouer"}</b></span><span>{record?.wins??0} victoire(s) sur cette piste</span><span>Meilleur combo <b>{record?.combo??"—"}{record?.combo!==undefined?" / 64":""}</b></span><span>Le bonus reste après un prestige. Une victoire pendant son activation ne le cumule ni ne le prolonge.</span></div>
  <Dialog open={open} onOpenChange={value=>{if(!value)abort();setOpen(value);}}><DialogContent className="rhythm-dialog" showCloseButton={false}>
   <div className="rhythm-game-top"><div><DialogTitle>{chart.name}</DialogTitle><DialogDescription>{current?.mode==="practice"?"Entraînement · vitesse 70 % · sans récompense":"Défi · objectif 82 % · 8 ratés maximum"}</DialogDescription></div><div className="rhythm-game-tools"><button aria-label={muted?"Activer le son de la piste":"Couper le son de la piste"} onClick={()=>{setMuted(!muted);if(!muted)stopAudio();else armAudio();}}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button><button aria-label="Quitter la piste" onClick={()=>{abort();setOpen(false);}}><X size={20}/></button></div></div>
   {phase==="playing"&&current&&<><div className="rhythm-hud"><span><b>{current.combo}×</b>combo</span><span><b>{hitCount}/64</b>touchés</span><span><b>{current.hits.filter(h=>h===RHYTHM_MISS).length}/8</b>ratés</span><span><b>{Math.max(0,Math.ceil((chart.duration-elapsed)/current.speed/1000))} s</b>restantes</span></div><div className="rhythm-arena" ref={arena} tabIndex={0} role="application" aria-label="Piste de rythme. Visez les cercles numérotés, puis cliquez ou appuyez sur Z ou X." onContextMenu={e=>e.preventDefault()} onPointerMove={e=>{const rect=e.currentTarget.getBoundingClientRect();pointer.current={x:e.clientX-rect.left,y:e.clientY-rect.top};}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.currentTarget.focus({preventScroll:true});const rect=e.currentTarget.getBoundingClientRect();pointer.current={x:e.clientX-rect.left,y:e.clientY-rect.top};press(pointer.current.x,pointer.current.y);}} onKeyDown={e=>{if(["z","x"].includes(e.key.toLowerCase())){e.preventDefault();if(!e.repeat&&pointer.current)press(pointer.current.x,pointer.current.y);}}}>
    {elapsed<2200&&<div className="rhythm-countdown"><b>{Math.max(1,Math.ceil((2200-elapsed)/1000))}</b><span>Repère le cercle 1</span></div>}
    {chart.notes.map((note,i)=>{if(current.hits[i]!==null||elapsed<note.at-chart.approach||elapsed>note.at+RHYTHM_WINDOW||i>first+2)return null;const approach=Math.max(1,1+(note.at-elapsed)/chart.approach*1.3);return <div key={i} data-note={i+1} className={"rhythm-note "+(i===first?"next":"later")} style={{left:note.x+"%",top:note.y+"%","--approach":approach,"--note-color":i%4===0?"#ffd16b":i%4===1?"#a9efff":i%4===2?"#bdb0ff":"#8bf0bb"} as CSSProperties}><i className="rhythm-approach"/><span>{i+1}</span></div>;})}
    {current.feedback&&elapsed-current.feedbackAt<650&&<div className={"rhythm-feedback "+(toneNames.includes(current.feedback)?"hit":"miss")}>{current.feedback}</div>}
    <span className="rhythm-arena-help">VISE + CLIQUE · Z / X · TACTILE</span>
   </div><progress className="rhythm-progress" max={chart.duration} value={elapsed} aria-label="Progression de la piste"/>{audioFailed&&<p className="rhythm-small">Le son est indisponible. Suis les anneaux pour garder le rythme.</p>}</>}
   {phase==="waiting"&&<div className="rhythm-end" role="status"><Activity size={40}/><h3>La piste se prépare…</h3><p>{saveError||"Enregistrement de ta nouvelle tentative."}</p>{saveError&&<button className="button secondary" onClick={onRetry}>Réessayer la connexion</button>}</div>}
   {phase==="aborted"&&<div className="rhythm-end"><RotateCcw size={40}/><h3>On reprend quand tu veux.</h3><p>La partie s’arrête lorsque tu quittes la piste ou changes d’onglet. Aucun cookie perdu.</p><button className="button primary" onClick={()=>setOpen(false)}>Retour à la piste</button></div>}
   {phase==="result"&&result&&current&&<div className={"rhythm-end "+(result.passed?"passed":"")}><div className="rhythm-result-icon">{result.passed?<Trophy size={36}/>:<Target size={36}/>}</div><span className="rhythm-level">{current.mode==="practice"?"ENTRAÎNEMENT TERMINÉ":saved?"RÉSULTAT SAUVEGARDÉ":"SAUVEGARDE DU RÉSULTAT…"}</span><h3>{result.passed?current.mode==="practice"?"Le rythme est là !":"Bien joué, le crew !":"Encore un peu d’entraînement."}</h3><div className="rhythm-targets"><span><b>{result.accuracy.toLocaleString("fr-FR")}%</b>précision / 82 %</span><span><b>{result.misses}/8</b>ratés</span><span><b>{current.bestCombo}×</b>meilleur combo</span></div><p>{current.mode==="practice"?result.passed?"Prêt à essayer à vitesse normale ? Le défi permet de gagner le bonus.":"Repère les petits enchaînements. Attends que l’anneau touche le bord avant de frapper.":!saved?saveError||"Ton score est en cours de sauvegarde…":!saved.passed?result.misses>8?"Concentre-toi sur le prochain numéro. La piste est toujours la même.":"Tu touches les cercles : essaie maintenant de frapper plus près de la pulsation.":saved.rewarded?"+25 % de production et de gains par clic pendant 24 h. Le bonus est actif !":"Nouvelle victoire ! Ton bonus actuel garde son heure de fin."}</p>{current.strays>0&&<small>{current.strays} frappe(s) à côté · −{current.strays} point(s) de précision</small>}{saveError&&!saved&&current.mode==="challenge"&&<button className="button secondary" onClick={onRetry}>Réessayer la sauvegarde</button>}<div className="rhythm-end-actions"><button className="button primary" disabled={busy||(current.mode==="challenge"&&!saved)} onClick={()=>launch(current.mode)}><RotateCcw size={17}/>Rejouer</button><button className="button secondary" onClick={()=>setOpen(false)}>Retour</button></div></div>}
  </DialogContent></Dialog>
 </section>;
}
