"use client";
import { useState } from "react";
import { Orbit,Flame,Crown,Medal,Check,LockKeyhole,ArrowUpRight,Hand,UsersRound,Timer,RotateCcw,Sparkles } from "lucide-react";
import { CookieCatalogFilter } from "@/components/cookie-catalog-filter";
import { CookieItemIcon } from "@/components/cookie-icons";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { BUILDINGS,UPGRADES,COSMIC_CHAPTERS,TRIALS,TRIAL_UNLOCK,buildingUnlock,buildingUnlocked,buildingPrice,trialPrice,trialProduction,trialMedal,settleTrial,formatCookies as fmt,type CookiePlayer,type CookieAction } from "@/lib/cookie-game";
import {CookieVoyageWorlds} from "@/components/cookie-voyages";
import {CookieWonderProjects} from "@/components/cookie-wonder";
import {BuildingEvolution,buildingEvolution} from "@/components/cookie-building-evolution";
const medalName=(n:number)=>["","Bronze","Argent","Or"][n];
const duration=(s:number)=>Math.floor(s/60)+" min "+String(Math.floor(s%60)).padStart(2,"0")+" s";
export function CookieHorizons({player:p,now,busy,purchaseBusy=busy,onAction,onRecipes,onTrialTap,tapsBlocked,initialSection="chapter"}:{player:CookiePlayer|null;now:number;busy:boolean;purchaseBusy?:boolean;onAction:(a:CookieAction)=>void;onRecipes:()=>void;onTrialTap:(runId:number)=>void;tapsBlocked:boolean;initialSection?:string}){
 const [section,setSection]=useState(initialSection.split(":")[0]),[cancelId,setCancelId]=useState<number|null>(null);
 const [chapterFilter,setChapterFilter]=useState("all");
 const trialPreview=p&&section==="trials"&&p.trials?.active?{...p,trials:{...p.trials,active:{...p.trials.active,buildings:[...p.trials.active.buildings]}}}:null;if(trialPreview)settleTrial(trialPreview,now);
 const t=trialPreview?.trials?.active,spec=TRIALS.find(s=>s.id===t?.scenario),complete=t?.finishedAt!==undefined;
 const elapsed=t?Math.max(0,((t.finishedAt??now)-t.startedAt)/1000):0;
 return <section className="cookie-horizons">
 <CookieCatalogFilter label="Explorer les horizons" value={section} onChange={setSection} options={[{value:"chapter",label:"Au-delà des galaxies"},{value:"worlds",label:"Après le Jubilé"},{value:"trials",label:"Épreuves de maître"},{value:"wonder",label:"Chantier du crew"}]}/>
 {section==="worlds"&&<CookieVoyageWorlds player={p} now={now} busy={busy} onAction={onAction}/>}
 {section==="chapter"&&<>
  <header className="horizon-heading"><div><span className="eyebrow"><Orbit size={17}/>{COSMIC_CHAPTERS.length} CHAPITRES COSMIQUES</span><h2>Plus loin que l’impossible.</h2><p>Après le Jubilé, explore le Royaume des paradoxes, le Four des origines et le Dernier banquet : neuf bâtiments, quarante-cinq recettes et des règles propres à chaque monde, jusqu’à 10¹⁴⁷.</p><button className="button secondary" onClick={onRecipes}>Ouvrir les recettes cosmiques<ArrowUpRight size={16}/></button></div><img loading="lazy" decoding="async" src="/cosmic-bakery-island.webp" alt="Un four, une écurie stellaire et un jacuzzi sur une île de biscuit dans le cosmos" width={1536} height={1024}/></header>
  <CookieCatalogFilter label="Choisir un chapitre" value={chapterFilter} onChange={setChapterFilter} options={[{value:"all",label:"Tous les chapitres"},...COSMIC_CHAPTERS.map((c,i)=>({value:String(i),label:c.name}))]}/>
  {COSMIC_CHAPTERS.map((chapter,n)=>chapterFilter!=="all"&&chapterFilter!==String(n)?null:<section key={chapter.name} className="cosmic-chapter"><div className="cosmic-chapter-title"><span>CHAPITRE {n+1}</span><h3>{chapter.name}</h3></div><div className="cosmic-building-grid">{BUILDINGS.slice(chapter.from,chapter.to).map((b,j)=>{const i=chapter.from+j,unlocked=!!p&&buildingUnlocked(p,i),owned=p?.buildings[i]??0,price=p?buildingPrice(p,i,1,now):b.price;return <article key={b.id} className={unlocked?"is-unlocked":""}><BuildingEvolution id={b.id} owned={owned}/><small className="building-evolution-label">{buildingEvolution(owned).label}</small><span className="eyebrow">{unlocked?owned+" POSSÉDÉ(S)":"À "+fmt(buildingUnlock(i))+" COOKIES HISTORIQUES"}</span><h3>{b.name}</h3><p>{b.description}</p><small>{unlocked?"Trois cuissons et deux synergies à découvrir.":"Encore "+fmt(Math.max(0,buildingUnlock(i)-(p?.lifetime??0)))+" cookies à produire."}</small><div className="cosmic-price"><span>Prochain exemplaire</span><strong>{fmt(price)} <small>cookies</small></strong></div><button className="button primary full" disabled={!unlocked||purchaseBusy||!p||p.balance<price||owned>=1000} onClick={()=>onAction({kind:"buy",building:i,quantity:1,maxCost:price})}>{!unlocked?<><LockKeyhole size={15}/>Prochain horizon</>:owned>=1000?"Limite atteinte":p&&p.balance<price?"Réserve insuffisante":<>Acheter<ArrowUpRight size={15}/></>}</button></article>;})}</div></section>)}
  <p className="horizon-note">Les accès restent ouverts après un prestige. Les bâtiments et recettes suivent les règles habituelles de la fournée. Chaque synergie renforce un bâtiment précis : +0,2 % par installation source, avec un maximum de +50 % par recette avant les talents de maîtrise.</p>
 </>}
 {section==="trials"&&<>
  <div className="horizon-intro"><span className="eyebrow"><Medal size={17}/>LES ÉPREUVES DE MAÎTRE</span><h2>La même recette de départ. Ton savoir-faire.</h2><p>Une partie séparée, sans bonus de prestige. Ton empire continue de produire. Aucun cookie ni bâtiment de ton atelier n’est engagé.</p>{(!p||p.lifetime<TRIAL_UNLOCK)&&<p className="horizon-locked"><LockKeyhole size={16}/>Accès à {fmt(TRIAL_UNLOCK)} cookies produits au total.</p>}</div>
  <section className="trial-grand-prize"><Sparkles size={31}/><div><span className="eyebrow">À CHAQUE RÉUSSITE · MÊME EN REJOUANT</span><h3>Ton atelier ×2 pendant une heure.</h3><p>Fours, clics manuels et pilote doublés, en plus de la médaille et du décor. Le bonus commence quand tu récupères ta récompense et se combine avec le cookie doré et les surprises.</p><small>Une nouvelle réussite renouvelle 60 minutes, sans additionner les durées. Le temps continue hors ligne ; ton prestige conserve le bonus restant.</small></div><strong>×2<span>60 MIN</span></strong></section>
  {t&&spec&&<section className="trial-workbench" aria-label="Épreuve en cours"><header><div><span className="eyebrow">{complete?"ÉPREUVE RÉUSSIE":"TENTATIVE EN COURS"}</span><h3>{spec.name}</h3><p>{spec.rule}</p></div><strong className="trial-clock"><Timer size={19}/>{duration(elapsed)}</strong></header><div className="trial-metrics"><div><small>Production de l’épreuve</small><strong>{fmt(t.produced)} / {fmt(spec.target)}</strong></div><div><small>Réserve séparée</small><strong>{fmt(t.balance)}</strong></div><div><small>Production / seconde</small><strong>{fmt(trialProduction(t))}</strong></div>{spec.budget!==null&&<div><small>Budget d’achat restant</small><strong>{fmt(Math.max(0,spec.budget-t.spent))}</strong></div>}</div><progress max={spec.target} value={t.produced}/>
   {complete?<div className="trial-finish"><Medal size={38}/><div><strong>{medalName(trialMedal(elapsed,t.scenario))} · {duration(elapsed)}</strong><p>Médaille + décor + atelier ×2 pendant 1 heure. Active le bonus quand tu es prêt !</p></div><button className="button primary" disabled={busy} onClick={()=>onAction({kind:"trialClaim",runId:t.id})}>Activer mon bonus de 1 h</button></div>:<div className="trial-play">{spec.click>0&&<button className="trial-tap" disabled={tapsBlocked} onClick={()=>onTrialTap(t.id)}><Hand size={30}/><strong>Pétrir · +{spec.click}</strong><small>Cookies de l’épreuve uniquement</small></button>}<div className="trial-buildings">{spec.allowed.map(i=>{const price=trialPrice(t,i,1);return <button key={i} disabled={busy||t.balance<price||(spec.budget!==null&&t.spent+price>spec.budget)} onClick={()=>onAction({kind:"trialBuy",runId:t.id,building:i,quantity:1})}><CookieItemIcon kind="building" id={BUILDINGS[i].id} size={23}/><span><strong>{BUILDINGS[i].name}</strong><small>{t.buildings[i]} possédé(s) · +{fmt(BUILDINGS[i].cps*spec.scale)} / s</small></span><b>{fmt(price)}</b></button>;})}</div></div>}
   <footer><small>Or ≤ {duration(spec.gold)} · Argent ≤ {duration(spec.silver)} · Bronze à la réussite. Le chronomètre continue pendant ton absence.</small><button className="trial-abandon" disabled={busy} onClick={()=>setCancelId(t.id)}>Abandonner cette tentative</button></footer></section>}
  <div className="trial-cards">{TRIALS.map((s,i)=>{const best=p?.trials?.bests[s.id];return <article className={"trial-card trial-"+s.id} key={s.id}><div className="trial-card-art"><img loading="lazy" decoding="async" src="/cosmic-bakery-island.webp" alt="" style={{objectPosition:["15% center","50% center","90% center"][i]}}/><span><Medal size={25}/>{best?medalName(best.medal):"À CONQUÉRIR"}</span></div><div className="trial-card-copy"><h3>{s.name}</h3><p>{s.rule}</p><dl><div><dt>Objectif</dt><dd>{fmt(s.target)} cookies</dd></div><div><dt>Meilleur temps</dt><dd>{best?duration(best.seconds):"Aucune réussite"}</dd></div></dl><p className="trial-boost-prize"><Flame size={18}/><strong>Atelier ×2 · 1 heure</strong></p><p className="trial-reward"><Sparkles size={16}/>Décor « {s.decor} »</p><small>Bronze : décor · Argent : halo du compagnon · Or : couronne du maître.</small><button className="button primary full" disabled={!p||p.lifetime<TRIAL_UNLOCK||!!t||busy} onClick={()=>onAction({kind:"trialStart",scenario:s.id,cycle:p?.trials?.cycle??0})}>{t?.scenario===s.id?"Tentative en cours":best?"Rejouer pour gagner 1 h":"Commencer l’épreuve"}</button>{best&&<button className="button secondary full" disabled={busy||p?.decor===s.id} onClick={()=>onAction({kind:"decor",decor:s.id})}>{p?.decor===s.id?<><Check size={15}/>Décor équipé</>:"Équiper ce décor"}</button>}</div></article>;})}</div>
  {p?.decor&&<button className="button secondary" disabled={busy} onClick={()=>onAction({kind:"decor",decor:"default"})}><RotateCcw size={15}/>Revenir au décor classique</button>}
 </>}
 {section==="wonder"&&<CookieWonderProjects initialProjectId={initialSection.split(":")[1]} player={p} busy={busy} onAction={onAction}/>}
 <Dialog open={cancelId!==null} onOpenChange={open=>{if(!open)setCancelId(null);}}><DialogContent className="club-dialog"><DialogTitle>Recommencer une autre fois ?</DialogTitle><DialogDescription>Seule cette tentative sera abandonnée. Tes meilleurs temps, tes décors et ton atelier principal sont conservés.</DialogDescription><button className="button secondary" onClick={()=>setCancelId(null)}>Continuer l’épreuve</button><button className="button primary" disabled={busy} onClick={()=>{if(cancelId!==null)onAction({kind:"trialCancel",runId:cancelId});setCancelId(null);}}>Abandonner la tentative</button></DialogContent></Dialog>
 </section>;
}
