"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { Cookie,Factory,Flame,Hand,ArrowUpRight,Sparkles,Trophy,LockKeyhole,Check,RefreshCw,Star,Play,Cloud,LoaderCircle,Gift,TrendingUp } from "lucide-react";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Dialog,DialogContent,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { CookieLeaderboard } from "@/components/cookie-leaderboard";
import type { CookieStanding } from "@/lib/club";
import { CrewAvatar } from "@/components/crew-avatar";
import { celebrate } from "@/components/club-effects";
import { voterKey } from "@/lib/identity";
import { BUILDINGS,UPGRADES,COOKIE_AVATARS,COOKIE_ACHIEVEMENTS,COOKIE_MISSIONS,METRIC_LABELS,formatCookies as fmt,baseProduction,production,clickPower,buildingPrice,upgradeReady,prestigeGain,type CookiePlayer,type CookieAction } from "@/lib/cookie-game";
type Result={player:CookiePlayer;offline:number;acceptedClicks?:number};
type Attempt={author:string;id:string;action:CookieAction};
const OUTBOX="jacuzzi-cookie-pending-v1:";
function remember(a:Attempt){try{localStorage.setItem(OUTBOX+a.id,JSON.stringify(a));}catch{}}
function forget(a:Attempt){try{localStorage.removeItem(OUTBOX+a.id);}catch{}}
function pending(author:string):Attempt[]{try{return Object.keys(localStorage).filter(k=>k.startsWith(OUTBOX)).map(k=>{try{return JSON.parse(localStorage.getItem(k)||"null");}catch{return null;}}).filter((a):a is Attempt=>!!a&&voterKey(a.author)===voterKey(author)&&typeof a.id==="string"&&!!a.action&&typeof a.action.kind==="string");}catch{return [];}}
export function CookieGame({person,identify,onWardrobe,onProgress,standings}:{person:string;identify:(fn:(name:string)=>void)=>void;onWardrobe:()=>void;onProgress:(author:string,player:CookiePlayer)=>void;standings:CookieStanding[]}){
 const [player,setPlayer]=useState<CookiePlayer|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true),[now,setNow]=useState(Date.now()),[quantity,setQuantity]=useState<1|10|100>(1),[view,setView]=useState("atelier"),[optimistic,setOptimistic]=useState(0),[offline,setOffline]=useState(0),[prestigeOpen,setPrestigeOpen]=useState(false),[queue,setQueue]=useState<string[]>([]),[sparks,setSparks]=useState<{id:number;x:number;y:number;label:string}[]>([]);
 const live=useRef<CookiePlayer|null>(null),name=useRef(person),working=useRef(false),buffer=useRef(0),retry=useRef<Attempt|null>(null),epoch=useRef(0),seen=useRef<string[]>([]),uid=useRef(0),callback=useRef(onProgress);callback.current=onProgress;name.current=person;
 const key=voterKey(person),seenKey="jacuzzi-cookie-seen-v1:"+key;
 const accept=useCallback((data:Result,author:string)=>{if(!live.current||data.player.version>live.current.version||(data.player.version===live.current.version&&data.player.updated>=live.current.updated)){live.current=data.player;setPlayer(data.player);callback.current(author,data.player);}},[]);
 const send=useCallback(async(attempt:Attempt,token:number)=>{if(working.current)return;working.current=true;setBusy(true);setError("");retry.current=attempt;remember(attempt);try{const response=await fetch("/api/cookie",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(attempt)});const data=await response.json() as Result&{error?:string};if(token!==epoch.current||voterKey(attempt.author)!==voterKey(name.current))return;if(!response.ok){if(response.status<500&&response.status!==409){retry.current=null;forget(attempt);if(attempt.action.kind==="click")setOptimistic(n=>Math.max(0,n-(attempt.action.kind==="click"?attempt.action.count:0)));}throw Error(data.error||"La sauvegarde fait une pause.");}if(attempt.action.kind==="sync"&&!live.current&&data.offline>1)setOffline(data.offline);accept(data,attempt.author);retry.current=null;forget(attempt);if(attempt.action.kind==="click")setOptimistic(n=>Math.max(0,n-(attempt.action.kind==="click"?attempt.action.count:0)));}catch(e){if(token===epoch.current)setError((e as Error).message||"Connexion interrompue. Réessaie.");}finally{if(token===epoch.current){working.current=false;setBusy(false);}}},[accept]);
 const drain=useCallback(async(author:string,token:number)=>{const backlog=pending(author),memory=retry.current;if(memory&&voterKey(memory.author)===voterKey(author)&&!backlog.some(a=>a.id===memory.id))backlog.unshift(memory);for(const a of backlog){if(token!==epoch.current)return;await send(a,token);if(retry.current)return;}if(token===epoch.current)await send({author,id:crypto.randomUUID(),action:{kind:"sync"}},token);},[send]);
 const transact=(action:CookieAction)=>{if(!person){identify(()=>{});return;}if(working.current||retry.current)return;void send({author:person,id:crypto.randomUUID(),action},epoch.current);};
 useEffect(()=>{const token=++epoch.current;working.current=false;retry.current=null;buffer.current=0;live.current=null;setPlayer(null);setOptimistic(0);setBusy(false);setError("");setQueue([]);setOffline(0);setLoading(!!person);try{const value=JSON.parse(localStorage.getItem(seenKey)||"[]");seen.current=Array.isArray(value)?value:[];}catch{seen.current=[];}if(!person)return;
  const backlog=pending(person);setOptimistic(backlog.reduce((n,a)=>n+(a.action.kind==="click"?a.action.count:0),0));
  void drain(person,token).then(()=>{if(token===epoch.current)setLoading(false);});
  const poll=setInterval(()=>{if(!document.hidden&&!working.current&&!retry.current)void send({author:person,id:crypto.randomUUID(),action:{kind:"sync"}},token);},15000),flush=setInterval(()=>{if(working.current||retry.current||!buffer.current)return;const count=Math.min(25,buffer.current);buffer.current-=count;void send({author:person,id:crypto.randomUUID(),action:{kind:"click",count}},token);},800);
  const wake=()=>{if(!document.hidden&&!working.current&&!retry.current)void send({author:person,id:crypto.randomUUID(),action:{kind:"sync"}},token);};document.addEventListener("visibilitychange",wake);
  return()=>{epoch.current++;clearInterval(poll);clearInterval(flush);document.removeEventListener("visibilitychange",wake);const count=Math.min(25,buffer.current);if(count>0){buffer.current-=count;const a:Attempt={author:person,id:crypto.randomUUID(),action:{kind:"click",count}};remember(a);void fetch("/api/cookie",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(a),keepalive:true}).then(r=>{if(r.ok)forget(a);}).catch(()=>{});}};
 },[person,seenKey,accept,send,drain]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),200);return()=>clearInterval(id);},[]);
 useEffect(()=>{if(!player)return;const earned=[...COOKIE_AVATARS.filter(a=>player.lifetime>=a.threshold).map(a=>"avatar"+a.index),...player.achievements];setQueue(current=>[...current,...earned.filter(id=>!seen.current.includes(id)&&!current.includes(id))]);},[player?.lifetime,player?.achievements.join(",")]);
 const dismiss=()=>{const id=queue[0];if(id){seen.current=[...new Set([...seen.current,id])];try{localStorage.setItem(seenKey,JSON.stringify(seen.current));}catch{}}setQueue(q=>q.slice(1));};
 const tap=(event:React.MouseEvent<HTMLButtonElement>)=>{if(!person){identify(()=>{});return;}if(!player||retry.current)return;if(buffer.current>=25)return;buffer.current++;setOptimistic(n=>n+1);if(!matchMedia("(prefers-reduced-motion: reduce)").matches){const r=event.currentTarget.getBoundingClientRect(),id=++uid.current;setSparks(s=>[...s.slice(-11),{id,x:event.detail?event.clientX-r.left:r.width/2,y:event.detail?event.clientY-r.top:r.height/2,label:"+"+fmt(clickPower(player,now))}]);setTimeout(()=>setSparks(s=>s.filter(p=>p.id!==id)),950);event.currentTarget.animate([{transform:"scale(.94) rotate(-2deg)"},{transform:"scale(1) rotate(0)"}],{duration:160});}};
 const p=player,rate=p?production(p,now):0,power=p?clickPower(p,now):1;
 const elapsed=p?Math.min(15000,Math.max(0,now-p.updated)):0,boosted=p?Math.max(0,Math.min(p.rushUntil,p.updated+elapsed)-p.updated):0;
 const spendable=p?p.balance+baseProduction(p)*(elapsed+6*boosted)/1000:0,display=spendable+optimistic*power;
 const activeAvatar=queue[0]?.startsWith("avatar")?COOKIE_AVATARS.find(a=>"avatar"+a.index===queue[0]):undefined,activeAchievement=COOKIE_ACHIEVEMENTS.find(a=>a.id===queue[0]);
 useEffect(()=>{if(queue[0])celebrate("yes");},[queue[0]]);
 return <section className="cookie-game"><div className="cookie-heading"><div><span className="eyebrow"><Cookie size={18}/>L’ARCADE DU CREW</span><h1>COOKIE <em>JACUZZI.</em></h1><p>De la première miette à l’empire galactique.</p></div><div className="cookie-save"><Cloud size={17}/>{!person?"Choisis ton prénom":busy?"Sauvegarde…":error?"À resynchroniser":"Progression sauvegardée"}{person&&<small>{person} · partie personnelle</small>}</div></div>
 <Tabs value={view} onValueChange={setView} className="cookie-tabs"><TabsList className="cookie-nav"><TabsTrigger value="atelier"><Factory size={16}/>Atelier</TabsTrigger><TabsTrigger value="objectifs"><Gift size={16}/>Objectifs {p?.missions.length??0}/12</TabsTrigger><TabsTrigger value="succes"><Trophy size={16}/>Succès {p?.achievements.length??0}/30</TabsTrigger><TabsTrigger value="collection"><Sparkles size={16}/>Avatars</TabsTrigger><TabsTrigger value="classement"><TrendingUp size={16}/>Classement</TabsTrigger><TabsTrigger value="prestige"><Star size={16}/>Prestige</TabsTrigger></TabsList>
 {error&&<div className="error-banner" role="alert">{error}<button disabled={busy} onClick={()=>void drain(person,epoch.current)}>Réessayer</button></div>}
 {!person&&<div className="cookie-identify"><p>Choisis ton prénom pour retrouver ta partie et tes avatars.</p><button className="button primary" onClick={()=>identify(()=>{})}>C’est parti<ArrowUpRight size={17}/></button></div>}
 {loading&&person&&<p className="loading-line"><LoaderCircle className="spin" size={17}/>On préchauffe tes fours…</p>}
 {offline>1&&<div className="cookie-offline"><Flame size={18}/>Tes fours ont produit {fmt(offline)} cookies pendant ton absence.<button onClick={()=>setOffline(0)}>Merci les fours !</button></div>}
 <TabsContent value="atelier"><div className="cookie-workshop"><div className="cookie-machine"><div className="cookie-bank"><span>COOKIES EN RÉSERVE</span><strong>{fmt(display)}</strong><small><TrendingUp size={15}/>{fmt(rate)} / seconde <span>·</span> {fmt(power)} / clic</small></div><div className={"cookie-click-stage "+(p&&p.rushUntil>now?"has-rush":"")}><div className="cookie-halo" aria-hidden="true"/><button className="giant-cookie" onClick={tap} disabled={!!person&&(!p||!!retry.current)} aria-label="Produire des cookies"><span className="cookie-art" aria-hidden="true"/>{sparks.map(s=><i key={s.id} className="cookie-spark" style={{left:s.x,top:s.y}}>{s.label}</i>)}</button>{p&&p.rushUntil>now&&<span className="cookie-rush"><Flame size={16}/>FOURNÉE ×7 · {Math.ceil((p.rushUntil-now)/1000)} s</span>}</div><p className="cookie-tap-hint"><Hand size={15}/>Un clic. Une miette. Un empire.</p><button className={"golden-cookie "+(p&&now>=p.goldenReadyAt?"ready":"")} disabled={!p||now<p.goldenReadyAt||busy||!!retry.current} onClick={()=>transact({kind:"golden"})}><Sparkles size={20}/><span><strong>Le cookie doré</strong><small>{!p?"Une surprise après ton premier clic":now>=p.goldenReadyAt?"Récolte le bonus et lance 77 s de production ×7": "Revient dans "+Math.max(1,Math.ceil((p.goldenReadyAt-now)/1000))+" s"}</small></span></button><div className="cookie-mini-stats"><span><b>{fmt(p?.lifetime??0)}</b>produits au total</span><span><b>{fmt(p?.clicks??0)}</b>clics à ton actif</span><span><b>{p?.prestige??0}</b>étoiles de prestige</span></div><p className="cookie-rules">Les fours travaillent pendant ton absence, jusqu’à 8 h. Les succès et avatars sont permanents. Les votes du crew ont leur propre progression.</p></div>
 <div className="cookie-production"><div className="cookie-shop-heading"><div><span className="eyebrow">LA CHAÎNE DE PRODUCTION</span><h2>Fais grandir l’atelier.</h2></div><div className="cookie-bulk" role="group" aria-label="Quantité à acheter">{([1,10,100] as const).map(n=><button key={n} aria-pressed={quantity===n} onClick={()=>setQuantity(n)}>×{n}</button>)}</div></div><div className="cookie-building-list">{BUILDINGS.map((b,i)=>{const cost=p?buildingPrice(p,i,quantity):Math.ceil(b.price*(Math.pow(1.15,quantity)-1)/.15),owned=p?.buildings[i]??0;return <button key={b.id} className="cookie-building" disabled={!p||busy||!!retry.current||spendable<cost||owned+quantity>1000} onClick={()=>transact({kind:"buy",building:i,quantity})}><span className="building-icon"><Factory size={23}/><small>{String(i+1).padStart(2,"0")}</small></span><span className="building-copy"><strong>{b.name}</strong><small>{b.description}</small><span>+{fmt(b.cps)} / s de base · {fmt(cost)} cookies</span></span><span className="building-count">{owned}<small>possédés</small></span></button>;})}</div></div></div>
 <section className="cookie-upgrades"><div className="section-heading"><div><span className="eyebrow">LES RECETTES SECRÈTES</span><h2>Une autre dimension.</h2></div><span>{p?.upgrades.length??0} / 20 améliorations</span></div><div className="cookie-upgrade-grid">{UPGRADES.map(u=>{const owned=p?.upgrades.includes(u.id),ready=p&&upgradeReady(p,u);return <article key={u.id} className={owned?"purchased":""}><span className="upgrade-icon">{owned?<Check size={23}/>:<Flame size={23}/>}</span><h3>{u.name}</h3><p>{u.description}</p><small>{u.building!==undefined?u.owned+" × "+BUILDINGS[u.building].name:u.clicks?fmt(u.clicks)+" clics":fmt(u.earned??0)+" cookies produits"}</small><button className="button secondary full" disabled={!p||owned||!ready||busy||!!retry.current||spendable<u.price} onClick={()=>transact({kind:"upgrade",upgrade:u.id})}>{owned?"Acquise":ready?fmt(u.price)+" cookies":<><LockKeyhole size={14}/>À débloquer</>}</button></article>;})}</div></section></TabsContent>
 <TabsContent value="objectifs"><div className="cookie-section-intro"><span className="eyebrow">LES COMMANDES DU CREW</span><h2>Douze défis. De grandes fournées.</h2><p>Les récompenses sont à réclamer une seule fois et restent marquées après un prestige.</p></div><div className="cookie-missions">{COOKIE_MISSIONS.map(m=>{const progress=p?.[m.metric]??0,claimed=p?.missions.includes(m.id);return <article key={m.id}><Gift size={24}/><div><h3>{m.name}</h3><p>{fmt(progress)} / {fmt(m.target)} {METRIC_LABELS[m.metric]}</p><progress max={m.target} value={Math.min(m.target,progress)}/></div><button className="button secondary" disabled={!p||claimed||progress<m.target||busy||!!retry.current} onClick={()=>transact({kind:"mission",mission:m.id})}>{claimed?<><Check size={16}/>Réclamé</>:"+"+fmt(m.reward)+" cookies"}</button></article>;})}</div></TabsContent>
 <TabsContent value="succes"><div className="cookie-section-intro"><span className="eyebrow">LES EXPLOITS DE L’ARCADE</span><h2>La gloire a un goût de biscuit.</h2><p>30 succès permanents, indépendants de tes votes. Rejoue tes déblocages quand tu veux.</p></div><div className="cookie-achievements">{COOKIE_ACHIEVEMENTS.map(a=>{const earned=p?.achievements.includes(a.id);return <article key={a.id} className={earned?"earned":"locked"}>{earned?<Trophy size={27}/>:<LockKeyhole size={27}/>}<h3>{a.name}</h3><p>{fmt(a.target)} {METRIC_LABELS[a.metric]}</p>{earned?<button onClick={()=>setQueue(q=>[a.id,...q.filter(id=>id!==a.id)])}><Play size={14}/>Rejouer</button>:<progress value={Math.min(a.target,p?.[a.metric]??0)} max={a.target}/>}</article>;})}</div></TabsContent>
 <TabsContent value="collection"><div className="cookie-section-intro"><span className="eyebrow">LES COMPAGNONS GOURMANDS</span><h2>Six avatars. Une sacrée recette.</h2><p>Produis des cookies pour les débloquer, puis porte-les partout dans le QG.</p></div><div className="cookie-avatar-gallery">{COOKIE_AVATARS.map(a=>{const earned=!!p&&p.lifetime>=a.threshold;return <article key={a.index} className={earned?"earned":"locked"}><CrewAvatar name={a.name} index={a.index}/><span>{earned?"DÉBLOQUÉ":fmt(a.threshold)+" COOKIES"}</span><h3>{a.name}</h3>{earned?<><button className="button primary full" onClick={onWardrobe}>Passer au vestiaire<ArrowUpRight size={16}/></button><button className="cookie-replay" onClick={()=>setQueue(q=>["avatar"+a.index,...q.filter(id=>id!=="avatar"+a.index)])}><Play size={14}/>Rejouer la révélation</button></>:<p>Encore {fmt(Math.max(0,a.threshold-(p?.lifetime??0)))} cookies à produire.</p>}</article>;})}</div></TabsContent>
 <TabsContent value="classement"><CookieLeaderboard standings={standings} person={person}/></TabsContent>
 <TabsContent value="prestige"><div className="cookie-prestige"><Star size={58}/><span className="eyebrow">LE GRAND RECOMMENCEMENT</span><h2>Une nouvelle fournée.<br/><em>Une puissance éternelle.</em></h2><p>Repars avec un atelier vide, mais conserve tes succès, tes avatars, tes statistiques et tes étoiles. Chaque étoile donne +10 % à la production et à la puissance de base du clic.</p><div className="prestige-numbers"><span><b>{p?.prestige??0}</b>étoiles acquises</span><span><b>+{(p?.prestige??0)*10} %</b>bonus permanent</span><span><b>+{p?prestigeGain(p):0}</b>étoiles à récolter</span></div><button className="button primary" disabled={!p||prestigeGain(p)<1||busy||!!retry.current} onClick={()=>setPrestigeOpen(true)}><RefreshCw size={18}/>Préparer une nouvelle fournée</button><p className="fine-print">Première étoile à 1 milliard de cookies produits. Les suivantes demandent une production cumulée croissante. Les petits resets n’ajoutent pas de points gratuits.</p></div></TabsContent>
 </Tabs>
 <Dialog open={prestigeOpen} onOpenChange={setPrestigeOpen}><DialogContent className="club-dialog"><DialogTitle>Une nouvelle fournée ?</DialogTitle><DialogDescription>Ton solde, tes bâtiments et tes améliorations d’atelier repartent à zéro. Tes succès, avatars, objectifs réclamés et statistiques restent acquis. Tu gagnes {p?prestigeGain(p):0} étoile(s) permanente(s).</DialogDescription><button className="button primary full" onClick={()=>{setPrestigeOpen(false);transact({kind:"prestige"});}}>Confirmer le prestige</button><button className="button secondary full" onClick={()=>setPrestigeOpen(false)}>Garder mon atelier</button></DialogContent></Dialog>
 <Dialog open={!!(activeAvatar||activeAchievement)} onOpenChange={open=>{if(!open)dismiss();}}><DialogContent className="club-dialog unlock-dialog cookie-unlock"><div className="unlock-rays" aria-hidden="true"/><div className="unlock-orbits" aria-hidden="true"><i/><i/><i/></div><div className="unlock-content" key={queue[0]}><span className="unlock-kicker"><Cookie size={18}/>{activeAvatar?"NOUVEAU COMPAGNON":"SUCCÈS COOKIE JACUZZI"}</span><div className="unlock-prize">{activeAvatar?<CrewAvatar name={activeAvatar.name} index={activeAvatar.index}/>:<Trophy size={100}/>}</div><span className="unlock-threshold">L’ARCADE · TA COLLECTION PERMANENTE</span><DialogTitle>{activeAvatar?.name||activeAchievement?.name}</DialogTitle><DialogDescription>{activeAvatar?activeAvatar.name+" rejoint ton vestiaire. Porte-le dans toute la villa !":activeAchievement?fmt(activeAchievement.target)+" "+METRIC_LABELS[activeAchievement.metric]+". Cette réussite est acquise pour de bon.":""}</DialogDescription><button className="button primary full" onClick={dismiss}>Ça, c’est du croustillant !<Sparkles size={17}/></button><button className="unlock-continue" onClick={()=>{dismiss();setView(activeAvatar?"collection":"succes");}}>Voir ma collection Arcade</button></div></DialogContent></Dialog>
 </section>;
}
