"use client";
import {useState} from "react";
import {Flame,Compass,Sparkles,ScrollText,Check,LockKeyhole,ArrowUpRight,Medal,Hand,Moon,RefreshCw,ChefHat} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {CONTRACT_KINDS,CONTRACT_RANKS,SPECIALIZATIONS,contractTerms,contractRank,canInvest,formatCookies as fmt,type CookiePlayer,type CookieAction,type ContractKind,type Specialization} from "@/lib/cookie-game";
const STORIES={
 produce:{name:"Le goûter ne s’arrête jamais",subtitle:"GRANDE FOURNÉE",copy:"Les fours tiennent la promesse faite au crew.",verb:"Produire",unit:"cookies après la signature",note:"Fours, clics et pilote comptent. Les primes et cadeaux ne comptent pas.",Icon:Flame},
 spend:{name:"La brigade se remet en selle",subtitle:"GRAND CHANTIER",copy:"Le crew a sorti les tabliers. Il manque les fours.",verb:"Investir",unit:"cookies dans l’atelier",note:"Seuls les achats de bâtiments et de recettes effectués après la signature comptent.",Icon:Compass},
 catch:{name:"Livraison venue des étoiles",subtitle:"CHASSE AUX SURPRISES",copy:"Le ciel du jacuzzi a encore préparé un cadeau.",verb:"Attraper",unit:"surprises qui traversent l’écran",note:"Les objets volants comptent. Le bouton du cookie doré ne compte pas.",Icon:Sparkles}
} as const;
export const contractTitle=(kind:ContractKind)=>STORIES[kind].name;
const SCHOOL_ICONS={architect:Compass,artisan:Hand,watcher:Moon};
const countdown=(until:number,now:number)=>Math.max(1,Math.ceil((until-now)/60000))+" min";
export function CookieContracts({player,now,busy,onAction}:{player:CookiePlayer|null;now:number;busy:boolean;onAction:(action:CookieAction)=>void}){
 const [schoolOpen,setSchoolOpen]=useState(false),[choice,setChoice]=useState<Specialization>("architect"),[cancelContractId,setCancelContractId]=useState<number|null>(null);
 const p=player,book=p?.contracts,active=book?.active,unlocked=!!p&&p.lifetime>=1e6,rank=p?contractRank(p):CONTRACT_RANKS[0],nextRank=CONTRACT_RANKS.find(r=>r.at>(book?.completed??0)),school=SPECIALIZATIONS.find(s=>s.id===p?.specialization),SchoolIcon=school?SCHOOL_ICONS[school.id]:ChefHat,cooling=!!book&&now<book.nextAcceptAt,schoolCooling=!!p&&now<(p.specializationChangeAt??0);
 return <section className="cookie-contracts"><header className="contract-desk-heading"><div><span className="eyebrow">LES COMMANDES DU CREW</span><h2>Le bureau des fournées.</h2><p>Trois chemins. Une commande à la fois. À toi de choisir.</p></div><span className={"contract-rank-seal rank-"+rank.at}><Medal size={34}/><strong>{rank.name}</strong><small>{book?.completed??0} contrat{book?.completed===1?"":"s"} terminé{book?.completed===1?"":"s"}</small></span></header>
 <div className="contract-career"><div><strong>{nextRank?"Prochain sceau : "+nextRank.name:"Tous les sceaux sont acquis."}</strong>{nextRank&&<><progress max={nextRank.at} value={book?.completed??0}/><small>{book?.completed??0} / {nextRank.at} contrats · Ton parcours reste après un prestige.</small></>}</div><details><summary>Mon parcours</summary><ol>{CONTRACT_RANKS.map(r=><li key={r.at} className={(book?.completed??0)>=r.at?"earned":""}><Medal size={17}/><span>{r.name}</span><b>{r.at}</b></li>)}</ol><p>Les sceaux habillent ton compagnon dans l’atelier. Les nouveaux succès se rejouent dans Succès.</p></details></div>
 <div className="contract-school"><SchoolIcon size={24}/><div><strong>{school?.name??"Les trois écoles"}</strong><small>{school?.benefit??"Choisis ta spécialisation dès ta première étoile."}</small></div><button className="button secondary" disabled={!p||p.prestige<1} onClick={()=>{setChoice(p?.specialization??"architect");setSchoolOpen(true);}}>{!p?.prestige?<><LockKeyhole size={14}/>1 étoile</>:school?"Changer":"Choisir"}</button></div>
 {!unlocked?<div className="contract-locked"><LockKeyhole size={35}/><h3>Une nouvelle porte au million.</h3><p>Produis 1 million de cookies au total pour ouvrir le bureau. Ton premier contrat t’attendra ici.</p><progress max={1e6} value={Math.min(p?.lifetime??0,1e6)}/><small>{fmt(p?.lifetime??0)} / 1 M</small></div>:<>
 {active?<div className="contract-active-wrap" key={active.id}><ContractCard kind={active.kind} target={active.target} reward={active.reward} progress={active.progress} active busy={busy} onSelect={()=>onAction({kind:"contractClaim",contractId:active.id})}/><aside className="contract-active-notes"><span className="eyebrow">COMMANDE SIGNÉE</span><h3>Le prix de la promesse.</h3><p>La cible et la prime sont fixées. Un bon achat ou une fournée dorée peut t’aider à terminer plus vite.</p><p>Ce contrat n’expire pas et continue après un prestige. Son parcours appartient à l’école choisie au moment de la signature.</p><strong>{active.school?SPECIALIZATIONS.find(s=>s.id===active.school)?.name:"Sans spécialisation"}</strong><button className="contract-cancel" disabled={busy} onClick={()=>setCancelContractId(active.id)}>Abandonner ce contrat</button></aside></div>:<><p className="contract-availability">{cooling?"Prochaine signature dans "+countdown(book!.nextAcceptAt,now)+". Tu peux déjà préparer ton choix.":"Le bureau est ouvert. Quelle promesse fais-tu au crew ?"}</p><div className="contract-offers">{CONTRACT_KINDS.map(kind=>{const terms=contractTerms(p!,kind),possible=kind!=="spend"||canInvest(p!);return <ContractCard key={kind} kind={kind} target={terms.target} reward={terms.reward} busy={busy||cooling||!possible} unavailable={!possible} onSelect={()=>onAction({kind:"contractAccept",contract:kind,cycle:book?.cycle??0})}/>;})}</div></>}
 <p className="contract-fine-print">Une nouvelle signature toutes les 20 min, sans contrat actif. Primes réservées aux achats : elles n’ajoutent ni score ni étoiles. Les montants s’adaptent à ton atelier à la signature, hors bonus temporaires.</p></>}
 <Dialog open={schoolOpen} onOpenChange={setSchoolOpen}><DialogContent className="club-dialog contract-school-dialog"><DialogTitle>Ta façon de faire tourner l’atelier.</DialogTitle><DialogDescription>Une école active. Changement gratuit toutes les 20 min. Le choix reste acquis après un prestige.</DialogDescription><RadioGroup value={choice} onValueChange={v=>setChoice(v as Specialization)} aria-label="Choisir une école" className="school-options">{SPECIALIZATIONS.map(s=>{const Icon=SCHOOL_ICONS[s.id];return <label key={s.id} className={choice===s.id?"selected":""}><RadioGroupItem value={s.id} id={"school-"+s.id}/><Icon size={28}/><span><strong>{s.name}</strong><b>{s.benefit}</b><small>{s.description}</small></span></label>;})}</RadioGroup>{schoolCooling&&<p className="fine-print">Changement possible dans {countdown(p!.specializationChangeAt!,now)}.</p>}<button className="button primary full" disabled={busy||!p||p.prestige<1||schoolCooling||choice===p.specialization} onClick={()=>{if(p)onAction({kind:"specialize",specialization:choice,expectedChangeAt:p.specializationChangeAt??0});}}>{choice===p?.specialization?<><Check size={17}/>École active</>:"Adopter cette école"}</button><p className="fine-print">Le Veilleur doit être actif avant ton absence pour bénéficier des 12 h. Un changement ne récupère pas de production passée.</p></DialogContent></Dialog>
 <Dialog open={cancelContractId!==null} onOpenChange={open=>{if(!open)setCancelContractId(null);}}> <DialogContent className="club-dialog"><DialogTitle>Rendre cette commande ?</DialogTitle><DialogDescription>Seule la progression du contrat actif sera abandonnée. Ton atelier, ton parcours et tes cookies restent acquis. Le délai avant la prochaine signature reste le même.</DialogDescription><button className="button secondary full" onClick={()=>setCancelContractId(null)}>Garder la commande</button><button className="button primary full" disabled={busy||!active||active.id!==cancelContractId} onClick={()=>{if(cancelContractId!==null)onAction({kind:"contractCancel",contractId:cancelContractId});setCancelContractId(null);}}>Abandonner le contrat</button></DialogContent></Dialog>
 </section>;
}
function ContractCard({kind,target,reward,progress=0,active=false,busy,unavailable=false,onSelect}:{kind:ContractKind;target:number;reward:number;progress?:number;active?:boolean;busy:boolean;unavailable?:boolean;onSelect:()=>void}){
 const story=STORIES[kind],ready=active&&progress>=target,Icon=story.Icon;
 return <article className={"contract-ticket "+kind+(active?" signed":"")+(ready?" ready":"")}><div className="contract-ticket-art" aria-hidden="true"><span className="contract-orbit"/><Icon size={60}/>{active&&<b className="contract-stamp">{ready?"TERMINÉ":"SIGNÉ"}</b>}</div><span className="eyebrow">{story.subtitle}</span><h3>{story.name}</h3><p className="contract-story">{story.copy}</p><div className="contract-target"><small>{story.verb}</small><strong>{fmt(target)}</strong><span>{story.unit}</span></div>{active&&<div className="contract-progress"><progress max={target} value={Math.min(progress,target)}/><span>{fmt(Math.min(progress,target))} / {fmt(target)} · {Math.floor(Math.min(100,progress/target*100))} %</span></div>}<p className="contract-count-note">{story.note}</p><div className="contract-prize"><span>PRIME</span><strong>+{fmt(reward)}<small>cookies</small></strong><p>+1 contrat dans ton parcours</p></div><button className="button primary full" disabled={busy||active&&!ready} onClick={onSelect} aria-label={active?(ready?"Réclamer la prime de "+story.name:"Contrat en cours : "+story.name):"Signer : "+story.name}>{unavailable?"Atelier entièrement équipé":active?ready?<><Check size={17}/>Réclamer la prime</>:"Commande en cours":<><ScrollText size={17}/>Signer ce contrat<ArrowUpRight size={15}/></>}</button></article>;
}
