"use client";
import {useEffect,useRef,useState} from "react";
import {Maximize,Minimize,Music2,Volume2,VolumeX} from "lucide-react";
import {createCookieMusic,type CookieMusic} from "@/lib/cookie-music";
export function CookieControls(){
 const [full,setFull]=useState(false),[music,setMusic]=useState(false),[starting,setStarting]=useState(false),[volume,setVolume]=useState(30),[error,setError]=useState("");
 const sound=useRef<CookieMusic|null>(null),native=useRef(false),alive=useRef(true),request=useRef(0),scroll=useRef(0),button=useRef<HTMLButtonElement>(null);
 const leave=()=>{setFull(false);if(native.current&&document.fullscreenElement)void document.exitFullscreen().catch(()=>{});native.current=false;};
 const toggleFull=()=>{if(full){leave();return;}scroll.current=window.scrollY;setFull(true);if(!document.fullscreenElement&&document.documentElement.requestFullscreen)void document.documentElement.requestFullscreen().then(()=>{if(alive.current)native.current=true;else if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{});}).catch(()=>{});};
 useEffect(()=>{if(!full)return;document.body.classList.add("cookie-fullscreen");window.scrollTo({top:0,behavior:"instant"});const onChange=()=>{if(native.current&&!document.fullscreenElement){native.current=false;setFull(false);}};const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!document.querySelector('[role="dialog"]'))leave();};document.addEventListener("fullscreenchange",onChange);document.addEventListener("keydown",onKey);return()=>{document.body.classList.remove("cookie-fullscreen");document.removeEventListener("fullscreenchange",onChange);document.removeEventListener("keydown",onKey);window.scrollTo({top:scroll.current,behavior:"instant"});button.current?.focus({preventScroll:true});};},[full]);
 useEffect(()=>{alive.current=true;const onVisibility=()=>{if(document.hidden)sound.current?.pause();else if(sound.current)void sound.current.resume().catch(()=>{sound.current?.stop();sound.current=null;setMusic(false);setError("Relance la musique pour reprendre le son.");});};document.addEventListener("visibilitychange",onVisibility);return()=>{alive.current=false;request.current++;sound.current?.stop();sound.current=null;document.removeEventListener("visibilitychange",onVisibility);document.body.classList.remove("cookie-fullscreen");if(native.current&&document.fullscreenElement)void document.exitFullscreen().catch(()=>{});};},[]);
 const toggleMusic=async()=>{setError("");if(sound.current){sound.current.stop();sound.current=null;setMusic(false);return;}if(starting)return;const token=++request.current;setStarting(true);try{const player=await createCookieMusic(volume/100);if(!alive.current||token!==request.current){player.stop();return;}sound.current=player;setMusic(true);if(document.hidden)player.pause();}catch{if(alive.current)setError("La musique n’a pas pu démarrer. Réessaie.");}finally{if(alive.current)setStarting(false);}};
 return <div className="cookie-controls"><div className="cookie-control-buttons"><button ref={button} className="button secondary cookie-fullscreen-button" aria-pressed={full} onClick={toggleFull}>{full?<Minimize size={17}/>:<Maximize size={17}/>} {full?"Quitter le plein écran":"Plein écran"}</button><button className={"button secondary cookie-music-button "+(music?"playing":"")} aria-pressed={music} disabled={starting} onClick={()=>void toggleMusic()} aria-label={music?"Désactiver la musique":"Activer la musique"}>{music?<Music2 size={17}/>:<VolumeX size={17}/>} {starting?"Chargement…":music?"Musique activée":"Musique désactivée"}{music&&<span className="music-equalizer" aria-hidden="true"><i/><i/><i/></span>}</button></div>{music&&<label className="cookie-volume"><Volume2 size={15}/><span className="sr-only">Volume de la musique</span><input type="range" min="0" max="100" step="5" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);sound.current?.setVolume(v/100);}}/><output>{volume}%</output><small>Cookie Groove · 118 BPM</small></label>}{error&&<p role="status" className="form-error">{error}</p>}</div>;
}
