"use client";
import {useEffect,useRef,useState} from "react";
import {UsersRound,ArrowUpRight,Gift,Check,LockKeyhole,Sparkles,Flame,Image as ImageIcon,RotateCcw} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {WONDER_PROJECTS,WONDER_STAGES,wonderProjectAt,wonderUnlocked,formatCookies as fmt,type CookiePlayer,type CookieAction,type wonderSummary} from "@/lib/cookie-game";
type Wonder=ReturnType<typeof wonderSummary>;
type Project=typeof WONDER_PROJECTS[number];
export function useWonder(enabled=true){
 const [data,setData]=useState<Wonder|null>(null),[error,setError]=useState("");
 useEffect(()=>{if(!enabled)return;let active=true,request=0;const load=async()=>{const id=++request;try{const r=await fetch("/api/wonder",{cache:"no-store"});if(!r.ok)throw Error();const d=await r.json() as Wonder;if(active&&id===request){setData(d);setError("");}}catch{if(active&&id===request)setError("Le chantier ne répond pas. Réessaie.");}};void load();const tick=setInterval(()=>{if(!document.hidden)void load();},15000);const update=()=>void load();window.addEventListener("cookie-wonder-update",update);return()=>{active=false;clearInterval(tick);window.removeEventListener("cookie-wonder-update",update);};},[enabled]);
 return {data,error,reload:()=>window.dispatchEvent(new Event("cookie-wonder-update"))};
}
export function WonderArtwork({project,stage=3}:{project:Project;stage?:number}){
 const progress=Math.max(0,Math.min(3,stage));
 return <div className="wonder-art"><img loading="lazy" decoding="async" src={project.image} alt={project.name+(progress===3?", récompense complète":", chantier en cours")} width={1536} height={1024}/><img loading="lazy" decoding="async" className="wonder-art-built" src={project.image} alt="" aria-hidden="true" width={1536} height={1024} style={{clipPath:`inset(0 ${100-progress/3*100}% 0 0)`}}/></div>;
}
export function CookieWonderQG({onOpen}:{onOpen:(projectId:string)=>void}){
 const {data,error,reload}=useWonder(),[selected,setSelected]=useState<string|null>(null);
 const project=WONDER_PROJECTS.find(p=>p.id===selected)??wonderProjectAt(data?.stage??0),done=!!data&&wonderUnlocked(project.id,data.stage);
 return <section className="wonder-qg"><WonderArtwork project={project}/><div><span className="eyebrow"><Gift size={16}/>LES MERVEILLES DU CREW · {data?WONDER_PROJECTS.filter(p=>wonderUnlocked(p.id,data.stage)).length:0} / {WONDER_PROJECTS.length}</span><h2>{project.name}</h2><p>{error||(!data?"Le chantier se synchronise…":done?`Acquis pour tout le crew. Le décor « ${project.decor} » t’attend dans l’atelier.`:`À construire ensemble pour débloquer le décor « ${project.decor} ».`)}</p><div className="wonder-qg-gallery" aria-label="Les monuments du crew">{WONDER_PROJECTS.map(p=><button key={p.id} aria-pressed={p.id===project.id} onClick={()=>setSelected(p.id)} title={p.name}><img src={p.image} alt={p.short} width={90} height={60}/>{data&&wonderUnlocked(p.id,data.stage)?<Check size={14}/>:<LockKeyhole size={13}/>}</button>)}</div>{error?<button className="button secondary" onClick={reload}>Réessayer</button>:<button className="button secondary" onClick={()=>onOpen(project.id)}>{done?"Mes décors et les chantiers":"Découvrir la récompense"}<ArrowUpRight size={16}/></button>}</div></section>;
}
export function CookieWonderProjects({player:p,busy,onAction,initialProjectId}:{player:CookiePlayer|null;busy:boolean;onAction:(a:CookieAction)=>void;initialProjectId?:string}){
 const {data,error,reload}=useWonder(),[selected,setSelected]=useState<string|null>(initialProjectId??null),[preview,setPreview]=useState(false),[celebration,setCelebration]=useState<Project|null>(null),lastStage=useRef<number|null>(null);
 useEffect(()=>{if(!data)return;if(lastStage.current!==null){const previous=lastStage.current;const unlocked=WONDER_PROJECTS.filter(project=>previous<project.end&&data.stage>=project.end);if(unlocked.length)setCelebration(unlocked[unlocked.length-1]);}lastStage.current=data.stage;},[data]);
 const current=data?.stage??0,project=WONDER_PROJECTS.find(item=>item.id===selected)??wonderProjectAt(current),done=!!data&&wonderUnlocked(project.id,current),isCurrent=current>=project.start&&current<project.end,localStage=Math.max(0,Math.min(3,current-project.start)),active=p?.wonder?.active,equipped=p?.wonderDecor===project.id;
 return <div className="wonder-projects">
  <header className="horizon-intro"><span className="eyebrow"><UsersRound size={17}/>LES CHANTIERS DU CREW</span><h2>Construisons quelque chose qui reste.</h2><p>Quatre merveilles, quatre décors à gagner ensemble. Chaque projet se construit en trois étapes, avec quatre contributions par étape.</p></header>
  {error&&<p className="error-banner" role="alert">{error}<button onClick={reload}>Réessayer</button></p>}
  <div className="wonder-project-nav" aria-label="Choisir un chantier">{WONDER_PROJECTS.map((item,i)=>{const unlocked=!!data&&wonderUnlocked(item.id,current),ongoing=current>=item.start&&current<item.end;return <button key={item.id} aria-pressed={item.id===project.id} onClick={()=>setSelected(item.id)}><img loading="lazy" src={item.image} alt="" width={240} height={160}/><span className="wonder-project-number">0{i+1}</span><span className="wonder-project-label"><strong>{item.short}</strong><small>{!data?"Synchronisation…":unlocked?<><Check size={13}/>Récompense débloquée</>:ongoing?<><Flame size={13}/>Chantier en cours</>:<><LockKeyhole size={13}/>À construire ensuite</>}</small></span></button>;})}</div>
  <section className={"wonder-reward-hero"+(done?" is-unlocked":"")}>
   <button className="wonder-preview-button" onClick={()=>setPreview(true)} aria-label={"Agrandir la récompense : "+project.name}><WonderArtwork project={project}/><span><ImageIcon size={15}/>Voir la récompense en grand</span></button>
   <div className="wonder-reward-copy"><span className="wonder-reward-badge"><Gift size={17}/>{done?"RÉCOMPENSE DÉBLOQUÉE":"CE QUE NOUS ALLONS GAGNER"}</span><h3>{project.name}</h3><p>{project.description}</p><div className="wonder-prize"><Sparkles size={21}/><div><small>DÉCOR PERMANENT POUR TON ATELIER</small><strong>{project.decor}</strong><p>{project.ambience}</p></div></div><ul className="wonder-reward-perks"><li><Check size={15}/>Offert à tout le crew à la fin du projet</li><li><Check size={15}/>Monument conservé dans la galerie du QG</li><li><Check size={15}/>Décor conservé après chaque prestige</li></ul>{done?<button className="button primary full" disabled={!p||busy||equipped||!!error} onClick={()=>onAction({kind:"wonderDecor",decor:project.id})}>{equipped?<><Check size={17}/>Décor équipé</>:!p?"Choisis ton prénom pour l’équiper":"Équiper ce décor dans mon atelier"}</button>:<div className="wonder-unlock-condition"><LockKeyhole size={16}/>{!data?"Le chantier se synchronise…":isCurrent?`${localStage} / 3 étapes terminées pour gagner ce décor`:`Après ${WONDER_PROJECTS[WONDER_PROJECTS.indexOf(project)-1]?.short}`}</div>}</div>
  </section>
  {celebration&&<div className="wonder-celebration" role="status"><Gift size={28}/><div><strong>Le crew a débloqué {celebration.decor} !</strong><p>Votre monument est terminé. Le décor est maintenant disponible pour chacun.</p></div><button className="button primary" onClick={()=>{setSelected(celebration.id);setCelebration(null);}}>Voir ma récompense</button></div>}
  {data&&<><div className="wonder-construction-heading"><h3>{done?"Construit ensemble.":isCurrent?"Le chantier avance.":"Les prochaines étapes."}</h3><span>{localStage} / 3 étapes</span></div><ol className="wonder-stages">{data.stages.slice(project.start,project.end).map((stage,i)=>{const index=project.start+i;return <li key={stage.name} className={index<current?"built":index===current?"current":""}><span>{index<current?<Check size={18}/>:i+1}</span><div><strong>{stage.name}</strong><small>{stage.reward}</small><small>{stage.contributors.length?stage.contributors.map(c=>c.author).join(" · "):"Quatre membres du crew pour accomplir cette étape."}</small></div><b>{Math.min(4,stage.contributors.length)} / 4</b></li>;})}</ol>
   {active?<section className="wonder-personal"><Flame size={26}/><div><span className="eyebrow">TA CONTRIBUTION EN COURS · {wonderProjectAt(active.stage).short}</span><h3>{WONDER_STAGES[active.stage]?.name}</h3><p>{fmt(active.progress)} / {fmt(active.target)} cookies produits après ton engagement.</p><progress aria-label="Ta production pour le chantier" value={active.progress} max={active.target}/><small>{active.stage<current?"Cette étape est déjà construite. Termine ta livraison pour inscrire ta participation, puis rejoindre la suivante.":"Ta livraison apporte un quart de l’étape. Aucun cookie n’est prélevé."}</small></div><button className="button primary" disabled={busy||active.progress<active.target} onClick={()=>onAction({kind:"wonderDeliver",stage:active.stage})}>{active.progress>=active.target?"Livrer ma contribution":"Fournée en cours…"}</button></section>:isCurrent?<section className="wonder-personal"><UsersRound size={28}/><div><h3>{p?.wonder?.completed.includes(current)?"Ta part est livrée. Place au crew !":"Ta prochaine fournée fait avancer le crew."}</h3><p>L’objectif est fixé à l’engagement : 10 minutes de production de ton atelier et de ton pilote débloqué, hors bonus temporaires.</p><small>Fours et clics comptent. Les cadeaux et les épreuves ne comptent pas. Chacun apporte au maximum un quart de l’étape.</small></div><button className="button primary" disabled={busy||!!error||!p||p.lifetime<1000||p.wonder?.completed.includes(current)} onClick={()=>onAction({kind:"wonderStart",stage:current})}>{!p||p.lifetime<1000?"Accès à 1 000 cookies":p.wonder?.completed.includes(current)?"Contribution livrée":"Rejoindre cette étape"}</button></section>:!done?<button className="button secondary" onClick={()=>setSelected(wonderProjectAt(current).id)}>Revenir au chantier en cours<ArrowUpRight size={16}/></button>:null}
  </>}
  {(p?.decor||p?.wonderDecor)&&<button className="button secondary wonder-default" disabled={busy} onClick={()=>onAction({kind:"wonderDecor",decor:"default"})}><RotateCcw size={15}/>Revenir au décor classique</button>}
  <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="club-dialog wonder-preview-dialog"><DialogTitle>{project.name}</DialogTitle><DialogDescription>{done?"Récompense acquise pour tout le crew.":"Aperçu de la récompense à débloquer en terminant les trois étapes."} Décor « {project.decor} ».</DialogDescription><WonderArtwork project={project}/><p>{project.ambience}</p></DialogContent></Dialog>
 </div>;
}
