"use client";
import {ArrowRight,Star,RefreshCw,ShieldCheck,ChefHat} from "lucide-react";
import {masteryStarter,formatCookies as fmt,type CookiePlayer} from "@/lib/cookie-game";
import {prestigePreview} from "@/lib/cookie-insights";
const percent=(n:number)=>(n*100>=1e6?fmt(n*100):(n*100).toLocaleString("fr-FR",{maximumFractionDigits:1}))+" %";
const factor=(n:number)=>n>=1e6?fmt(n):n.toLocaleString("fr-FR",{maximumFractionDigits:1});
export function CookiePrestige({player,busy,onPrepare}:{player:CookiePlayer|null;busy:boolean;onPrepare:()=>void}){
 const x=player?prestigePreview(player):null,stars=(player?.prestige??0)+(x?.gain??0);
 return <section className="cookie-prestige"><Star size={58}/><span className="eyebrow">LE GRAND RECOMMENCEMENT</span><h2>Une nouvelle fournée.<br/><em>Un savoir qui reste.</em></h2><p>Chaque étoile ajoute 10 % au multiplicateur de base de production et de clic. Prépare ton retour : ta prochaine fournée aura sa réserve de départ et six objectifs renouvelables.</p><div className="prestige-numbers"><span><b>{fmt(player?.prestige??0)}</b>étoiles acquises</span><span><b>+{fmt(x?.gain??0)}</b>à récolter maintenant</span></div><div className="prestige-preview"><span>MULTIPLICATEUR PERMANENT</span><div><b>×{factor(x?.current??1)}</b><ArrowRight size={22}/><b>×{factor(x?.next??1)}</b><strong>+{percent(x?.relative??0)}</strong></div><small>Gain à atelier et recettes identiques, une fois reconstruits.</small></div>{x&&x.gain>0&&x.relative<.1&&<p className="prestige-advice">Petit gain pour une nouvelle reconstruction. Attendre au moins +10 % peut rendre le retour plus intéressant.</p>}<div className="prestige-plan"><article><ShieldCheck size={21}/><strong>Ton patrimoine reste</strong><p>Succès, avatars, clics, pilote, records, école, maîtrise, épreuves, objectif suivi, contrat actif, parcours et objectifs permanents réclamés.</p></article><article><ChefHat size={21}/><strong>Ton prochain atelier</strong><p>Bâtiments et recettes à reconstruire. {stars>0?fmt(player?masteryStarter(player,stars):275):"275"} cookies offerts au départ et six défis à refaire pour financer les achats.</p></article></div><button className="button primary" disabled={!x||x.gain<1||busy} onClick={onPrepare}><RefreshCw size={18}/>Préparer une nouvelle fournée</button><details className="prestige-milestones"><summary>Préparer un meilleur départ</summary><div>{x?.milestones.map(m=><span key={m.relative}><b>+{percent(m.relative)} de puissance</b><small>+{fmt(m.gain)} étoiles à récolter</small><strong>{m.remaining>0?fmt(m.remaining)+" cookies encore à produire":"Palier atteint"}</strong></span>)}</div><p className="fine-print">Repères par rapport à tes étoiles actuelles. Les aides de reconstruction ne comptent pas comme de la production.</p></details><p className="fine-print">{x?(x.nextStarGain>1?"Prochain palier (+"+fmt(x.nextStarGain)+" étoiles) : ":"Prochaine étoile : ")+fmt(x.remaining)+" cookies encore à produire.":"Première étoile à 1 milliard de cookies produits."} Un prestige réclame toujours au moins une nouvelle étoile.</p></section>;
}
