"use client";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import {Compass,Map,FlaskConical,Sparkles,Crown,Check,LockKeyhole,ArrowRight,Clock,BookOpen,RotateCcw,Flame} from "lucide-react";
import {CookieCatalogFilter} from "@/components/cookie-catalog-filter";
import {CrewAvatar} from "@/components/crew-avatar";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {FINAL_COOKIE_AVATAR,INGREDIENTS,VOYAGE_DESTINATIONS,SECRET_RECIPES,COOKIE_AVATARS,COMPANION_ROLES,BANQUET_COURSES,companionRecord,companionChallenges,companionCanEvolve,companionRole,secretCombination,secretCanCraft,voyageTeamBonus,voyageBuildingMultiplier,formatCookies as fmt,type CookiePlayer,type CookieAction,type IngredientId,type VoyageId} from "@/lib/cookie-game";
type Props={player:CookiePlayer|null;now:number;busy:boolean;onAction:(a:CookieAction)=>void;initialSection?:string};
const stageNames=["","Éclosion","Éveil","Légende"];
const timeLeft=(ms:number)=>{const s=Math.max(0,Math.ceil(ms/1000));return Math.floor(s/60)+" min "+String(s%60).padStart(2,"0")+" s";};
const ingredient=(id:string)=>INGREDIENTS.find(i=>i.id===id)!;
export function IngredientCost({cost,player,owned=false}:{cost:Partial<Record<IngredientId,number>>;player:CookiePlayer|null;owned?:boolean}){return <div className="voyage-ingredients">{Object.entries(cost).map(([id,n])=>{const i=ingredient(id),have=player?.voyages?.inventory[i.id]??0;return <span key={id} className={!owned&&have<n?"is-missing":""} style={{"--ingredient":i.color} as CSSProperties}><i aria-hidden="true">{i.symbol}</i><span>{i.name}<b>{owned?"+"+n:have+" / "+n}</b></span></span>;})}</div>;}
export function CompanionPortrait({index,name,stage=1}:{index:number;name:string;stage?:number}){return <div className={"companion-portrait companion-stage-"+stage} style={{backgroundImage:`url(/companion-shrine-${stage}.webp)`}}><CrewAvatar index={index} name={name}/><span className="companion-rank" aria-label={stageNames[stage]}>{stage===3?<Crown size={17}/>:<Sparkles size={16}/>} {stageNames[stage]}</span></div>;}
export function CookieVoyages({player:p,now,busy,onAction,initialSection="expeditions"}:Props){
 const [section,setSection]=useState(initialSection),[team,setTeam]=useState<number[]>([]),[selected,setSelected]=useState<VoyageId>("grove"),[filter,setFilter]=useState("earned"),[search,setSearch]=useState(""),[a,setA]=useState<IngredientId>("dew"),[b,setB]=useState<IngredientId>("cocoa"),[cancel,setCancel]=useState<number|null>(null),[revealed,setRevealed]=useState<{index:number;stage:2|3}|null>(null);
 const book=p?.voyages,revision=book?.revision??0,run=book?.active,chosen=VOYAGE_DESTINATIONS.find(d=>d.id===selected)!,destination=VOYAGE_DESTINATIONS.find(d=>d.id===run?.destination),ready=!!run&&now>=run.readyAt;
 const earned=useMemo(()=>COOKIE_AVATARS.filter(c=>p&&p.lifetime>=c.threshold),[p?.lifetime]);
 useEffect(()=>{if(earned.length)setTeam(current=>current.length?current.filter(id=>earned.some(c=>c.index===id)):earned.slice(0,3).map(c=>c.index));},[earned]);
 const combination=secretCombination(a,b),equipped=SECRET_RECIPES.find(r=>r.id===book?.equippedRecipe),shown=COOKIE_AVATARS.filter(c=>(filter==="all"||filter==="earned"&&!!p&&p.lifetime>=c.threshold||filter==="evolve"&&!!p&&(companionCanEvolve(p,c.index,2)||companionCanEvolve(p,c.index,3)))&&c.name.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")));
 const toggle=(id:number)=>setTeam(t=>t.includes(id)?t.filter(x=>x!==id):t.length<3?[...t,id]:t);
 return <section className="cookie-voyages">
  <header className="voyage-heading"><div><span className="eyebrow"><Compass size={17}/>LE CARNET DES VOYAGEURS</span><h2>Un monde à rapporter.</h2><p>Explore avec tes compagnons, rapporte des ingrédients et compose tes propres recettes.</p></div><div className="voyage-summary"><span><b>{book?.recipes.length??0}/9</b> recettes</span><span><b>{book?.relics.length??0}/12</b> souvenirs</span><span><b>{earned.filter(c=>p&&companionRecord(p,c.index).stage===3).length}/{COOKIE_AVATARS.length}</b> légendes</span></div></header>
  <CookieCatalogFilter label="Le carnet des voyageurs" value={section} onChange={setSection} options={[{value:"expeditions",label:"Expéditions"},{value:"companions",label:"Évolutions"},{value:"alchemy",label:"Recettes secrètes"},{value:"worlds",label:"Nouveaux mondes"}]}/>
  {section==="expeditions"&&<>
   {run&&destination?<article className="voyage-active" aria-label="Expédition en cours">
    <div className="voyage-active-art" style={{backgroundImage:`url('${destination.image}')`,...(destination.panel!==undefined?{backgroundSize:"300% 100%",backgroundPosition:destination.panel*50+"% center"}:{})}}/>
    <div className="voyage-active-copy"><span className="eyebrow">{run.step===2?"LE RETOUR":`RENCONTRE ${run.step+1} / 2`}</span><h3>{destination.name}</h3><div className="voyage-party">{run.team.map(id=><CrewAvatar key={id} index={id} name={COOKIE_AVATARS.find(c=>c.index===id)!.name}/>)}</div>
     <ol className="voyage-steps" aria-label="Étapes du voyage">{["Découverte","Passage","Retour"].map((label,i)=><li key={label} aria-current={run.step===i?"step":undefined} className={i<run.step?"is-done":""}>{i<run.step?<Check size={14}/>:i+1}<span>{label}</span></li>)}</ol>
     {!ready?<div className="voyage-wait"><Clock size={19}/><div><strong>{timeLeft(run.readyAt-now)}</strong><p>{run.step===2?"Tes compagnons rentrent avec leur récolte.":"Tes compagnons approchent de leur prochaine rencontre."} Tu peux continuer à jouer ou revenir plus tard.</p></div></div>:run.step<2?<>
      <p className="voyage-story">{destination.encounters[run.step as 0|1]}</p><div className="voyage-choices">
       <button className="button secondary" disabled={busy} onClick={()=>onAction({kind:"voyageChoice",runId:run.id,step:run.step as 0|1,choice:run.step===0?"gather":"safe"})}><strong>{run.step===0?"Récolter au passage":"Suivre le chemin éclairé"}</strong><span>+4 {ingredient(destination.primary).name}</span></button>
       <button className="button secondary" disabled={busy} onClick={()=>onAction({kind:"voyageChoice",runId:run.id,step:run.step as 0|1,choice:run.step===0?"study":"secret"})}><strong>{run.step===0?"Déchiffrer le mystère":"Explorer le passage secret"}</strong><span>+2 {ingredient(destination.secondary).name} · un souvenir</span></button>
      </div></>:<div className="voyage-return"><h4>Ta récolte est prête.</h4><IngredientCost cost={run.cargo} player={p} owned/><p>{run.secrets.length} souvenir(s) exploré(s) · chaque compagnon progresse.</p><button className="button primary full" disabled={busy} onClick={()=>onAction({kind:"voyageClaim",runId:run.id})}><Check size={18}/>Récupérer la récolte et les exploits</button></div>}
     {run.step<2&&<details className="voyage-cargo"><summary>Récolte déjà trouvée</summary><IngredientCost cost={run.cargo} player={p} owned/></details>}
     <button className="voyage-text-button" disabled={busy} onClick={()=>setCancel(run.id)}>Rappeler l’équipe</button>
    </div>
   </article>:<>
    {book?.last&&<div className="voyage-last" role="status"><Check size={20}/><div><strong>Récolte rangée dans ton garde-manger</strong><p>{Object.entries(book.last.cargo).map(([id,n])=>"+"+n+" "+ingredient(id).name).join(" · ")}{book.last.newRelics.length?" · "+book.last.newRelics.length+" nouveau(x) souvenir(s)":""}</p></div><button className="button secondary" onClick={()=>setSection("alchemy")}>Composer<ArrowRight size={16}/></button></div>}
    <div className="voyage-planner">
     <div><div className="voyage-section-title"><h3>1. Choisis ta destination</h3><span>Deux choix pendant le voyage</span></div><div className="voyage-destinations">{VOYAGE_DESTINATIONS.map(d=>{const unlocked=!!p&&p.lifetime>=d.threshold;return <button key={d.id} aria-pressed={selected===d.id} className={selected===d.id?"selected":""} onClick={()=>setSelected(d.id)}><div className="voyage-destination-art" style={{backgroundImage:`url('${d.image}')`,...(d.panel!==undefined?{backgroundSize:"300% 100%",backgroundPosition:d.panel*50+"% center"}:{})}}/><div><span>{unlocked?<><Compass size={13}/>{d.minutes} min minimum</>:<><LockKeyhole size={13}/>{fmt(d.threshold)} cookies</>}</span><strong>{d.name}</strong><small>{ingredient(d.primary).name} · {ingredient(d.secondary).name}</small></div></button>;})}</div></div>
     <aside className="voyage-launch"><span className="eyebrow">TON PROCHAIN VOYAGE</span><h3>{chosen.name}</h3><p>{chosen.description}</p><div className="voyage-section-title"><h4>2. Forme ton équipe</h4><span>{team.length}/3</span></div><p className="voyage-note">Affinité : {COMPANION_ROLES[chosen.affinity].name}. Chaque affinité et chaque stade gagné ajoutent un ingrédient au retour.</p>
      <div className="voyage-team-picker" role="group" aria-label="Compagnons de l’expédition">{earned.map(c=><button key={c.index} disabled={busy||team.length>=3&&!team.includes(c.index)} aria-pressed={team.includes(c.index)} onClick={()=>toggle(c.index)} title={c.name+" · "+COMPANION_ROLES[companionRole(c.index)].name}><CrewAvatar index={c.index} name={c.name}/><span>{c.name}</span>{team.includes(c.index)&&<Check size={14}/>}</button>)}</div>
      {!earned.length&&<p>Débloque ton premier compagnon en produisant des cookies.</p>}
      <div className="voyage-prize"><strong>Récolte garantie</strong><IngredientCost player={p} owned cost={{[chosen.primary]:4+(p?voyageTeamBonus(p,chosen,team):0),[chosen.secondary]:2}}/><small>Les deux rencontres ajoutent leurs récompenses. Aucun ingrédient n’est dépensé au départ.</small></div>
      <button className="button primary full" disabled={!p||p.lifetime<chosen.threshold||!team.length||busy} onClick={()=>onAction({kind:"voyageStart",destination:chosen.id,team,cycle:book?.cycle??0})}>{!p||p.lifetime<chosen.threshold?<><LockKeyhole size={17}/>Accès à {fmt(chosen.threshold)}</>:<>Partir en expédition<ArrowRight size={17}/></>}</button><small className="voyage-note">Une étape toutes les {chosen.minutes/3} min après ton choix. Les rencontres et récompenses t’attendent sans expiration.</small>
     </aside>
    </div>
   </>}
   <details className="voyage-souvenirs"><summary><BookOpen size={18}/>Les souvenirs du voyage · {book?.relics.length??0}/12</summary><div>{VOYAGE_DESTINATIONS.flatMap(d=>d.relics.map((name,i)=><article key={d.id+i} className={book?.relics.includes(d.id+":"+i)?"found":""}><span>{book?.relics.includes(d.id+":"+i)?<Check size={16}/>:<LockKeyhole size={16}/>}</span><strong>{book?.relics.includes(d.id+":"+i)?name:"Un secret à découvrir"}</strong><small>{d.name}</small></article>))}</div></details>
  </>}
  {section==="companions"&&<>
   <div className="voyage-section-title"><div><h3>Leur histoire, leurs exploits.</h3><p>Tes compagnons évoluent jusqu’à leur forme légendaire. Emmène-les en voyage pour débloquer leur éveil, puis leur forme légendaire animée. Le gardien final arrive directement en légende.</p></div>{book?.equippedCompanion!==undefined&&<button className="button secondary" disabled={busy} onClick={()=>onAction({kind:"companionEquip",companion:null,revision})}>Compagnon automatique</button>}</div>
   <div className="companion-tools"><CookieCatalogFilter label="Compagnons à faire évoluer" value={filter} onChange={setFilter} options={[{value:"earned",label:"Débloqués",count:earned.length},{value:"evolve",label:"Prêts à évoluer"},{value:"all",label:"Tous",count:COOKIE_AVATARS.length}]}/><label>Rechercher<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom d’un compagnon"/></label></div>
   <div className="companion-grid">{shown.map(c=>{const record=p?companionRecord(p,c.index):null,stage=record?.stage??1,next=stage===1?2:3,unlocked=!!p&&p.lifetime>=c.threshold,challenges=p?companionChallenges(p,c.index,next):[],can=unlocked&&companionCanEvolve(p!,c.index,next);return <article key={c.index} className={unlocked?"":"locked"}><CompanionPortrait index={c.index} name={c.name} stage={stage}/><div className="companion-copy"><span className="eyebrow">{COMPANION_ROLES[companionRole(c.index)].name}</span><h3>{c.name}</h3>{!unlocked?<p>À {fmt(c.threshold)} cookies historiques.</p>:<><div className="companion-stage-track" aria-label={"Stade "+stage+" sur 3"}>{[1,2,3].map(n=><span key={n} className={stage>=n?"earned":""}>{stage>=n?<Check size={13}/>:n}{stageNames[n]}</span>)}</div>{stage<3?<><strong className="companion-next">Pour atteindre {stageNames[next]}</strong>{challenges.map(goal=><div className="companion-goal" key={goal.label}><span>{goal.label}<b>{Math.min(goal.value,goal.target)}/{goal.target}</b></span><progress max={goal.target} value={Math.min(goal.value,goal.target)}/></div>)}<button className="button primary full" disabled={!can||busy} onClick={()=>{setRevealed({index:c.index,stage:next});onAction({kind:"companionEvolve",companion:c.index,stage:next,revision});}}><Sparkles size={16}/>{can?"Faire évoluer":"Exploits en cours"}</button></>:<p className="companion-legend"><Crown size={18}/>{c.index===FINAL_COOKIE_AVATAR.index?"Récompense finale · forme légendaire acquise dès le plafond.":"Forme légendaire, cadre et animation acquis."}</p>}<button className="button secondary full" disabled={busy||book?.equippedCompanion===c.index} onClick={()=>onAction({kind:"companionEquip",companion:c.index,revision})}>{book?.equippedCompanion===c.index?<><Check size={15}/>Dans ton atelier</>:"Choisir pour l’atelier"}</button></>}</div></article>;})}</div>
   {!shown.length&&<p className="cookie-catalog-empty">Aucun compagnon dans cette sélection. Les exploits progressent au retour des expéditions.</p>}
  </>}
  {section==="alchemy"&&<>
   <div className="voyage-pantry" aria-label="Garde-manger">{INGREDIENTS.map(i=><div key={i.id} style={{"--ingredient":i.color} as CSSProperties}><i aria-hidden="true">{i.symbol}</i><span>{i.name}<b>{fmt(book?.inventory[i.id]??0)}</b></span></div>)}</div>
   <div className="alchemy-bench"><div><span className="eyebrow"><FlaskConical size={17}/>À TOI DE COMPOSER</span><h3>Deux ingrédients. Un nouveau secret.</h3><p>Une découverte consomme les ingrédients indiqués et reste acquise. Tu peux ensuite changer gratuitement de recette active ; ses effets durent tant qu’elle est équipée.</p><div className="alchemy-selects">{([{label:"Premier ingrédient",value:a,set:setA},{label:"Second ingrédient",value:b,set:setB}]).map(field=><label key={field.label}>{field.label}<select value={field.value} onChange={e=>field.set(e.target.value as IngredientId)}>{INGREDIENTS.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>)}</div></div><div className="alchemy-result" aria-live="polite">{combination?<><span className="eyebrow">{book?.recipes.includes(combination.id)?"RECETTE DÉCOUVERTE":"UNE COMBINAISON PROMETTEUSE"}</span><h3>{book?.recipes.includes(combination.id)?combination.name:"Une recette à révéler"}</h3><p>{combination.description}</p><IngredientCost cost={combination.cost} player={p}/><button className="button primary full" disabled={!p||busy||!secretCanCraft(p,combination)} onClick={()=>onAction({kind:"secretCraft",recipe:combination.id,revision})}>{book?.recipes.includes(combination.id)?<><Check size={16}/>Déjà dans ton carnet</>:<><Sparkles size={16}/>Découvrir cette recette</>}</button></>:<><FlaskConical size={30}/><h3>Essaie une autre association.</h3><p>Cette combinaison ne donne pas de recette. Aucun ingrédient n’est consommé.</p></>}</div></div>
   <div className="alchemy-equipped"><Flame size={20}/><div><strong>{equipped?"Recette active · "+equipped.name:"Aucune recette active"}</strong><p>{equipped?.description??"Ta première découverte s’équipera automatiquement."}</p></div>{equipped&&<button className="button secondary" disabled={busy} onClick={()=>onAction({kind:"secretEquip",recipe:null,revision})}>Retirer</button>}</div>
   <div className="secret-recipes">{SECRET_RECIPES.map(r=>{const known=book?.recipes.includes(r.id),active=book?.equippedRecipe===r.id;return <article key={r.id} className={active?"active":""}><span className="eyebrow">{active?"DANS TON ATELIER":known?"DÉCOUVERTE":"INDICE DE RECETTE"}</span><h3>{known?r.name:Object.keys(r.cost).map(id=>ingredient(id).name).join(" + ")}</h3><p>{r.description}</p>{known?<button className="button secondary full" disabled={busy||active} onClick={()=>onAction({kind:"secretEquip",recipe:r.id,revision})}>{active?<><Check size={16}/>Équipée</>:"Équiper cette recette"}</button>:<><IngredientCost cost={r.cost} player={p}/><button className="button secondary full" onClick={()=>{const ids=Object.keys(r.cost) as IngredientId[];setA(ids[0]);setB(ids[1]);document.querySelector(".alchemy-bench")?.scrollIntoView({block:"start",behavior:"smooth"});}}>Essayer cette combinaison</button></>}</article>;})}</div>
  </>}
  {section==="worlds"&&<CookieVoyageWorlds player={p} now={now} busy={busy} onAction={onAction}/>}
  <p className="voyage-preservation">Compagnons, évolutions, ingrédients, recettes découvertes et souvenirs restent acquis après un prestige. Ton atelier continue de produire pendant les voyages.</p>
  <Dialog open={cancel!==null} onOpenChange={open=>{if(!open)setCancel(null);}}><DialogContent className="club-dialog"><DialogTitle>Rappeler tes compagnons ?</DialogTitle><DialogDescription>La récolte de cette expédition sera laissée sur place. Tes ingrédients déjà rangés et les exploits précédents restent acquis.</DialogDescription><button className="button secondary" onClick={()=>setCancel(null)}>Continuer le voyage</button><button className="button primary" disabled={busy} onClick={()=>{if(cancel!==null)onAction({kind:"voyageCancel",runId:cancel});setCancel(null);}}>Rappeler l’équipe</button></DialogContent></Dialog>
  <Dialog open={revealed!==null&&!busy&&!!p&&companionRecord(p,revealed.index).stage>=revealed.stage} onOpenChange={open=>{if(!open)setRevealed(null);}}><DialogContent className="club-dialog companion-reveal"><DialogTitle>{revealed!==null?COOKIE_AVATARS.find(c=>c.index===revealed.index)?.name:""}</DialogTitle><DialogDescription>Une nouvelle apparence et un ingrédient bonus lors de chaque prochaine expédition.</DialogDescription>{revealed!==null&&p&&<CompanionPortrait index={revealed.index} name={COOKIE_AVATARS.find(c=>c.index===revealed.index)!.name} stage={companionRecord(p,revealed.index).stage}/>}<button className="button primary" onClick={()=>setRevealed(null)}>Continuer l’aventure</button></DialogContent></Dialog>
 </section>;
}

export function CookieVoyageWorlds({player:p,now,busy,onAction}:Props){const book=p?.voyages,revision=book?.revision??0,course=book?.banquetCourse??0,next=BANQUET_COURSES[course];return <div className="voyage-worlds">{VOYAGE_DESTINATIONS.slice(3).map((d,i)=>{const unlocked=!!p&&p.lifetime>=d.threshold;return <article className="voyage-world" key={d.id}><div className="voyage-world-art" style={{backgroundImage:`url(${d.image})`}}/><div><span className="eyebrow">{unlocked?"MONDE OUVERT":"À "+fmt(d.threshold)+" COOKIES HISTORIQUES"}</span><h3>{d.name}</h3>{i===0?<><p>Inverse les fours renforcés : <b>Clarté</b> double le Four des reflets et le Palais ; <b>Miroir</b> triple le Jardin à rebours.</p><div className="world-mode-buttons">{(["light","mirror"] as const).map(mode=><button className="button secondary" key={mode} aria-pressed={(book?.paradoxMode??"light")===mode} disabled={!unlocked||busy||(book?.paradoxMode??"light")===mode||now<(book?.paradoxChangeAt??0)} onClick={()=>onAction({kind:"paradoxSwitch",mode,revision})}>{mode==="light"?"Clarté · ×2":"Miroir · ×3"}</button>)}</div><small>{now<(book?.paradoxChangeAt??0)?"Inversion disponible dans "+timeLeft(book!.paradoxChangeAt!-now):"Inversion gratuite, une fois par minute. Les gains écoulés gardent l’ancien réglage."}</small></>:i===1?<><p>Réunis autant de <b>Braises premières</b>, de <b>Noyaux de sucre</b> et de <b>Fours des origines</b> que possible. Chaque trio ajoute +2 % à ces trois bâtiments, jusqu’à ×2.</p><div className="world-bonus"><strong>+{Math.round(Math.min(1,Math.min(...[50,51,52].map(index=>p?.buildings[index]??0))/50)*100)} %</strong><span>{Math.min(...[50,51,52].map(index=>p?.buildings[index]??0))} trio(s) dans cette fournée</span></div><small>Le bonus suit les bâtiments possédés. Les recettes et synergies s’y ajoutent.</small></>:<><p>Prépare les trois services du banquet avec les ingrédients des voyages. Ils renforcent définitivement les trois derniers bâtiments.</p><div className="world-bonus"><strong>×{BANQUET_COURSES[course-1]?.multiplier??1}</strong><span>{course}/3 services préparés</span></div>{next?<><h4>{next.name} · prochain bonus ×{next.multiplier}</h4><IngredientCost cost={next.cost} player={p}/><button className="button primary full" disabled={!unlocked||busy||Object.entries(next.cost).some(([id,n])=>(book?.inventory[id as IngredientId]??0)<n)} onClick={()=>onAction({kind:"banquetPrepare",course,revision})}>Préparer ce service</button></>:<p className="companion-legend"><Crown size={18}/>Le banquet des 34 est servi. Bonus ×2 permanent.</p>}</>}{!unlocked&&<p className="voyage-world-lock"><LockKeyhole size={15}/>Encore {fmt(Math.max(0,d.threshold-(p?.lifetime??0)))} cookies historiques.</p>}</div></article>;})}</div>;}
