import type { CSSProperties } from "react";
import { Utensils,Microwave,ChefHat,Wheat,Sprout,Factory,FlaskConical,DoorOpen,Orbit,Telescope,WandSparkles,Flame,UsersRound,BookOpen,Leaf,Droplets,Beaker,Waypoints,Earth,Sparkles,Bean,Candy,Atom,ScanEye,Eclipse,Rocket,ThumbsUp,Footprints,Drum,AudioLines,Cookie,CookingPot,Wind,Package,AlarmClock,Coins,Bath,Castle,Infinity,MousePointer2,Music2,CircleCheck,Hand,Crown,Hammer,Wrench,House,Warehouse,Network,Ruler,Building2,RefreshCw,Hourglass,GraduationCap,Sun,Check,LockKeyhole,ScrollText,Medal,BriefcaseBusiness,PenTool,Compass,type LucideIcon } from "lucide-react";
const buildings:Record<string,LucideIcon>={spoon:Utensils,oven:Microwave,crew:ChefHat,bakery:Wheat,cocoa:Sprout,caramel:Factory,lab:FlaskConical,portal:DoorOpen,planet:Orbit,galaxy:Telescope};
const upgrades:Record<string,LucideIcon>={spoon_double:WandSparkles,oven_double:Flame,crew_double:UsersRound,bakery_double:BookOpen,cocoa_double:Leaf,caramel_double:Droplets,lab_double:Beaker,portal_double:Waypoints,planet_double:Earth,galaxy_double:Sparkles,cocoa_master:Bean,caramel_master:Candy,lab_master:Atom,portal_master:ScanEye,planet_master:Eclipse,galaxy_master:Rocket,thumb:ThumbsUp,hooves:Footprints,rhythm:Drum,cadence:AudioLines,spoon_master:WandSparkles,oven_master:Flame,crew_master:ChefHat,bakery_master:BookOpen,...Object.fromEntries(Object.entries(buildings).map(([id,icon])=>[id+"_signature",icon])),whisk:Wind,mixer:Factory,thunder:Flame,starlight:Sparkles,pulse:Drum,resonance:AudioLines};
const achievements:Record<string,LucideIcon>={contract0:PenTool,contract1:Package,contract2:BriefcaseBusiness,contract3:Medal,contract4:Crown,contractVariety0:Waypoints,contractVariety1:Compass,contractSchool0:GraduationCap,bake0:Cookie,bake1:CookingPot,bake2:Wind,bake3:Package,bake4:AlarmClock,bake5:Coins,bake6:Bath,bake7:Castle,bake8:Earth,bake9:Infinity,click0:MousePointer2,click1:Music2,click2:CircleCheck,click3:ThumbsUp,click4:Hand,click5:Drum,click6:Footprints,click7:Crown,build0:Hammer,build1:Wrench,build2:House,build3:Warehouse,build4:Factory,build5:Network,build6:Ruler,build7:Building2,prestige0:RefreshCw,prestige1:Hourglass,prestige2:GraduationCap,prestige3:Sun,...Object.fromEntries([...[Flame,Sun,Coins,Sparkles,Crown,Beaker].map((icon,i)=>["golden"+i,icon]),...[BookOpen,Leaf,ChefHat,GraduationCap,Package,Crown].map((icon,i)=>["recipe"+i,icon]),...[Utensils,Warehouse,Waypoints,Network].map((icon,i)=>["diversity"+i,icon]),...[Wind,Droplets,Wheat,Factory,Earth,Orbit].map((icon,i)=>["flow"+i,icon]),...[Sparkles,Sun,Orbit,Infinity].map((icon,i)=>["prestige"+(i+4),icon]),...[Flame,Candy,Footprints,Infinity].map((icon,i)=>["bake"+(i+10),icon])])};
const colors=["#ffd28a","#ff9a75","#ffc7df","#efca7a","#9edc94","#eab78f","#7bdcd0","#c4a0ff","#96bbff","#daafff"];
export const COOKIE_ICON_MAPS={building:buildings,upgrade:upgrades,achievement:achievements};
export function CookieItemIcon({kind,id,size=26,state}:{kind:keyof typeof COOKIE_ICON_MAPS;id:string;size?:number;state?:"locked"|"earned"|"legendary"}){
 const map=COOKIE_ICON_MAPS[kind],Icon=map[id]??Cookie,index=Object.keys(map).indexOf(id),color=kind==="achievement"?id.startsWith("prestige")?"#d4b3ff":id.startsWith("click")?"#8bddd0":id.startsWith("build")?"#99bfff":"#ffd28a":colors[Math.max(0,index)%colors.length];
 return <span className={"cookie-item-icon "+(state??"")} style={{"--item-color":color,"--item-size":size+"px"} as CSSProperties} aria-hidden="true" data-cookie-icon={kind+":"+id}><Icon size={size} strokeWidth={1.8}/>{state&&<span className="cookie-icon-status">{state==="locked"?<LockKeyhole size={11}/>:state==="legendary"?<Crown size={11}/>:<Check size={11}/>}</span>}</span>;
}
