"use client";
import { useRef, useState, type CSSProperties, type FormEvent } from "react";
import { ArrowUpRight, Check, Clock3, Coins, FlipHorizontal2, LoaderCircle, MapPin, MessageCircle, Pencil, Send, Sparkles, Users } from "lucide-react";
import { CREW, dateLabel, type ActivityDetails, type ClubState, type Proposal } from "@/lib/club";
import { CrewAvatar } from "@/components/crew-avatar";
import { voterKey } from "@/lib/identity";

export type SocialProps={state:ClubState;person:string;identify:(work:(name:string)=>void)=>void;save:(body:Record<string,unknown>)=>Promise<unknown>};
const colors=["#dfff00","#91a5ff","#ff9ccf","#62e8c7","#ffa679","#c3a3ff","#ffe795","#80d7ff","#ffbca8","#86efb0","#c9cfff"];
export function CrewCards({state}:{state:ClubState}){
  const [flipped,setFlipped]=useState<string[]>([]);
  return <section className="crew-collection"><div className="section-heading"><div><span className="eyebrow muted">ÉDITION LIMITÉE · 11 EXEMPLAIRES</span><h2>Le crew. Version légendaire.</h2></div><span className="section-note"><FlipHorizontal2 size={18}/>Retourne une carte</span></div><div className="crew-deck">{CREW.map((name,i)=>{
    const match=(n:string)=>voterKey(n)===voterKey(name);const proposals=state.proposals.filter(p=>match(p.author));const votes=state.votes.filter(v=>match(v.author));const comments=state.comments.filter(v=>match(v.author));const flip=flipped.includes(name);
    return <button key={name} className={`holo-card ${flip?"flipped":""}`} style={{"--crew-color":colors[i],"--i":i} as CSSProperties} aria-pressed={flip} aria-label={`Carte de ${name}, ${flip?"revenir au recto":"voir ses contributions"}`} onClick={()=>setFlipped(f=>f.includes(name)?f.filter(n=>n!==name):[...f,name])} onPointerMove={e=>{if(e.pointerType!=="mouse"||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--holo-x",`${(e.clientX-r.left)/r.width*100}%`);e.currentTarget.style.setProperty("--holo-y",`${(e.clientY-r.top)/r.height*100}%`);}}><span className={`holo-inner ${flip?"showing-stats":""}`} key={`${name}-${flip}`}><span className="holo-front" aria-hidden={flip}><span className="card-serial">34 / {String(i+1).padStart(2,"0")}<Sparkles size={15}/></span><CrewAvatar name={name} className="crew-monogram"/><strong>{name}</strong><span className="card-edition">JACUZZI CLUB · SEPT. 2026</span></span><span className="holo-back" aria-hidden={!flip}><strong>{name}</strong><span className="crew-stat"><b>{proposals.length}</b>proposition{proposals.length!==1?"s":""}</span><span className="crew-stat"><b>{votes.length}</b>votes</span><span className="crew-stat"><b>{comments.length}</b>message{comments.length!==1?"s":""}</span><small>{votes.filter(v=>v.value===1).length} pour · {votes.filter(v=>v.value===0).length} neutres · {votes.filter(v=>v.value===-1).length} contre</small></span></span></button>;
  })}</div><p className="fine-print">Contributions associées aux prénoms déclarés. Un vote par prénom et par proposition.</p></section>;
}

export function Discussion({proposal,...s}:SocialProps&{proposal:Proposal}){
  const [text,setText]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [sent,setSent]=useState(false);const attempt=useRef<{body:string;id:string}|null>(null);const guard=useRef(false);
  const comments=s.state.comments.filter(c=>c.proposalId===proposal.id);
  const submit=(e:FormEvent)=>{e.preventDefault();if(!text.trim()||guard.current)return;s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);setError("");setSent(false);const body=text.trim();if(attempt.current?.body!==body)attempt.current={body,id:crypto.randomUUID()};try{await s.save({action:"comment",id:attempt.current.id,proposalId:proposal.id,author,body});setText("");attempt.current=null;setSent(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);guard.current=false;}});};
  return <section className="discussion" aria-label={`Discussion : ${proposal.title}`}><div className="social-heading"><h3><MessageCircle size={20}/>Le petit débat</h3><span>{comments.length} message{comments.length!==1?"s":""}</span></div>{comments.length?<ol className="comment-list">{comments.map(c=><li key={c.id}><CrewAvatar name={c.author} small/><div><header><strong>{c.author}</strong><time dateTime={c.created}>{dateLabel(c.created,{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</time></header><p>{c.body}</p></div></li>)}</ol>:<p className="discussion-empty">Une question, un détail à partager ? Ouvre le débat.</p>}<form onSubmit={submit}><label htmlFor={`comment-${proposal.id}`}>Ton message {s.person&&<span>· {s.person}</span>}</label><textarea disabled={busy} id={`comment-${proposal.id}`} value={text} maxLength={1500} rows={3} onChange={e=>{setText(e.target.value);setSent(false);}} placeholder="Je suis chaud, mais on mange avant ?" required/><div className="comment-submit"><small>{text.length}/1500</small><button className="button primary" type="submit" disabled={busy||!text.trim()}>{busy?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>} {busy?"Envoi…":"Envoyer"}</button></div>{error&&<p className="form-error" role="alert">{error}</p>}{sent&&<p className="inline-success" role="status"><Check size={15}/>Message envoyé au crew.</p>}</form></section>;
}

export function ActivityFields({details}:{details?:ActivityDetails}){return <div className="practical-fields"><div className="field-pair"><label>Prix par personne (€)<input name="cost" type="number" min="0" max="10000" step="0.01" defaultValue={details?.costCents==null?"":details.costCents/100} placeholder="À confirmer"/></label><label>Capacité maximale<input name="capacity" type="number" min="1" max="10000" step="1" defaultValue={details?.capacity??""} placeholder="À confirmer"/></label></div><label>Adresse<input name="address" maxLength={300} defaultValue={details?.address||""} placeholder="Nom du lieu, rue, ville"/></label><label>Trajet depuis l’Airbnb<input name="travel" maxLength={200} defaultValue={details?.travel||""} placeholder="≈ 15 min en voiture · 11 km"/></label><label>Détail des tarifs<textarea name="pricing" maxLength={1500} rows={3} defaultValue={details?.pricing||""} placeholder="Tarif de groupe, location, suppléments…"/></label><label>Infos utiles<textarea name="notes" maxLength={3000} rows={4} defaultValue={details?.notes||""} placeholder="Réservation, équipement, contact, organisation…"/></label><p className="fine-print">Laisse les champs inconnus vides. 0 € signifie gratuit.</p></div>;}
export function readActivityFields(form:FormData){return {costCents:form.get("cost")?Math.round(Number(form.get("cost"))*100):null,capacity:form.get("capacity")?Number(form.get("capacity")):null,address:String(form.get("address")||""),travel:String(form.get("travel")||""),pricing:String(form.get("pricing")||""),notes:String(form.get("notes")||"")};}
export function ActivityPractical({proposal,...s}:SocialProps&{proposal:Proposal}){
  const d=s.state.activityDetails.find(d=>d.proposalId===proposal.id);const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [saved,setSaved]=useState(false);
  const minutes=proposal.start&&proposal.end?Math.round((+new Date(proposal.end)-+new Date(proposal.start))/60000):0;
  const submit=(e:FormEvent)=>{e.preventDefault();const values=readActivityFields(new FormData(e.currentTarget as HTMLFormElement));s.identify(async author=>{setBusy(true);setError("");try{await s.save({action:"details",proposalId:proposal.id,author,...values});setEditing(false);setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}});};
  return <section className="practical"><div className="social-heading"><h3>Le concret, avant de partir.</h3><button className="icon-button" onClick={()=>{setEditing(!editing);setSaved(false);}} aria-label={editing?"Fermer la modification des infos":"Modifier les infos pratiques"}><Pencil size={17}/></button></div>{editing?<form onSubmit={submit}><fieldset disabled={busy}><ActivityFields details={d}/></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Enregistrer les infos</button></form>:<><div className="practical-grid"><div><Coins size={19}/><span>Par personne</span><strong>{d?.costCents==null?"À confirmer":d.costCents===0?"Gratuit":`${(d.costCents/100).toLocaleString("fr-FR")} €`}</strong></div><div><Clock3 size={19}/><span>Créneau prévu</span><strong>{minutes?`${Math.floor(minutes/60)} h${minutes%60?` ${minutes%60}`:""}`:"À définir"}</strong></div><div><Users size={19}/><span>Capacité</span><strong>{d?.capacity?`${d.capacity} personnes`:"À confirmer"}</strong></div></div>{d?.address&&<p className="practical-address"><MapPin size={17}/><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.address)}`} target="_blank" rel="noopener noreferrer">{d.address}<ArrowUpRight size={15}/></a></p>}{d?.travel&&<p className="practical-travel">{d.travel}</p>}{d?.pricing&&<div className="practical-note"><h4>Tarifs & conditions</h4><p>{d.pricing}</p></div>}{d?.notes&&<div className="practical-note"><h4>À savoir</h4><p>{d.notes}</p></div>}{!d&&<button className="button secondary full" onClick={()=>setEditing(true)}><Pencil size={16}/>Compléter les infos pratiques</button>}{d&&<p className="fine-print">Infos partagées par {d.updatedBy} · à confirmer auprès du lieu.</p>}</>}{saved&&<p className="inline-success" role="status"><Check size={15}/>Infos pratiques enregistrées.</p>}</section>;
}
