"use client";
import { Trophy, LockKeyhole, Check, ArrowUpRight } from "lucide-react";
import { CrewAvatar } from "@/components/crew-avatar";
import { EmojiImage } from "@/components/emoji-image";
import { CREW, type ClubState } from "@/lib/club";
import { voterKey } from "@/lib/identity";
import { REWARDS } from "@/lib/rewards";
export function CrewLeaderboard({state,person,onRewards}:{state:ClubState;person:string;onRewards:()=>void}){
  const ranks=CREW.map((name,index)=>({name,index,key:voterKey(name),votes:state.votes.filter(v=>voterKey(v.author)===voterKey(name)).length})).sort((a,b)=>b.votes-a.votes||a.index-b.index);
  const peak=state.progress.find(p=>p.authorKey===voterKey(person))?.peakVotes??0,next=REWARDS.find(r=>r.votes>peak);
  return <section className="crew-leaderboard"><div className="section-heading"><div><span className="eyebrow"><Trophy size={17}/>LA COURSE DES LÉGENDES</span><h2>Chaque voix compte.</h2></div><span className="date-pill">11 cavaliers · un seul crew</span></div><div className="leaderboard-podium">{ranks.slice(0,3).map((member,i)=><article key={member.key} className={"podium-place place-"+(i+1)}><span className="podium-rank">#{i+1}</span><CrewAvatar name={member.name}/><strong>{member.name}</strong><span><b>{member.votes}</b> vote{member.votes!==1?"s":""}</span>{i===0&&<Trophy className="podium-trophy" size={28}/>}</article>)}</div><div className="leaderboard-rows">{ranks.slice(3).map((member,i)=><div key={member.key} className={member.key===voterKey(person)?"is-me":""}><span className="leaderboard-rank">{i+4}</span><CrewAvatar name={member.name} small/><strong>{member.name}</strong><span><b>{member.votes}</b> votes</span></div>)}</div><div className="rewards-track"><div className="rewards-heading"><div><strong>{person?"Les trophées de "+person:"Ton prochain look se mérite."}</strong><p>{next?next.votes-state.votes.filter(v=>voterKey(v.author)===voterKey(person)).length+" vote(s) pour débloquer « "+next.title+" ».":"Tous les paliers sont débloqués. Légendaire."}</p></div><button className="button secondary" onClick={onRewards}>Mes récompenses<ArrowUpRight size={16}/></button></div><div className="reward-milestones">{REWARDS.map(reward=><div key={reward.votes} className={peak>=reward.votes?"unlocked":"locked"}><EmojiImage emoji={reward.items[0].emoji}/><strong>{reward.votes} votes</strong><span>{reward.title}</span>{peak>=reward.votes?<Check size={15}/>:<LockKeyhole size={15}/>}</div>)}</div></div><p className="fine-print">Films, activités, créneaux et idées : une cible compte une fois, quel que soit ton choix. Les accessoires débloqués restent acquis.</p></section>;
}
