"use client";
import { COOKIE_AVATARS, formatCookies } from "@/lib/cookie-game";
import { createContext, useContext, useEffect, useRef, useState, type CSSProperties, type FormEvent } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, LoaderCircle, RotateCcw, Sparkles } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import type { Profile } from "@/lib/club";
import { requiredVotes } from "@/lib/rewards";
import { voterKey } from "@/lib/identity";
import { AVATAR_NAMES, DEFAULT_LOOK, EYEWEAR, HATS, EXTRAS, extraAccessory, avatarIndex, avatarSheet, lookFor, reactAvatar, type Look } from "@/lib/appearance";
import type { SocialProps } from "@/components/crew-social";
import { toast } from "sonner";
import { EmojiImage } from "@/components/emoji-image";
import { AccessoryTransformControls } from "@/components/accessory-transform-controls";
import { AvatarAccessories, accessoryLabel, visibleAccessories, type AccessoryEditing } from "@/components/avatar-accessories";
import { accessoryLayout, clampPosition, type AccessoryKind, type AccessoryPosition } from "@/lib/avatar-positions";
export { AVATAR_NAMES, avatarIndex } from "@/lib/appearance";
export const AvatarContext=createContext<Profile[]>([]);

export function CrewAvatar({name,small=false,index,className="",look,imageUrl,editing}:{name:string;small?:boolean;index?:number;className?:string;look?:Look;imageUrl?:string;editing?:AccessoryEditing}){
  const profiles=useContext(AvatarContext),profile=profiles.find(p=>p.authorKey===voterKey(name));
  const i=index??avatarIndex(name,profiles),sheet=avatarSheet(i),outfit=look??(index===undefined?lookFor(name,profiles):{...DEFAULT_LOOK,animated:0});
  const custom=imageUrl??(index===undefined?profile?.imageUrl:"");
  const [failed,setFailed]=useState(false),[reaction,setReaction]=useState("");const expiry=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  useEffect(()=>setFailed(false),[custom]);
  useEffect(()=>{if(!outfit.animated||index!==undefined)return;const react=(event:Event)=>{const d=(event as CustomEvent).detail;if(d?.name!==voterKey(name)||matchMedia("(prefers-reduced-motion: reduce)").matches)return;clearTimeout(expiry.current);setReaction("");requestAnimationFrame(()=>setReaction(d.kind));expiry.current=setTimeout(()=>setReaction(""),1200);};window.addEventListener("jacuzzi:avatar",react);return()=>{clearTimeout(expiry.current);window.removeEventListener("jacuzzi:avatar",react);};},[name,outfit.animated,index]);
  return <span title={name} className={`avatar avatar-shell ${small?"small":""} ${outfit.animated&&!editing?"animated-avatar":""} ${editing?"avatar-being-edited":""} ${reaction?`avatar-react-${reaction}`:""} ${className}`}>
    <span className={`avatar-face kawaii-avatar ${i>=12?"extra-avatar":""}`} style={{"--avatar-image":`url("${sheet.url}")`,"--avatar-size":`${100/sheet.frame.width}% ${100/sheet.frame.height}%`,backgroundPosition:`${sheet.frame.x/(1-sheet.frame.width)*100}% ${sheet.frame.y/(1-sheet.frame.height)*100}%`} as CSSProperties}>{custom&&!failed&&<img src={custom} alt="" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>}</span>
    <AvatarAccessories look={outfit} editing={editing}/>
    {voterKey(name)==="alex"&&<span className="avatar-dev-badge" aria-label="Développeur du QG">DEV</span>}
    {reaction&&<span className="avatar-reaction-symbol" aria-hidden="true"><EmojiImage emoji={reaction==="yes"?"💚":reaction==="no"?"💭":"✨"}/></span>}
  </span>;
}

export function AvatarEditor({open,onClose,...s}:SocialProps&{open:boolean;onClose:()=>void}){
  const [selected,setSelected]=useState(0),[url,setUrl]=useState(""),[outfit,setOutfit]=useState<Look>(DEFAULT_LOOK),[busy,setBusy]=useState(false),[error,setError]=useState("");const guard=useRef(false);
  const [active,setActive]=useState<AccessoryKind|null>(null);
  const cookieTotal=s.state.cookieProgress.find(p=>p.authorKey===voterKey(s.person))?.lifetime??0;
  const peak=s.state.progress.find(p=>p.authorKey===voterKey(s.person))?.peakVotes??0;
  const visible=visibleAccessories(outfit),activeKind=active&&visible.includes(active)?active:visible[0]??null;
  const changePosition=(kind:AccessoryKind,position:AccessoryPosition)=>setOutfit(o=>({...o,positions:{...o.positions,[kind]:{...o.positions?.[kind],...position}}}));
  const nudge=(x:number,y:number)=>{if(!activeKind)return;const pos=accessoryLayout(activeKind,outfit.hat,outfit.positions,extraAccessory(outfit));changePosition(activeKind,{x:clampPosition(pos.x+x),y:clampPosition(pos.y+y)});};
  const resetPosition=()=>{if(!activeKind)return;const defaults=accessoryLayout(activeKind,outfit.hat,{},extraAccessory(outfit));changePosition(activeKind,{x:defaults.x,y:defaults.y});};
  useEffect(()=>{if(open){const p=s.state.profiles.find(p=>p.authorKey===voterKey(s.person));setSelected(avatarIndex(s.person,s.state.profiles));setOutfit(lookFor(s.person,s.state.profiles));setUrl(p?.imageUrl||"");setError("");setActive(null);}},[open,s.person]);
  const submit=(e:FormEvent)=>{e.preventDefault();if(guard.current)return;s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);setError("");try{await s.save({action:"profile",transformVersion:2,author,avatar:selected,imageUrl:url.trim(),...outfit,accessory:extraAccessory(outfit),floatie:extraAccessory(outfit)==="floatie",animated:!!outfit.animated});onClose();reactAvatar(author);toast.success(`Nouveau look enregistré pour ${author} !`);}catch(e){setError((e as Error).message);}finally{setBusy(false);guard.current=false;}});};
  return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="club-dialog avatar-dialog"><span className="dialog-kicker"><Sparkles size={18}/>LE VESTIAIRE DU CREW</span><DialogTitle>Un look de légende.</DialogTitle><DialogDescription>60 compagnons + {COOKIE_AVATARS.length} exclusifs de l’Arcade, tes accessoires et une bonne dose de personnalité. Ton look est partagé avec tout le crew.</DialogDescription>
    <form onSubmit={submit}><div className="avatar-position-editor"><div className="avatar-position-title"><strong>{s.person||"Ton prénom"}</strong><span>{url?"Ton image":AVATAR_NAMES[selected]}</span></div><div className="avatar-position-stage"><CrewAvatar name={s.person||"Ton avatar"} index={selected} look={outfit} imageUrl={url} className="position-preview-avatar" editing={{active:activeKind,disabled:busy,onSelect:setActive,onChange:changePosition}}/></div><p id="avatar-position-help">{visible.length?"Touche un accessoire pour afficher ses poignées. Glisse le centre pour le déplacer.":"Choisis un accessoire ci-dessous pour le placer sur ton avatar."}</p>{activeKind&&<fieldset disabled={busy} className="position-controls"><RadioGroup value={activeKind} onValueChange={v=>setActive(v as AccessoryKind)} className="position-selection" aria-label="Accessoire à déplacer">{visible.map(kind=><label key={kind} className={kind===activeKind?"chosen":""}><RadioGroupItem value={kind} aria-label={accessoryLabel(kind,outfit)}/><span>{accessoryLabel(kind,outfit)}</span></label>)}</RadioGroup><AccessoryTransformControls label={accessoryLabel(activeKind,outfit)} layout={accessoryLayout(activeKind,outfit.hat,outfit.positions,extraAccessory(outfit))} disabled={busy} onChange={position=>changePosition(activeKind,position)}/><div className="position-actions"><button type="button" aria-label="Déplacer à gauche" onClick={()=>nudge(-2,0)}><ArrowLeft size={18}/></button><button type="button" aria-label="Déplacer vers le haut" onClick={()=>nudge(0,-2)}><ArrowUp size={18}/></button><button type="button" aria-label="Déplacer vers le bas" onClick={()=>nudge(0,2)}><ArrowDown size={18}/></button><button type="button" aria-label="Déplacer à droite" onClick={()=>nudge(2,0)}><ArrowRight size={18}/></button><button type="button" className="position-reset" onClick={resetPosition}><RotateCcw size={16}/>Recentrer</button></div><p className="position-readout" aria-live="polite">{accessoryLabel(activeKind,outfit)} · Horizontal {Math.round(accessoryLayout(activeKind,outfit.hat,outfit.positions,extraAccessory(outfit)).x)} % · Vertical {Math.round(accessoryLayout(activeKind,outfit.hat,outfit.positions,extraAccessory(outfit)).y)} %</p></fieldset>}</div>
      <fieldset disabled={busy} className="outfit-fields"><legend>La touche finale</legend>{[{key:"hat",label:"Sur la tête",items:HATS},{key:"eyewear",label:"Les lunettes",items:EYEWEAR},{key:"accessory",label:"Les accessoires",items:EXTRAS}].map(category=><div className="outfit-category" key={category.key}><span>{category.label}</span><RadioGroup value={(category.key==="accessory"?extraAccessory(outfit):outfit[category.key as "hat"|"eyewear"])} onValueChange={value=>{setOutfit(o=>({...o,[category.key]:value,...(category.key==="accessory"?{floatie:Number(value==="floatie"),positions:{...o.positions,floatie:undefined}}:{})}));setActive(category.key==="accessory"?"floatie":category.key as AccessoryKind);}} className="outfit-options" aria-label={category.label}>{category.items.map(item=><label key={item.id} className={(category.key==="accessory"?extraAccessory(outfit):outfit[category.key as "hat"|"eyewear"])===item.id?"chosen":""}><RadioGroupItem value={item.id} aria-label={item.label} disabled={requiredVotes(category.key,item.id)>peak}/><span aria-hidden="true">{item.emoji?<EmojiImage emoji={item.emoji}/>:"✕"}</span><small>{item.label}{requiredVotes(category.key,item.id)>peak&&<span className="outfit-unlock-label">{requiredVotes(category.key,item.id)} votes pour débloquer</span>}</small></label>)}</RadioGroup></div>)}
      <div className="outfit-switch"><label htmlFor="avatar-motion">Danses et réactions animées</label><Switch id="avatar-motion" checked={!!outfit.animated} onCheckedChange={v=>setOutfit(o=>({...o,animated:Number(v)}))}/></div></fieldset>
      <details className="avatar-gallery" open><summary>Choisir son compagnon <span>{AVATAR_NAMES.length} avatars</span></summary><div className="avatar-picker" role="group" aria-label="Choisir un avatar kawaii">{AVATAR_NAMES.map((name,i)=><button key={name} disabled={busy||(COOKIE_AVATARS.find(a=>a.index===i)?.threshold??0)>cookieTotal} type="button" aria-pressed={selected===i&&!url} aria-label={name} className={selected===i&&!url?"selected":""} onClick={()=>{setSelected(i);setUrl("");}}><CrewAvatar name={name} index={i}/><span>{name}</span>{i>=60&&<small className="cookie-avatar-lock">Arcade · {formatCookies(COOKIE_AVATARS[i-60].threshold)} cookies</small>}{selected===i&&!url&&<Check size={16}/>}</button>)}</div></details>
      <label className="custom-avatar-label">Ou le lien de ton image<input disabled={busy} type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…/mon-avatar.png" maxLength={1000}/></label><p className="fine-print">Image publique en HTTPS. Les accessoires s’appliquent aussi à ton image. Les animations respectent les préférences de ton appareil.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>}Enregistrer mon look</button>
    </form></DialogContent></Dialog>;
}
