"use client";
import { useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowUpRight, Lightbulb, LoaderCircle, Send, Trash2 } from "lucide-react";
import { CrewAvatar } from "@/components/crew-avatar";
import { Discussion } from "@/components/crew-social";
import type { SocialProps } from "@/components/crew-social";
import { dateLabel } from "@/lib/club";
import { toast } from "sonner";

export function FeatureIdeas({loaded,error,onRetry,renderVotes,...s}:SocialProps&{loaded:boolean;error:string;onRetry:()=>void;renderVotes:(id:string)=>ReactNode}){
  const [title,setTitle]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[formError,setFormError]=useState("");
  const guard=useRef(false),attempt=useRef<{signature:string;id:string}|null>(null);
  const submit=(event:FormEvent)=>{event.preventDefault();if(guard.current||!title.trim())return;const submitted={title:title.trim(),body:body.trim()};s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);setFormError("");const signature=JSON.stringify({...submitted,author});if(attempt.current?.signature!==signature)attempt.current={signature,id:crypto.randomUUID()};try{await s.save({action:"featureIdea",id:attempt.current.id,author,...submitted});setTitle("");setBody("");attempt.current=null;toast.success("Ton idée rejoint la boîte du crew !");}catch(e){setFormError((e as Error).message);}finally{guard.current=false;setBusy(false);}});};
  const ideas=[...s.state.featureIdeas].sort((a,b)=>b.created.localeCompare(a.created));
  return <section className="feature-ideas-page" aria-labelledby="feature-ideas-heading">
    <div className="feature-ideas-heading"><div><span className="eyebrow"><Lightbulb size={17}/> LE SITE GRANDIT AVEC LE CREW</span><h1 id="feature-ideas-heading">La boîte <em>à idées.</em></h1><p>Une fonctionnalité qui manque ? Une amélioration à imaginer ? Propose-la ici.</p></div><Lightbulb className="ideas-bulb" aria-hidden="true"/></div>
    <div className="feature-ideas-layout"><form className="feature-idea-form" onSubmit={submit}><h2>La prochaine bonne idée <ArrowUpRight size={22}/></h2><label htmlFor="feature-title">Ton idée<input id="feature-title" required maxLength={120} disabled={busy} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Une liste de courses commune"/></label><label htmlFor="feature-body">Les détails <span>facultatif</span><textarea id="feature-body" rows={4} maxLength={1500} disabled={busy} value={body} onChange={e=>setBody(e.target.value)} placeholder="À quoi ça servirait ? Comment tu l’imagines ?"/></label><div className="feature-idea-author">{s.person?<><CrewAvatar name={s.person} small/><span>Proposée par <strong>{s.person}</strong></span></>:<span>Choisis ton prénom au moment de proposer.</span>}</div>{formError&&<p className="form-error" role="alert">{formError}</p>}<button className="button primary full" disabled={busy||!title.trim()}>{busy?<LoaderCircle size={18} className="spin"/>:<Send size={18}/>} {busy?"Envoi de l’idée…":"Proposer cette idée"}</button></form>
      <div className="feature-idea-board"><div className="feature-board-title"><h2>Les idées du crew</h2><span>{ideas.length}</span></div>{error&&<div className="error-banner" role="alert">{error}<button onClick={onRetry}>Réessayer</button></div>}{!loaded?<p className="loading-line"><LoaderCircle className="spin" size={18}/>On ouvre la boîte…</p>:!ideas.length?<div className="feature-ideas-empty"><Lightbulb size={35}/><h3>À toi d’allumer la première étincelle.</h3><p>Les suggestions pour améliorer la plateforme apparaîtront ici.</p></div>:<div className="feature-idea-list">{ideas.map((idea,i)=><article className="feature-idea-card" key={idea.id}><span className="idea-card-number">IDÉE {String(ideas.length-i).padStart(2,"0")}</span><h3>{idea.title}</h3>{idea.body&&<p>{idea.body}</p>}<div className="feature-idea-meta"><CrewAvatar name={idea.author} small/><strong>{idea.author}</strong><time dateTime={idea.created}>{dateLabel(idea.created,{day:"numeric",month:"short"})}</time></div><div className="idea-votes">{renderVotes(idea.id)}</div><details className="idea-discussion"><summary>Commentaires · {s.state.ideaComments.filter(c=>c.ideaId===idea.id).length}</summary><Discussion {...s} proposal={idea} idea/></details><DeleteIdea idea={idea} {...s}/></article>)}</div>}</div>
    </div>
  </section>;
}

function DeleteIdea({idea,...s}:SocialProps&{idea:{id:string;title:string}}){const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const guard=useRef(false);const remove=()=>s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);setError("");try{await s.save({action:"deleteFeatureIdea",id:idea.id,author});toast.success("L’idée a été supprimée.");}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}});return <div className="idea-delete">{confirm?<div className="delete-movie-confirm" role="group" aria-label="Confirmer la suppression de l’idée"><strong>Supprimer « {idea.title} » ?</strong><p>Cette idée, ses votes et ses commentaires seront retirés pour tout le crew.</p><div><button className="button secondary" disabled={busy} onClick={()=>{setConfirm(false);setError("");}}>Annuler</button><button className="button delete-movie-action" disabled={busy} onClick={remove}>{busy?<LoaderCircle size={16} className="spin"/>:<Trash2 size={16}/>}Confirmer la suppression</button></div>{error&&<p className="form-error" role="alert">{error}</p>}</div>:<button className="delete-movie-trigger" aria-label={`Supprimer l’idée ${idea.title}`} onClick={()=>setConfirm(true)}><Trash2 size={15}/>Supprimer l’idée</button>}</div>;}
