"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, CalendarDays, Check, Download, LoaderCircle, MapPin, Share2, Sparkles, Ticket, Users } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { dateLabel, timeLabel, type ClubState, type Proposal, type SelectedPlan } from "@/lib/club";
import type { SocialProps } from "@/components/crew-social";
import { ActivityEmojiBadge } from "@/components/activity-emoji";
import { emojiAsset } from "@/lib/emoji-assets";
import { activityEmoji } from "@/lib/activity-emoji";
import { celebrate } from "@/components/club-effects";

function dayOf(iso:string){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Paris"}).format(new Date(iso));}
function clockOf(iso:string){return timeLabel(iso).replace(" h ",":");}
export function SelectPlan({proposal,editing,onClose,onReveal,...s}:SocialProps&{proposal:Proposal|null;editing:SelectedPlan|null;onClose:()=>void;onReveal:(id:string)=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const attempt=useRef<{key:string;id:string}|null>(null);const guard=useRef(false);
  useEffect(()=>{setError("");attempt.current=null;},[proposal?.id,editing?.id,editing?.updated]);
  const submit=(e:FormEvent)=>{e.preventDefault();if(!proposal||guard.current)return;const f=new FormData(e.currentTarget as HTMLFormElement);const start=`${f.get("day")}T${f.get("start")}:00+02:00`,end=`${f.get("day")}T${f.get("end")}:00+02:00`;if(end<=start){setError("La fin doit être après le début.");return;}s.identify(async author=>{if(guard.current)return;guard.current=true;setBusy(true);setError("");const key=JSON.stringify({proposal:proposal.id,start,end,author});if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};try{await s.save(editing?{action:"editPlan",planId:editing.id,author,start,end,expectedUpdated:editing.updated??null}:{action:"select",id:attempt.current.id,proposalId:proposal.id,author,start,end});const id=editing?.id||attempt.current.id;attempt.current=null;onClose();onReveal(id);}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}});};
  return <Dialog open={!!proposal} onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="club-dialog"><span className="dialog-kicker"><Ticket size={19}/>ON A NOTRE PLAN</span><DialogTitle>{editing?"On change de créneau ?":"Ça mérite une annonce."}</DialogTitle><DialogDescription>{editing?`Modifie le rendez-vous « ${proposal?.title} ». Les présences confirmées sont conservées.`:`Retiens « ${proposal?.title} » et son créneau. Chacun pourra ensuite confirmer sa présence.`}</DialogDescription>{proposal&&<form className="activity-form" onSubmit={submit} key={editing?.id||proposal.id}><label>Le jour du rendez-vous<input disabled={busy} name="day" type="date" defaultValue={editing?dayOf(editing.start):proposal.start?dayOf(proposal.start):""} min="2026-09-20" max="2026-09-27" required/></label><div className="field-pair"><label>Début du rendez-vous<input disabled={busy} name="start" type="time" defaultValue={editing?clockOf(editing.start):proposal.start?clockOf(proposal.start):"21:00"} required/></label><label>Fin du rendez-vous<input disabled={busy} name="end" type="time" defaultValue={editing?clockOf(editing.end):proposal.end?clockOf(proposal.end):"23:00"} required/></label></div>{proposal.kind==="activity"&&s.state.slots.filter(slot=>slot.proposalId===proposal.id).length>0&&<p className="fine-print">Les horaires ci-dessus sont modifiables pour reprendre un créneau suggéré dans la fiche.</p>}<p className="fine-print">Un plan retenu n’est pas une réservation auprès du lieu. Heure de Paris.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy?"Enregistrement…":editing?"Enregistrer le nouveau créneau":"Révéler le plan au crew"}</button></form>}</DialogContent></Dialog>;
}

export function SelectedPlans({state,onReveal}:{state:ClubState;onReveal:(id:string)=>void}){
  if(!state.plans.length)return <section className="plans-empty"><Ticket size={25}/><div><strong>Le prochain grand moment attend son affiche.</strong><p>Ouvre un film ou une activité, puis « Retenir ce plan ».</p></div></section>;
  return <section className="selected-plans"><div className="section-heading"><div><span className="eyebrow muted">ON A RENDEZ-VOUS</span><h2>Les plans retenus.</h2></div><span className="date-pill"><Ticket size={16}/>{state.plans.length} rendez-vous</span></div><div className="plan-tickets">{state.plans.map(plan=>{const p=state.proposals.find(p=>p.id===plan.proposalId);if(!p)return null;const n=state.participants.filter(a=>a.planId===plan.id&&a.attending).length;return <button key={plan.id} className="plan-ticket" onClick={()=>onReveal(plan.id)}><span className="ticket-date"><b>{dateLabel(plan.start,{day:"numeric"})}</b>{dateLabel(plan.start,{month:"short"})}</span><span className="ticket-copy"><small>{p.kind==="movie"?"CINÉMA":"SORTIE"} · {timeLabel(plan.start)}</small><strong>{p.kind==="activity"&&<ActivityEmojiBadge proposal={p} className="ticket-emoji"/>}{p.title}</strong><span>{n} présence{n!==1?"s":""} confirmée{n!==1?"s":""}</span></span><ArrowUpRight size={24}/></button>;})}</div></section>;
}

export function PlanReveal({id,onClose,onEdit,...s}:SocialProps&{id:string|null;onClose:()=>void;onEdit:(plan:SelectedPlan)=>void}){
  const plan=s.state.plans.find(p=>p.id===id);const proposal=s.state.proposals.find(p=>p.id===plan?.proposalId);const details=s.state.activityDetails.find(d=>d.proposalId===proposal?.id);const [count,setCount]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [downloading,setDownloading]=useState(false);const guard=useRef(false);
  useEffect(()=>{if(!id)return;setMessage("");setError("");if(matchMedia("(prefers-reduced-motion: reduce)").matches){setCount(0);return;}setCount(3);const interval=setInterval(()=>setCount(n=>Math.max(0,n-1)),650);const timeout=setTimeout(()=>{clearInterval(interval);celebrate();},2050);return()=>{clearInterval(interval);clearTimeout(timeout);};},[id]);
  const participants=s.state.participants.filter(p=>p.planId===id&&p.attending);const attending=participants.some(p=>p.authorKey===s.person.trim().normalize("NFKC").toLocaleLowerCase("fr"));
  const attend=()=>s.identify(async author=>{if(!plan||guard.current)return;guard.current=true;setBusy(true);setError("");try{const was=s.state.participants.some(p=>p.planId===id&&p.authorKey===author.trim().normalize("NFKC").toLocaleLowerCase("fr")&&p.attending);await s.save({action:"attend",planId:plan.id,author,attending:!was});setMessage(was?`${author} s’est retiré de la liste.`:`${author}, ta présence est confirmée !`);if(!was)celebrate("yes");}catch(e){setError((e as Error).message);}finally{guard.current=false;setBusy(false);}});
  const link=()=>`${location.origin}/?plan=${encodeURIComponent(id||"")}`;
  const share=async()=>{setError("");try{if(navigator.share)await navigator.share({title:proposal?.title,text:"Le prochain grand moment des 34 Chevaux du Jacuzzi",url:link()});else{await navigator.clipboard.writeText(link());setMessage("Lien de l’affiche copié !");}}catch(e){if((e as Error).name!=="AbortError")setError("Le partage n’a pas abouti. Copie le lien ci-dessous.");}};
  const download=async()=>{if(!proposal||!plan)return;setDownloading(true);setError("");try{await downloadPoster(proposal,plan,participants.map(p=>p.author),details?.address|| (proposal.kind==="movie"?"Cinéma à l’Airbnb":"Lieu à confirmer"),link());setMessage("Affiche PNG téléchargée !");}catch{setError("Impossible de générer l’affiche. Tu peux partager le lien.");}finally{setDownloading(false);}};
  return <Dialog open={!!id} onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="club-dialog reveal-dialog">{count>0&&<div className="reveal-countdown" aria-hidden="true"><span key={count}>{count}</span><small>LE CREW A RENDEZ-VOUS</small></div>}{plan&&proposal?<><div className={`reveal-poster ${count?"waiting":""}`}><img className="reveal-image" src={proposal.movie?.backdrop||proposal.movie?.poster||"/jacuzzi.webp"} alt=""/><div className="reveal-gradient"/><div className="reveal-content"><span className="reveal-stamp">LES 34 CHEVAUX<br/>DU JACUZZI</span><span className="eyebrow"><Sparkles size={16}/>C’EST LE PLAN.</span>{proposal.kind==="activity"&&<ActivityEmojiBadge proposal={proposal} className="reveal-emoji"/>}<DialogTitle>{proposal.title}</DialogTitle><DialogDescription><CalendarDays size={18}/>{dateLabel(plan.start)} · {timeLabel(plan.start)} — {timeLabel(plan.end)}</DialogDescription><p><MapPin size={17}/>{details?.address||(proposal.kind==="movie"?"Cinéma à l’Airbnb":"Lieu indiqué sur la fiche")}</p><span className="reveal-author">Retenu par {plan.selectedBy}</span></div></div><div className="reveal-bottom"><button className="button secondary full edit-plan-button" onClick={()=>onEdit(plan)}><CalendarDays size={16}/>Modifier ce rendez-vous</button>{plan.updatedBy&&<p className="fine-print">Créneau modifié par {plan.updatedBy}.</p>}<div className="social-heading"><h3><Users size={20}/>Qui vient ?</h3><span>{participants.length} confirmé{participants.length!==1?"s":""}</span></div><div className="participant-chips">{participants.length?participants.map(p=><span key={p.authorKey}><Check size={14}/>{p.author}</span>):<p>Première place au premier motivé.</p>}</div><button className={`button ${attending?"secondary":"primary"} full`} disabled={busy} onClick={attend}>{busy?<LoaderCircle size={17} className="spin"/>:<Ticket size={17}/>} {attending?"Je me retire":"Je participe"}</button><p className="fine-print">Une présence par prénom déclaré, indépendamment des votes.</p><div className="reveal-actions"><button className="button secondary" onClick={()=>void share()}><Share2 size={16}/>Partager le lien</button><button className="button secondary" disabled={downloading} onClick={()=>void download()}>{downloading?<LoaderCircle className="spin" size={16}/>:<Download size={16}/>}Affiche PNG</button></div><label className="share-link">Lien de cette affiche<input readOnly value={typeof location!=="undefined"?link():""} onFocus={e=>e.currentTarget.select()}/></label>{message&&<p className="inline-success" role="status">{message}</p>}{error&&<p className="form-error" role="alert">{error}</p>}</div></>:<><DialogTitle>L’affiche se prépare.</DialogTitle><DialogDescription>Ce plan est en cours de chargement. S’il n’apparaît pas, vérifie le lien ou réessaie depuis le QG.</DialogDescription></>}</DialogContent></Dialog>;
}

async function downloadPoster(p:Proposal,plan:SelectedPlan,names:string[],address:string,url:string){
  const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1500;const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");
  const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src="/jacuzzi.webp";});
  ctx.fillStyle="#080e20";ctx.fillRect(0,0,1080,1500);const scale=Math.max(1080/image.width,800/image.height);ctx.drawImage(image,(1080-image.width*scale)/2,0,image.width*scale,image.height*scale);
  const gradient=ctx.createLinearGradient(0,180,0,850);gradient.addColorStop(0,"rgba(8,14,32,0)");gradient.addColorStop(1,"#080e20");ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,900);
  ctx.fillStyle="#dfff00";ctx.font="bold 25px Arial";ctx.fillText("LES 34 CHEVAUX DU JACUZZI",70,85);ctx.fillText("C’EST LE PLAN.",70,550);
  if(p.kind==="activity"){const glyph=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=emojiAsset(activityEmoji(p));});ctx.drawImage(glyph,70,335,120,120);}
  let y=625;const wrap=(text:string,font:string,width:number,line:number,maxLines=20)=>{ctx.font=font;let row="",lines=0;for(const word of text.split(/\s+/)){if(ctx.measureText(`${row} ${word}`).width>width&&row){ctx.fillText(row,70,y);y+=line;lines++;row="";if(lines>=maxLines){ctx.fillText("…",70,y);return;}}row+=(row?" ":"")+word;}ctx.fillText(row,70,y);y+=line;};
  ctx.fillStyle="#fff";wrap(p.title,"bold 66px Arial",930,76,5);y+=25;ctx.fillStyle="#dfff00";wrap(dateLabel(plan.start),"bold 36px Arial",930,46,2);wrap(`${timeLabel(plan.start)} — ${timeLabel(plan.end)} · Heure de Paris`,"bold 30px Arial",930,42,2);ctx.fillStyle="#c0cbdf";wrap(address,"28px Arial",930,36,3);y+=25;ctx.fillStyle="#fff";wrap(names.length?`AVEC ${names.join(" · ")}`:"CONFIRME TA PRÉSENCE SUR LE SITE","bold 25px Arial",930,35,3);ctx.fillStyle="#6f85af";ctx.font="20px Arial";ctx.fillText("Retrouve les infos et les présences à jour sur l’affiche en ligne.",70,1410);ctx.font="17px Arial";ctx.fillText(url,70,1450,940);
  const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(),"image/png"));const href=URL.createObjectURL(blob);const a=document.createElement("a");a.href=href;a.download=`jacuzzi-${p.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,60)}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(href),10000);
}
