"use client";
import { ArrowUpRight, Check, LockKeyhole, Play, Trophy } from "lucide-react";
import { REWARDS } from "@/lib/rewards";
import { EmojiImage } from "@/components/emoji-image";
import { CrewAvatar } from "@/components/crew-avatar";
export function RewardsPage({person,peak,currentVotes,onReplay,onWardrobe,onIdentify}:{person:string;peak:number;currentVotes:number;onReplay:(reward:typeof REWARDS[number])=>void;onWardrobe:()=>void;onIdentify:()=>void}){
  const count=REWARDS.filter(r=>r.votes<=peak).length;
  return <section className="rewards-page"><div className="rewards-hero"><span className="eyebrow"><Trophy size={18}/>LE PANTHÉON DU CREW</span><h1>Chaque palier.<br/><em>Un nouveau toi.</em></h1><p>Ta collection de récompenses. Tes moments de gloire. À revivre autant de fois que tu veux.</p><div className="rewards-profile">{person?<><CrewAvatar name={person}/><div><strong>{person}</strong><span>{count} / {REWARDS.length} succès débloqués · record de {peak} votes</span></div><button className="button primary" onClick={onWardrobe}>Mon vestiaire<ArrowUpRight size={17}/></button></>:<button className="button primary" onClick={onIdentify}>Choisir mon prénom<ArrowUpRight size={17}/></button>}</div></div><div className="rewards-gallery">{REWARDS.map((reward,index)=>{const earned=!!person&&peak>=reward.votes;return <article key={reward.votes} className={"reward-card "+(earned?"earned":"locked")}><span className="reward-number">0{index+1}</span><span className="reward-status">{earned?<><Check size={14}/>DÉBLOQUÉ</>:<><LockKeyhole size={14}/>{reward.votes} VOTES</>}</span><div className="reward-art">{reward.items.map(item=><EmojiImage key={item.id} emoji={item.emoji}/>)}</div><div className="reward-card-copy"><span className="eyebrow">PALIER {reward.votes} VOTES</span><h2>{reward.title}</h2><p>{reward.items.map(item=>item.label).join(" + ")}</p>{earned?<button className="button secondary full" onClick={()=>onReplay(reward)}><Play size={16}/>Rejouer le déblocage</button>:<div className="reward-locked-note">{person?Math.max(0,reward.votes-currentVotes)+" vote(s) avant le déblocage":"Choisis ton prénom pour voir ta progression."}</div>}</div></article>;})}</div><p className="fine-print">Les votes déjà exprimés comptent aussi. Tes accessoires restent acquis si une proposition est supprimée. Un vote par proposition : changer d’avis ne multiplie pas les points.</p></section>;
}
