"use client";
import { useEffect,useRef,useState } from "react";
import { ArrowUpRight,Clapperboard,House,RotateCcw,Sun,Waves } from "lucide-react";
import type { VillaZone } from "@/lib/villa-three";
const ROOMS=[{id:"villa",label:"Vue d’ensemble",Icon:House},{id:"cinema",label:"Salon cinéma",Icon:Clapperboard},{id:"terrace",label:"La terrasse",Icon:Sun},{id:"jacuzzi",label:"Le jacuzzi",Icon:Waves}] as const;
export function VillaScene({onCinema,onProgramme,onWardrobe}:{onCinema:()=>void;onProgramme:()=>void;onWardrobe:()=>void}){
  const host=useRef<HTMLDivElement>(null),scene=useRef<{setZone:(z:VillaZone)=>void;dispose:()=>void}|null>(null);const [zone,setZone]=useState<VillaZone>("villa"),[status,setStatus]=useState("loading");
  useEffect(()=>{let stopped=false;void import("@/lib/villa-three").then(({buildVilla})=>{if(stopped||!host.current)return;scene.current=buildVilla(host.current,setZone,ready=>setStatus(ready?"ready":"fallback"));setStatus("ready");}).catch(()=>{if(!stopped)setStatus("fallback");});return()=>{stopped=true;scene.current?.dispose();scene.current=null;};},[]);
  useEffect(()=>scene.current?.setZone(zone),[zone,status]);
  const room=zone==="cinema"?{eyebrow:"LE SALON",title:"La meilleure place, c’est ensemble.",label:"Entrer dans la salle",action:onCinema}:zone==="terrace"?{eyebrow:"LA TERRASSE",title:"On prépare la prochaine sortie ?",label:"Ouvrir le programme",action:onProgramme}:zone==="jacuzzi"?{eyebrow:"LE BAIN DES LÉGENDES",title:"La bouée est un accessoire essentiel.",label:"Passer au vestiaire",action:onWardrobe}:{eyebrow:"BIENVENUE À LA MAISON",title:"Trois espaces. Onze bonnes raisons de rester.",label:"Choisir notre film",action:onCinema};
  return <section className="villa-experience" aria-label="Explorer la villa du crew"><div className="villa-heading"><div><span className="eyebrow">LES 34 CHEVAUX · LE QG</span><h1>LA VILLA <em>DU CREW.</em></h1></div><p>Le salon pour les films.<br/>La terrasse pour les sorties.<br/>Le jacuzzi pour le style.</p></div><div className={`villa-stage scene-${status}`} data-scene-status={status}><img src="/villa-night.webp" alt="Maquette nocturne d’une villa avec salon cinéma, terrasse et jacuzzi" className="villa-fallback"/><div ref={host} className="villa-canvas"/><span className="villa-coordinate">MAGALAS · SEPTEMBRE 2026</span><button className="villa-reset" onClick={()=>{setZone("villa");scene.current?.setZone("villa");}} aria-label="Revenir à la vue d’ensemble"><RotateCcw size={18}/></button><div className="villa-room-card" aria-live="polite"><span className="eyebrow">{room.eyebrow}</span><h2>{room.title}</h2><button className="button primary" onClick={room.action}>{room.label}<ArrowUpRight size={18}/></button></div></div><div className="villa-controls" role="group" aria-label="Choisir une pièce de la villa">{ROOMS.map(({id,label,Icon})=><button key={id} aria-pressed={zone===id} onClick={()=>setZone(id)}><Icon size={18}/>{label}</button>)}</div><p className="villa-help">{status==="fallback"?"Choisis une pièce avec les boutons pour continuer la visite.":"Clique sur une pièce dans la villa, ou utilise les boutons pour la visiter."}</p></section>;
}
