"use client";
import { useEffect,useRef,useState } from "react";
import { ArrowUpRight,Clapperboard,House,RotateCcw,Sun,Waves } from "lucide-react";
import { CrewAvatar } from "@/components/crew-avatar";
import { ROOM_LABELS,type PresenceMember,type PresenceRoom,type PresenceAction } from "@/lib/presence";
import type { Profile } from "@/lib/club";
import type { VillaZone } from "@/lib/villa-three";
const ROOMS=[{id:"villa",label:"Vue d’ensemble",Icon:House},{id:"cinema",label:"Salon cinéma",Icon:Clapperboard},{id:"terrace",label:"La terrasse",Icon:Sun},{id:"jacuzzi",label:"Le jacuzzi",Icon:Waves}] as const;
export function VillaScene({onCinema,onProgramme,onWardrobe,members,profiles,online,person,onMove}:{onCinema:()=>void;onProgramme:()=>void;onWardrobe:()=>void;members:PresenceMember[];profiles:Profile[];online:boolean;person:string;onMove:(room:PresenceRoom,action:PresenceAction)=>void}){
  const host=useRef<HTMLDivElement>(null),scene=useRef<{setZone:(z:VillaZone)=>void;updatePresence:(members:PresenceMember[],profiles:Profile[])=>void;dispose:()=>void}|null>(null);const [zone,setZone]=useState<VillaZone>("villa"),[status,setStatus]=useState("loading");
  const movement=useRef(onMove);movement.current=onMove;
  useEffect(()=>{let stopped=false;void import("@/lib/villa-three").then(({buildVilla})=>{if(stopped||!host.current)return;scene.current=buildVilla(host.current,z=>{setZone(z);movement.current(z,z==="jacuzzi"?"bathe":"walk");},ready=>setStatus(ready?"ready":"fallback"));setStatus("ready");}).catch(()=>{if(!stopped)setStatus("fallback");});return()=>{stopped=true;scene.current?.dispose();scene.current=null;};},[]);
  useEffect(()=>scene.current?.setZone(zone),[zone,status]);
  useEffect(()=>scene.current?.updatePresence(members,profiles),[members,profiles,status]);
  const room=zone==="cinema"?{eyebrow:"LE SALON",title:"La meilleure place, c’est ensemble.",label:"Entrer dans la salle",action:onCinema}:zone==="terrace"?{eyebrow:"LA TERRASSE",title:"On prépare la prochaine sortie ?",label:"Ouvrir le programme",action:onProgramme}:zone==="jacuzzi"?{eyebrow:"LE BAIN DES LÉGENDES",title:"La bouée est un accessoire essentiel.",label:"Passer au vestiaire",action:onWardrobe}:{eyebrow:"BIENVENUE À LA MAISON",title:"Trois espaces. Onze bonnes raisons de rester.",label:"Choisir notre film",action:onCinema};
  return <section className="villa-experience" aria-label="Explorer la villa du crew"><div className="villa-heading"><div><span className="eyebrow">LES 34 CHEVAUX · LE QG</span><h1>LA VILLA <em>DU CREW.</em></h1></div><p>Le salon pour les films.<br/>La terrasse pour les sorties.<br/>Le jacuzzi pour le style.</p></div><div className={`villa-stage scene-${status}`} data-scene-status={status}><img src="/villa-night.webp" alt="Maquette nocturne d’une villa avec salon cinéma, terrasse et jacuzzi" className="villa-fallback"/><div ref={host} className="villa-canvas"/><span className="villa-coordinate">MAGALAS · SEPTEMBRE 2026</span><button className="villa-reset" onClick={()=>{setZone("villa");scene.current?.setZone("villa");}} aria-label="Revenir à la vue d’ensemble"><RotateCcw size={18}/></button><div className="villa-room-card" aria-live="polite"><span className="eyebrow">{room.eyebrow}</span><h2>{room.title}</h2><button className="button primary" onClick={room.action}>{room.label}<ArrowUpRight size={18}/></button></div></div><div className="villa-controls" role="group" aria-label="Choisir une pièce de la villa">{ROOMS.map(({id,label,Icon})=><button key={id} aria-pressed={zone===id} onClick={()=>{setZone(id);onMove(id,id==="jacuzzi"?"bathe":"walk");}}><Icon size={18}/>{label}</button>)}</div><div className="villa-presence-panel"><div className="presence-heading"><span className={online?"presence-live":""}>{online?"EN DIRECT":"RECONNEXION…"}</span><strong>{members.length} présent{members.length!==1?"s":""}</strong><small>Mise à jour automatique · 5 s</small></div><div className="presence-actions"><button onClick={()=>onMove(zone,zone==="jacuzzi"?"bathe":"walk")}>{person?"Me balader ici":"Entrer dans la villa"}</button><button onClick={()=>onMove(zone,zone==="jacuzzi"?"bathe":"sit")}>{zone==="jacuzzi"?"Me détendre dans le bain":"M’asseoir ici"}</button></div><div className="presence-roster">{members.map(member=><span key={member.authorKey}><CrewAvatar name={member.author} small/><span><strong>{member.author}</strong><small>{member.action==="sit"?"Assis ":member.action==="bathe"?"Se détend ":"Se balade "}{ROOM_LABELS[member.room]}</small></span></span>)}</div></div><p className="villa-help">{status==="fallback"?"Choisis une pièce avec les boutons pour continuer la visite.":"Clique sur une pièce dans la villa, ou utilise les boutons pour la visiter."}</p></section>;
}
