"use client";
import { useEffect,useRef,useState,type KeyboardEvent,type PointerEvent } from "react";
import { ArrowUpRight,GripVertical,LoaderCircle,Plus,Sun,X } from "lucide-react";
import { dateLabel,timeLabel,tripDays,type Proposal } from "@/lib/club";
import { ActivityEmojiBadge } from "@/components/activity-emoji";
import { parisDay,moveToDay } from "@/lib/planning";
import { toast } from "sonner";
const visibleDays=tripDays.filter(day=>day>="2026-09-24");
type Drag={proposal:Proposal;day:string;mode:"pointer"|"keyboard";x:number;y:number};
export function WeeklyPlanner({activities,onOpen,onAdd,onMove,canMove,onIdentify}:{activities:Proposal[];onOpen:(id:string)=>void;onAdd:(day:string)=>void;onMove:(p:Proposal,times:{start:string;end:string})=>Promise<void>;canMove:boolean;onIdentify:()=>void}){
  const [drag,setDrag]=useState<Drag|null>(null),[busy,setBusy]=useState<string|null>(null),[announcement,setAnnouncement]=useState("");
  const active=useRef<Drag|null>(null),pointer=useRef<{p:Proposal;x:number;y:number;moving:boolean}|null>(null),suppressClick=useRef(false),scroll=useRef<HTMLDivElement>(null),saving=useRef(false);
  const update=(d:Drag|null)=>{active.current=d;setDrag(d);};
  const cancel=()=>{if(pointer.current)suppressClick.current=true;pointer.current=null;update(null);setAnnouncement("Déplacement annulé.");};
  const commit=async(d:Drag)=>{update(null);pointer.current=null;if(saving.current)return;if(d.day===parisDay(d.proposal.start!)){setAnnouncement("Le créneau reste inchangé.");return;}saving.current=true;setBusy(d.proposal.id);setAnnouncement("Enregistrement du nouveau jour…");try{await onMove(d.proposal,moveToDay(d.proposal,d.day));setAnnouncement(`${d.proposal.title} déplacé au ${dateLabel(d.day)}. Heure et durée conservées.`);}catch(e){toast.error((e as Error).message);setAnnouncement("Le déplacement n’a pas été enregistré.");}finally{setBusy(null);saving.current=false;requestAnimationFrame(()=>document.getElementById(`move-${d.proposal.id}`)?.focus({preventScroll:true}));}};
  const pickup=(p:Proposal)=>{if(busy)return;if(!canMove){onIdentify();return;}if(active.current?.proposal.id===p.id){void commit(active.current);return;}const d={proposal:{...p},day:parisDay(p.start!),mode:"keyboard" as const,x:0,y:0};update(d);setAnnouncement(`${p.title} sélectionné. Choisis un jour ou utilise les flèches, puis Entrée. Échap pour annuler.`);};
  const down=(e:PointerEvent<HTMLButtonElement>,p:Proposal)=>{if(e.button!==0||busy)return;suppressClick.current=false;if(!canMove)return;pointer.current={p:{...p},x:e.clientX,y:e.clientY,moving:false};e.currentTarget.setPointerCapture(e.pointerId);};
  const point=(x:number,y:number)=>document.elementFromPoint(x,y)?.closest<HTMLElement>("[data-plan-day]")?.dataset.planDay;
  const move=(e:PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(!p)return;if(!p.moving&&Math.hypot(e.clientX-p.x,e.clientY-p.y)<7)return;p.moving=true;const day=point(e.clientX,e.clientY)||active.current?.day||parisDay(p.p.start!);update({proposal:p.p,day,mode:"pointer",x:e.clientX,y:e.clientY});};
  const up=(e:PointerEvent<HTMLButtonElement>)=>{const p=pointer.current;if(!p)return;pointer.current=null;if(!p.moving)return;suppressClick.current=true;const d=active.current,day=point(e.clientX,e.clientY);if(d&&day)void commit({...d,day});else cancel();};
  const key=(e:KeyboardEvent<HTMLButtonElement>,p:Proposal)=>{if(e.key==="Escape"){e.preventDefault();cancel();return;}if(e.key===" "||e.key==="Enter"){e.preventDefault();pickup(p);return;}if(active.current?.proposal.id===p.id&&["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();const i=visibleDays.indexOf(active.current.day),direction=e.key==="ArrowLeft"||e.key==="ArrowUp"?-1:1,day=visibleDays[Math.max(0,Math.min(visibleDays.length-1,i+direction))];update({...active.current,day});setAnnouncement(`${dateLabel(day)}. Entrée pour déposer.`);scroll.current?.querySelector(`[data-plan-day="${day}"]`)?.scrollIntoView({block:"nearest",inline:"nearest",behavior:"instant"});}};
  useEffect(()=>{if(!drag||drag.mode!=="pointer")return;let frame=0;const tick=()=>{const d=active.current,el=scroll.current;if(!d||d.mode!=="pointer"||!el)return;const r=el.getBoundingClientRect();if(d.x<r.left+45)el.scrollLeft-=12;else if(d.x>r.right-45)el.scrollLeft+=12;if(d.y<110)window.scrollBy(0,-9);else if(d.y>innerHeight-65)window.scrollBy(0,9);const day=point(d.x,d.y);if(day&&day!==d.day)update({...d,day});frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[drag?.mode]);
  useEffect(()=>{const d=active.current;if(!d)return;const latest=activities.find(p=>p.id===d.proposal.id);if(!latest||latest.updated!==d.proposal.updated||latest.start!==d.proposal.start||latest.end!==d.proposal.end){cancel();toast.info("Cette activité a changé. Reprends-la depuis son nouveau créneau.");}},[activities]);
  useEffect(()=>{const escape=(e:globalThis.KeyboardEvent)=>{if(e.key==="Escape"&&active.current)cancel();};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[]);
  return <><div className="planner-instructions"><GripVertical size={18}/><span>Déplace une activité avec sa poignée. L’heure et la durée restent identiques.</span></div>{drag&&<div className="planner-drag-message" role="status"><strong>{drag.proposal.title}</strong><span>→ {dateLabel(drag.day)}</span><button onClick={cancel} aria-label="Annuler le déplacement"><X size={18}/></button></div>}
    <div className="week-scroll" ref={scroll}><div className={`week-grid ${drag?"is-rearranging":""}`}>{visibleDays.map((day)=>{const plans=activities.filter(p=>p.start&&parisDay(p.start)===day).sort((a,b)=>Date.parse(a.start!)-Date.parse(b.start!));return <div className={`day-column ${parisDay(new Date().toISOString())===day?"today":""} ${drag?.day===day?"drop-target":""}`} key={day} data-plan-day={day}><button className="day-heading" disabled={!drag} onClick={()=>drag&&void commit({...drag,day})} aria-label={drag?`Déposer ${drag.proposal.title} le ${dateLabel(day)}`:dateLabel(day)}><span>{dateLabel(day,{weekday:"short"}).replace(".","")}</span><strong>{Number(day.slice(-2))}</strong><small>{drag?.day===day?"DÉPOSER ICI":parisDay(new Date().toISOString())===day?"AUJOURD’HUI":"SEPTEMBRE"}</small></button><div className="day-events">{plans.length?plans.map(p=><div key={p.id} className={`draggable-event ${drag?.proposal.id===p.id?"being-moved":""} ${busy===p.id?"move-saving":""}`}><button className="day-event" onClick={()=>!drag&&onOpen(p.id)} disabled={busy===p.id}><ActivityEmojiBadge proposal={p}/><span>{timeLabel(p.start!)} — {timeLabel(p.end!)}</span><strong>{p.title}</strong><span className="event-author">{p.author}<ArrowUpRight size={14}/></span></button><button id={`move-${p.id}`} className="event-grip" disabled={!!busy} aria-label={`Déplacer ${p.title}`} aria-pressed={drag?.proposal.id===p.id} onPointerDown={e=>down(e,p)} onPointerMove={move} onPointerUp={up} onLostPointerCapture={()=>{if(pointer.current?.moving)cancel();}} onPointerCancel={()=>{suppressClick.current=true;cancel();}} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return;}pickup(p);}} onKeyDown={e=>key(e,p)}>{busy===p.id?<LoaderCircle size={17} className="spin"/>:<GripVertical size={17}/>}</button></div>):<div className="free-day"><Sun size={20}/><span>{drag?"Dépose ton activité ici":"Quartier libre"}</span></div>}</div><button className="day-add" onClick={()=>onAdd(day)} disabled={!!drag} aria-label={`Proposer une activité le ${dateLabel(day)}`}><Plus size={17}/><span>Une idée ?</span></button></div>;})}</div></div>
    {drag?.mode==="pointer"&&<div className="planner-ghost" style={{left:drag.x+15,top:drag.y-30}} aria-hidden="true"><ActivityEmojiBadge proposal={drag.proposal}/><strong>{drag.proposal.title}</strong></div>}<span className="sr-only" role="status" aria-live="polite">{announcement}</span>
  </>;
}
