import { THREE,type SceneRuntime } from "@/lib/scene-runtime";
import { avatarIndex,avatarSheet,EYEWEAR,HATS,EXTRAS,extraAccessory,lookFor } from "@/lib/appearance";
import { emojiAsset } from "@/lib/emoji-assets";
import { ACCESSORIES, accessoryLayout } from "@/lib/avatar-positions";
import type { Profile } from "@/lib/club";
const pictures=new Map<string,Promise<HTMLImageElement>>();
function picture(url:string){let p=pictures.get(url);if(!p){p=new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>resolve(image);image.onerror=reject;image.src=url;});pictures.set(url,p);void p.catch(()=>{if(pictures.get(url)===p)pictures.delete(url);});if(pictures.size>40)pictures.delete(pictures.keys().next().value!);}return p;}
// Extra transparent margin accommodates accessories at 180%, including near the face edges.
export async function avatarTexture(rt:SceneRuntime,name:string,profiles:Profile[]){const i=avatarIndex(name,profiles),sheet=avatarSheet(i),look=lookFor(name,profiles),profile=profiles.find(p=>p.authorKey===name.trim().normalize("NFKC").toLocaleLowerCase("fr"));let image:HTMLImageElement;let custom=false;try{if(!profile?.imageUrl)throw Error();image=await picture(profile.imageUrl);custom=true;}catch{image=await picture(sheet.url);}if(rt.disposed)return null;const canvas=document.createElement("canvas");canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d')!;ctx.save();ctx.beginPath();ctx.arc(256,256,84,0,Math.PI*2);ctx.clip();if(custom){const size=Math.min(image.width,image.height);ctx.drawImage(image,(image.width-size)/2,(image.height-size)/2,size,size,172,172,168,168);}else {const f=sheet.frame;ctx.drawImage(image,f.x*image.width,f.y*image.height,f.width*image.width,f.height*image.height,172,172,168,168);}ctx.restore();ctx.textAlign="center";ctx.textBaseline="middle";for(const kind of ACCESSORIES){if(kind==="hat"&&look.hat==="none"||kind==="eyewear"&&look.eyewear==="none"||kind==="floatie"&&extraAccessory(look)==="none")continue;const layout=accessoryLayout(kind,look.hat,look.positions,extraAccessory(look));const emoji=kind==="hat"?HATS.find(h=>h.id===look.hat)?.emoji:kind==="eyewear"?EYEWEAR.find(h=>h.id===look.eyewear)?.emoji:EXTRAS.find(h=>h.id===extraAccessory(look))?.emoji;const glyph=await picture(emojiAsset(emoji||"✨"));if(rt.disposed)return null;ctx.save();ctx.translate(172+layout.x*1.68,172+layout.y*1.68);ctx.rotate(layout.rotation*Math.PI/180);const width=layout.width*1.68,height=layout.height*1.68;ctx.drawImage(glyph,-width/2,-height/2,width,height);ctx.restore();}if(name.trim().normalize("NFKC").toLocaleLowerCase("fr")==="alex"){ctx.fillStyle="#dfff00";ctx.beginPath();ctx.roundRect(265,314,94,38,10);ctx.fill();ctx.fillStyle="#112018";ctx.font="900 24px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("DEV",312,334);}const texture=rt.track(new THREE.CanvasTexture(canvas));texture.colorSpace=THREE.SRGBColorSpace;return texture;}
