const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
function compile(source,deps={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,id=>{if(!deps[id])throw Error(id);return deps[id];});return m.exports;}
const g=compile(fs.readFileSync('lib/cookie-game.ts','utf8')),old=compile((()=>{for(const sha of ['caa305b525f3d7e188d255ae12ccce964bf78b66','5083e3c653936a42f47844d81618e4b7bbe30bea']){const r=spawnSync('git',['show',sha+':lib/cookie-game.ts'],{encoding:'utf8'});if(r.status===0)return r.stdout;}throw Error('Missing v29 baseline; fetch repository history.');})()),finale=compile(fs.readFileSync('lib/cookie-finale.ts','utf8'),{'@/lib/cookie-game':g});
const appearance=compile(fs.readFileSync('lib/appearance.ts','utf8'),{'@/lib/cookie-game':g,'@/lib/rewards':{REWARDS:[]},'@/lib/club':{CREW:[]},'@/lib/avatar-positions':{readPositions:()=>({})},'@/lib/identity':{voterKey:s=>s.toLowerCase()}});
const checks=[],failures=[],fresh=patch=>Object.assign(g.freshCookiePlayer(1000),{nextEventAt:1e15},patch),all=g.COOKIE_ACHIEVEMENTS.map(a=>a.id),full=Object.fromEntries(g.MASTERY_TALENTS.map(t=>[t.id,3]));
function check(name,fn){try{fn();checks.push(name);}catch(e){failures.push({name,error:e.message});}}
check('v29 numeric cap and playable chapters unchanged',()=>{assert.equal(g.COOKIE_CAP,1e200);assert.equal(g.COOKIE_CAP,old.COOKIE_CAP);for(const key of ['BUILDINGS','UPGRADES','COOKIE_MISSIONS','COOKIE_ACHIEVEMENTS','CHAPTER_THRESHOLDS','COSMIC_CHAPTERS','MASTERY_TALENTS'])assert.deepEqual(g[key],old[key]);assert.deepEqual(g.COOKIE_AVATARS.filter(a=>a.index!==138),old.COOKIE_AVATARS.filter(a=>a.index!==138));assert(g.FINAL_COOKIE_AVATAR.threshold<old.FINAL_COOKIE_AVATAR.threshold);assert(g.COOKIE_AVATARS.every((a,i)=>a.index===old.COOKIE_AVATARS[i].index));});
check('final avatar keeps its identity with an earlier threshold',()=>{assert.equal(g.COOKIE_AVATARS.length,79);assert.equal(g.FINAL_COOKIE_AVATAR.index,138);assert.equal(g.FINAL_COOKIE_AVATAR.threshold,g.COOKIE_FINALE_TOTAL);assert(g.COOKIE_AVATARS.every((a,i)=>a.index===i+60));});
for(const value of [0,g.COOKIE_FINALE_START,g.COOKIE_FINALE_TOTAL/10,g.COOKIE_FINALE_TOTAL*(1-1e-12)])check('no final affordance before cap '+value,()=>{const p=fresh({lifetime:value});assert(!g.cookieFinished(p));assert.notEqual(g.latestCookieAvatar(value).index,138);assert.equal(finale.cookieFinaleIssueUrl(p,'30.0.0'),null);assert.throws(()=>g.applyCookieAction(p,{kind:'companionEquip',companion:138,revision:0},1000));});
check('exact finish unlocks final legend and safe editable GitHub draft',()=>{const p=fresh({lifetime:g.COOKIE_FINALE_TOTAL});assert(g.cookieFinished(p));assert.equal(g.latestCookieAvatar(p.lifetime).index,138);assert.equal(g.companionRecord(p,138).stage,3);assert(!g.companionCanEvolve(p,138,2));assert(!g.companionCanEvolve(p,138,3));g.applyCookieAction(p,{kind:'companionEquip',companion:138,revision:0},1000);assert.equal(p.voyages.equippedCompanion,138);const url=new URL(finale.cookieFinaleIssueUrl(p,'30.0.0'));assert.equal(url.origin,'https://github.com');assert.equal(url.pathname,'/Aleqsd/les-34-chevaux-du-jacuzzi/issues/new');assert.deepEqual([...url.searchParams.keys()],['title','body']);assert(url.searchParams.get('body').includes('10^153'));assert(url.searchParams.get('body').includes('30.0.0'));assert(url.toString().length<2000);});
check('end reward survives purchase, prestige and serialization',()=>{const p=fresh({lifetime:g.COOKIE_FINALE_TOTAL,balance:1e10,runEarned:1e10});g.applyCookieAction(p,{kind:'companionEquip',companion:138,revision:0},1000);g.applyCookieAction(p,{kind:'buy',building:0,quantity:1},1000);g.applyCookieAction(p,{kind:'prestige'},1000);const loaded=JSON.parse(JSON.stringify(p));assert(g.cookieFinished(loaded));assert.equal(loaded.voyages.equippedCompanion,138);assert.equal(g.companionRecord(loaded,138).stage,3);assert(finale.cookieFinaleIssueUrl(loaded,'30.0.0'));});
check('final legend works in expeditions without extra progression requirement',()=>{const p=fresh({lifetime:g.COOKIE_FINALE_TOTAL});g.applyCookieAction(p,{kind:'voyageStart',destination:'grove',team:[138],cycle:0},1000);assert.equal(p.voyages.active.cargo.dew,7);});
check('single avatar image has finite CSS and canvas crop',()=>{const sheet=appearance.avatarSheet(138);assert.equal(sheet.url,'/cookie-finale-avatar.webp');assert.deepEqual(sheet.frame,{x:0,y:0,width:1,height:1});assert.equal(appearance.avatarBackgroundPosition(sheet.frame),'50% 50%');for(let i=0;i<138;i++){const f=appearance.avatarSheet(i).frame;assert.equal(appearance.avatarBackgroundPosition(f),`${f.x/(1-f.width)*100}% ${f.y/(1-f.height)*100}%`);}});
check('nine talents need exactly27 points, achievable by135 known successes',()=>{assert.equal(g.MASTERY_MAX_POINTS,27);assert.equal(g.masteryPoints(fresh({achievements:all.slice(0,134)})),26);assert.equal(g.masteryPoints(fresh({achievements:all.slice(0,135)})),27);assert.equal(g.masteryPoints(fresh({achievements:all})),27);assert.equal(g.masteryPoints(fresh({achievements:[...all,...all,'unknown']})),27);assert.equal(g.masteryPoints(fresh({achievements:['unknown',...Array(20).fill(all[0])]})),0);});
check('complete tree accepted with exact budget, preserved across prestige and reload',()=>{const p=fresh({achievements:all.slice(0,135),lifetime:1e10,runEarned:1e10});g.applyCookieAction(p,{kind:'mastery',revision:0,ranks:full},1000);assert.equal(g.masterySpent(p),27);assert.equal(g.masteryPoints(p)-g.masterySpent(p),0);const record=JSON.stringify(p.mastery);g.applyCookieAction(p,{kind:'prestige'},1000);assert.equal(JSON.stringify(p.mastery),record);assert.equal(g.masteryPoints(JSON.parse(JSON.stringify(p))),27);});
check('no extra points after end, saved ranks retained and respec remains valid',()=>{const p=fresh({achievements:all,lifetime:g.COOKIE_FINALE_TOTAL,mastery:{revision:3,nextChangeAt:1000,ranks:full}});g.applyCookieAction(p,{kind:'sync'},1000);assert.equal(g.masteryPoints(p),27);assert.deepEqual(p.mastery.ranks,full);g.applyCookieAction(p,{kind:'mastery',revision:3,ranks:{}},1000);assert.equal(g.masteryPoints(p),27);g.applyCookieAction(p,{kind:'mastery',revision:4,ranks:full},1000);assert.equal(g.masterySpent(p),27);});
check('insufficient points, bad rank and stale revision still rejected',()=>{assert.throws(()=>g.applyCookieAction(fresh({achievements:all.slice(0,134)}),{kind:'mastery',revision:0,ranks:full},1000));for(const action of [{revision:1,ranks:full},{revision:0,ranks:{variety:4}},{revision:0,ranks:{links:3}},{revision:0,ranks:{unknown:1}}])assert.throws(()=>g.applyCookieAction(fresh({achievements:all}),{kind:'mastery',...action},1000));});
check('final milestones are hidden before last workshop and logarithmic thereafter',()=>{assert.equal(finale.cookieFinaleProgress(null),null);assert.equal(finale.cookieFinaleProgress(fresh({lifetime:g.COOKIE_FINALE_START*(1-1e-12)})),null);assert.equal(finale.cookieFinaleProgress(fresh({lifetime:g.COOKIE_FINALE_START})),0);const mid=Math.sqrt(g.COOKIE_FINALE_START)*Math.sqrt(g.COOKIE_FINALE_TOTAL);assert(Math.abs(finale.cookieFinaleProgress(fresh({lifetime:mid}))-.5)<1e-12);assert.equal(finale.cookieFinaleProgress(fresh({lifetime:g.COOKIE_FINALE_TOTAL})),1);assert.equal(finale.cookieFinaleProgress(fresh({lifetime:g.COOKIE_CAP})),1);});
check('existing players beyond the new finale unlock immediately without losing scores',()=>{for(const value of [g.COOKIE_FINALE_TOTAL,1e180,g.COOKIE_CAP]){const p=fresh({lifetime:value,balance:value/2,runEarned:value/2});const before=JSON.stringify(p);assert(g.cookieFinished(p));assert.equal(g.companionRecord(p,138).stage,3);assert(finale.cookieFinaleIssueUrl(p,'30.0.0'));assert.equal(JSON.stringify(p),before);g.applyCookieAction(p,{kind:'sync'},1000);assert.equal(p.lifetime,value);assert.equal(p.balance,value/2);}});
check('round finale follows100 final workshops without changing their prices',()=>{const p=fresh({}),last=g.BUILDINGS.length-1;assert.equal(g.buildingUnlock(last),g.COOKIE_FINALE_START);const cost=g.buildingPrice(p,last,100,1000);assert(cost<g.COOKIE_FINALE_TOTAL&&g.COOKIE_FINALE_TOTAL<cost*10);for(const owned of [0,49,50,99,100,999]){p.buildings[last]=owned;for(const qty of [1,10,100])assert.equal(g.buildingPrice(p,last,qty,1000),old.buildingPrice(p,last,qty,1000));}});
const report={passed:checks.length,failed:failures.length,failures};fs.writeFileSync('.sites-runtime/finale-model-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(failures.length)process.exitCode=1;
