// Pure model and compatibility tests; no database or real-player data.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript'),{execFileSync}=require('node:child_process');
const baseline='ff7d676fc10d5f528389cc66aec8b73a88e4b019';
const compile=source=>{const exports={},math=Object.create(Math);math.random=()=>.25;vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Math:math});return exports;};
const g=compile(fs.readFileSync('lib/cookie-game.ts','utf8')),old=compile(execFileSync('git',['show',baseline+':lib/cookie-game.ts'],{encoding:'utf8'}));
const clone=x=>JSON.parse(JSON.stringify(x)),equal=(a,b)=>assert.deepEqual(clone(a),clone(b)),near=(a,b)=>assert(Math.abs(a-b)<=Math.max(1e-8,Math.abs(b)*1e-10)),checks=[],failures=[];
function check(name,fn){try{fn();checks.push(name);}catch(e){failures.push({name,error:e.message});}}
const fresh=(lifetime=1e147)=>Object.assign(g.freshCookiePlayer(1000),{lifetime,balance:0,nextEventAt:1e15,nextEventId:'comet'});
const act=(p,a,at=p.updated)=>g.applyCookieAction(p,a,at);
const revised=(p,a)=>act(p,{...a,revision:p.voyages?.revision??0});
function voyage(p,destination='grove',team=[60,61,62],choices=['study','secret']){act(p,{kind:'voyageStart',destination,team,cycle:p.voyages?.cycle??0});for(let step=0;step<2;step++)act(p,{kind:'voyageChoice',runId:p.voyages.active.id,step,choice:choices[step]},p.voyages.active.readyAt);const run=clone(p.voyages.active);act(p,{kind:'voyageClaim',runId:run.id},run.readyAt);return run;}
function stocked(){const p=fresh();act(p,{kind:'companionEquip',companion:60,revision:0});p.voyages.inventory=Object.fromEntries(g.INGREDIENT_IDS.map(id=>[id,1000]));return p;}
for(const key of ['BUILDINGS','UPGRADES','COOKIE_MISSIONS','COOKIE_ACHIEVEMENTS','COOKIE_AVATARS','CHAPTER_THRESHOLDS','COSMIC_CHAPTERS','AUTO_TIERS','TRIALS','WONDER_PROJECTS','WONDER_STAGES','REBUILD_MISSIONS','MASTERY_TALENTS','SPECIALIZATIONS'])check(key+' complete v27 prefix preserved',()=>equal(g[key].slice(0,old[key].length),old[key]));
for(const lifetime of [0,100,1e12,1e30,1e90,1e120])for(const rich of [false,true])for(const kind of ['sync','click','auto','prestige'])check('legacy '+lifetime+' '+rich+' '+kind,()=>{
 const p=old.freshCookiePlayer(1000);Object.assign(p,{lifetime,balance:1e20,runEarned:1e20,clicks:250000,prestige:39445,autoCredit:40,nextEventAt:1e15,nextEventId:'comet',upgrades:rich?old.UPGRADES.map(u=>u.id):[],missions:['m1'],contracts:{cycle:1,completed:2,nextAcceptAt:1e9,byKind:{produce:2},bySchool:{}}});p.buildings=old.BUILDINGS.map((_,i)=>rich?10:i<3?2:0);old.award(p);
 const q=clone(p),action=kind==='click'||kind==='auto'?{kind,count:2}:{kind};const a=old.applyCookieAction(p,action,2000),b=g.applyCookieAction(q,action,2000);q.buildings=q.buildings.slice(0,47);q.achievements=q.achievements.filter(id=>!id.startsWith('voyage_'));equal(p,q);equal(a,b);
});
check('nine new buildings and forty-five recipes',()=>{assert.equal(g.BUILDINGS.length,56);assert.equal(g.UPGRADES.length,270);assert.equal(g.COSMIC_CHAPTERS.length,14);});
for(let i=47;i<56;i++)check('new building '+i+' unlock and buy',()=>{const p=fresh(g.buildingUnlock(i)-g.buildingUnlock(i)*.01);p.balance=1e190;assert.throws(()=>act(p,{kind:'buy',building:i,quantity:1}));p.lifetime=g.buildingUnlock(i);act(p,{kind:'buy',building:i,quantity:50});assert.equal(p.buildings[i],50);const plan=g.recipePurchasePlan(p);assert(plan.recipes.some(u=>u.id===g.BUILDINGS[i].id+'_signature'));});
for(const d of g.VOYAGE_DESTINATIONS)check('full voyage '+d.id,()=>{const p=fresh(d.threshold);const run=voyage(p,d.id);assert(!p.voyages.active);equal(p.voyages.inventory,run.cargo);assert.equal(p.voyages.relics.length,2);for(const id of run.team){assert.equal(g.companionRecord(p,id).returns,1);assert.equal(g.companionRecord(p,id).secrets,2);equal(g.companionRecord(p,id).regions,[d.id]);}assert.equal(p.balance,0);assert.equal(p.lifetime,d.threshold);assert.throws(()=>act(p,{kind:'voyageClaim',runId:run.id}));});
check('collect branches award primary ingredients and no secrets',()=>{const p=fresh();voyage(p,'grove',[60],['gather','safe']);equal(p.voyages.inventory,{dew:13,cocoa:2});assert.equal(p.voyages.relics.length,0);});
check('start rejects locked worlds, duplicate/unknown/locked/empty teams and stale cycles',()=>{for(const a of [{destination:'paradox',team:[60],cycle:0},{destination:'grove',team:[60,60],cycle:0},{destination:'grove',team:[137],cycle:0},{destination:'grove',team:[0],cycle:0},{destination:'grove',team:[],cycle:0},{destination:'grove',team:[60],cycle:1}])assert.throws(()=>act(fresh(1e6),{kind:'voyageStart',...a}));});
check('only one active expedition, time and choice guards',()=>{const p=fresh();act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:0});const run=p.voyages.active;assert.throws(()=>act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:1}));assert.throws(()=>act(p,{kind:'voyageChoice',runId:1,step:0,choice:'study'},run.readyAt-1));assert.throws(()=>act(p,{kind:'voyageChoice',runId:1,step:0,choice:'secret'},run.readyAt));assert.throws(()=>act(p,{kind:'voyageClaim',runId:1},run.readyAt));act(p,{kind:'voyageChoice',runId:1,step:0,choice:'study'},run.readyAt);assert.throws(()=>act(p,{kind:'voyageChoice',runId:1,step:0,choice:'study'},run.readyAt));});
check('cancellation gives no cargo or exploits, old run cannot affect next',()=>{const p=fresh();act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:0});act(p,{kind:'voyageCancel',runId:1});equal(p.voyages.inventory,{});equal(p.voyages.companions,{});act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:1});assert.throws(()=>act(p,{kind:'voyageCancel',runId:1}));});
check('repeated secrets retain unique collection but progress personal exploits',()=>{const p=fresh();voyage(p);voyage(p);assert.equal(p.voyages.relics.length,2);assert.equal(g.companionRecord(p,60).secrets,4);});
for(const c of g.COOKIE_AVATARS.filter(c=>c.index!==g.FINAL_COOKIE_AVATAR?.index))check(c.name+' has reachable and permanent evolutions',()=>{const p=fresh();assert.throws(()=>revised(p,{kind:'companionEvolve',companion:c.index,stage:3}));for(let i=0;i<8;i++)voyage(p,g.VOYAGE_IDS[i%3],[c.index]);revised(p,{kind:'companionEvolve',companion:c.index,stage:2});revised(p,{kind:'companionEvolve',companion:c.index,stage:3});assert.equal(g.companionRecord(p,c.index).stage,3);assert.throws(()=>revised(p,{kind:'companionEvolve',companion:c.index,stage:3}));});
check('evolution and affinity freeze extra cargo at departure',()=>{const p=fresh();act(p,{kind:'companionEquip',companion:60,revision:0});p.voyages.companions[60]={stage:3,returns:8,finds:100,secrets:10,regions:['grove','lagoon','archive']};act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:0});assert.equal(p.voyages.active.cargo.dew,7);});
check('secret pairs are unique and searchable in both orders',()=>{assert.equal(new Set(g.SECRET_RECIPES.map(r=>Object.keys(r.cost).sort().join(','))).size,9);for(const r of g.SECRET_RECIPES){const [a,b]=Object.keys(r.cost);assert.equal(g.secretCombination(a,b).id,r.id);assert.equal(g.secretCombination(b,a).id,r.id);}assert.equal(g.secretCombination('dew','dew'),undefined);});
for(const recipe of g.SECRET_RECIPES)check('craft '+recipe.id+' exact debit, discovery and revision guards',()=>{const p=stocked(),before=clone(p.voyages.inventory),revision=p.voyages.revision;revised(p,{kind:'secretCraft',recipe:recipe.id});for(const i of g.INGREDIENT_IDS)assert.equal(p.voyages.inventory[i],before[i]-(recipe.cost[i]??0));assert(p.voyages.recipes.includes(recipe.id));assert.equal(p.voyages.equippedRecipe,recipe.id);assert.throws(()=>act(p,{kind:'secretEquip',recipe:null,revision}));assert.throws(()=>revised(p,{kind:'secretCraft',recipe:recipe.id}));});
check('missing ingredients and unlearned equip cannot succeed',()=>{const p=fresh();assert.throws(()=>revised(p,{kind:'secretCraft',recipe:'galette'}));assert.throws(()=>revised(p,{kind:'secretEquip',recipe:'galette'}));});
check('recipe equip settles elapsed production under old rules, no retroactive gain',()=>{const p=stocked();p.buildings[1]=100;revised(p,{kind:'secretCraft',recipe:'nectar'});revised(p,{kind:'secretEquip',recipe:null});p.balance=0;act(p,{kind:'secretEquip',recipe:'nectar',revision:p.voyages.revision},p.updated+10000);near(p.balance,1000);near(g.baseProduction(p),115);near(g.passiveGain(p,p.updated,p.updated+10000),1150);});
check('recipe effects follow family/manual boundaries',()=>{const p=stocked();p.buildings[1]=10;p.buildings[10]=10;p.buildings[47]=10;const base=g.baseProduction(p),manual=g.manualClickPower(p),auto=g.clickPower(p);p.voyages.equippedRecipe='caramel';near(g.baseProduction(p),base);near(g.manualClickPower(p),manual*1.5);near(g.clickPower(p),auto);p.voyages.equippedRecipe='menu';near(g.baseProduction(p),base*1.25);p.voyages.equippedRecipe='biscuit';near(g.voyageBuildingMultiplier(p,47),2*1.4);near(g.voyageBuildingMultiplier(p,10),1);});
check('launch perks explicitly survive strategic recipe switch',()=>{const p=stocked();p.voyages.recipes=['perles','souffle','nectar'];revised(p,{kind:'secretEquip',recipe:'perles'});act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:0});assert.equal(p.voyages.active.cargo.dew,8);revised(p,{kind:'secretEquip',recipe:'souffle'});p.goldenReadyAt=p.updated;act(p,{kind:'golden'});assert.equal(p.rushUntil-p.updated,92000);revised(p,{kind:'secretEquip',recipe:'nectar'});assert.equal(p.rushUntil-p.updated,92000);assert.equal(p.voyages.active.cargo.dew,8);});
check('paradox switches settle old mode and enforce cooldown',()=>{const p=stocked();p.buildings[47]=1;near(g.voyageBuildingMultiplier(p,47),2);act(p,{kind:'paradoxSwitch',mode:'mirror',revision:p.voyages.revision},p.updated+10000);near(p.balance,2e64);near(g.voyageBuildingMultiplier(p,47),1);near(g.voyageBuildingMultiplier(p,48),3);assert.throws(()=>revised(p,{kind:'paradoxSwitch',mode:'light'}));act(p,{kind:'paradoxSwitch',mode:'light',revision:p.voyages.revision},p.voyages.paradoxChangeAt);});
check('origins pairs limited by smallest count and capped at50',()=>{const p=fresh();p.buildings[50]=80;p.buildings[51]=50;p.buildings[52]=20;near(g.voyageBuildingMultiplier(p,50),1.4);p.buildings[52]=60;near(g.voyageBuildingMultiplier(p,52),2);});
check('banquet three services charge once and max at2x',()=>{const p=stocked();for(let course=0;course<3;course++){revised(p,{kind:'banquetPrepare',course});near(g.voyageBuildingMultiplier(p,55),g.BANQUET_COURSES[course].multiplier);assert.throws(()=>revised(p,{kind:'banquetPrepare',course}));}assert.throws(()=>revised(p,{kind:'banquetPrepare',course:3}));});
check('locked worlds cannot activate rules',()=>{const p=stocked();p.lifetime=1e120;assert.throws(()=>revised(p,{kind:'paradoxSwitch',mode:'mirror'}));assert.throws(()=>revised(p,{kind:'banquetPrepare',course:0}));});
check('prestige and serialization retain every voyage field',()=>{const p=stocked();voyage(p);revised(p,{kind:'secretCraft',recipe:'nectar'});revised(p,{kind:'banquetPrepare',course:0});act(p,{kind:'voyageStart',destination:'grove',team:[60],cycle:1});const book=clone(p.voyages);p.runEarned=1e40;act(p,{kind:'prestige'});equal(p.voyages,book);equal(clone(p).voyages,book);});
check('endgame cap prestige and offline earnings remain finite',()=>{const p=stocked();p.lifetime=g.COOKIE_CAP;p.runEarned=g.COOKIE_CAP;p.balance=g.COOKIE_CAP;act(p,{kind:'prestige'});p.buildings=g.BUILDINGS.map(()=>1000);p.upgrades=g.UPGRADES.map(u=>u.id);g.settle(p,p.updated+12*3600000);for(const value of [p.balance,p.lifetime,p.runEarned,p.prestige,g.baseProduction(p),g.clickPower(p)])assert(Number.isFinite(value));});
const report={baseline,passed:checks.length,failed:failures.length,failures};fs.mkdirSync('.sites-runtime',{recursive:true});fs.writeFileSync('.sites-runtime/voyages-model-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(failures.length)process.exitCode=1;
