import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import ts from 'typescript';
import crypto from 'node:crypto';
const base=process.env.COOKIE_TEST_URL||'http://localhost:5173';if(!['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname))throw Error('Local tests only');
function compile(source,deps={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,id=>{if(!deps[id])throw Error('Unknown import '+id);return deps[id];});return m.exports;}
const g=compile(fs.readFileSync('lib/cookie-game.ts','utf8')),ins=compile(fs.readFileSync('lib/cookie-insights.ts','utf8'),{'@/lib/cookie-game':g}),goals=compile(fs.readFileSync('lib/cookie-goals.ts','utf8'),{'@/lib/cookie-game':g,'@/lib/cookie-insights':ins});
const previous=spawnSync('git',['show','HEAD:lib/cookie-game.ts'],{encoding:'utf8'});if(previous.status!==0)throw Error('Missing previous model');const old=compile(previous.stdout);
const checks=[],check=(name,pass,detail)=>{checks.push({name,pass:!!pass,...(!pass?{detail}:{})});},near=(a,b)=>Math.abs(a-b)<=Math.max(1e-8,Math.abs(b)*1e-10),throws=f=>{try{f();return false;}catch{return true;}},fresh=(patch={})=>({...g.freshCookiePlayer(1000),...patch}),all=g.COOKIE_ACHIEVEMENTS.map(a=>a.id),ranks=r=>({revision:1,nextChangeAt:0,ranks:r});
for(const patch of [{},{buildings:[10,15,25,50,100,120,25,25,10,10],upgrades:g.UPGRADES.slice(0,40).map(u=>u.id),prestige:39445,clicks:234000,lifetime:4e18},{buildings:g.BUILDINGS.map(()=>100),upgrades:g.UPGRADES.map(u=>u.id),specialization:'architect',prestige:1000}]){
 const p=fresh(patch);check('v17 production unchanged without talents',old.baseProduction(p)===g.baseProduction(p));check('v17 click unchanged',old.clickPower(p,1000)===g.clickPower(p,1000));check('v17 building prices unchanged',g.BUILDINGS.every((_,i)=>old.buildingPrice(p,i,10)===g.buildingPrice(p,i,10)));
}
check('unique known achievements only',g.masteryPoints(fresh({achievements:[...all,...all,'unknown']}))===27);
check('no points for first four successes',g.masteryPoints(fresh({achievements:all.slice(0,4)}))===0);
const p=fresh({achievements:all});g.applyCookieAction(p,{kind:'mastery',revision:0,ranks:{variety:2,links:3,hands:1}},1000);check('valid allocation persists revision',p.mastery.revision===1&&g.masterySpent(p)===6);
for(const action of [{revision:0,ranks:{variety:1}},{revision:1,ranks:{variety:-1}},{revision:1,ranks:{variety:1.5}},{revision:1,ranks:{variety:4}},{revision:1,ranks:{unknown:1}},{revision:1,ranks:{links:1}}])check('invalid allocation rejected '+JSON.stringify(action),throws(()=>g.applyCookieAction(structuredClone(p),{kind:'mastery',...action},1000)));
check('redistribution cooldown enforced',throws(()=>g.applyCookieAction(structuredClone(p),{kind:'mastery',revision:1,ranks:{}},1001)));
g.applyCookieAction(p,{kind:'mastery',revision:1,ranks:{variety:3,links:3,hands:1}},1001);check('new points add during cooldown',g.masterySpent(p)===7);
g.applyCookieAction(p,{kind:'mastery',revision:2,ranks:{gifts:2,rush:2,rest:3}},1201000);check('free redistribution after20min',p.mastery.revision===3&&g.masterySpent(p)===7);
const causal=fresh({buildings:[0,10,...Array(14).fill(0)],achievements:all});g.applyCookieAction(causal,{kind:'mastery',revision:0,ranks:{variety:3}},11000);check('elapsed income uses old allocation',near(causal.balance,100));check('future production uses new ranks',near(g.baseProduction(causal),10*1.0075));
const synergy=fresh({buildings:g.BUILDINGS.map(()=>250),upgrades:['link_spoon_dimension'],mastery:ranks({links:3})});check('only synergy bonus amplified',near(g.synergyMultiplier(synergy,10),1.65));
const discount=fresh({specialization:'architect',mastery:ranks({plans:3})});check('discount stacks multiplicatively',g.buildingPrice(discount,1,10)===Math.ceil(100*(1.15**10-1)/.15*.92*.97));
const artisan=fresh({specialization:'artisan',mastery:ranks({hands:3})});check('manual bonus excluded from pilot',near(g.manualClickPower(artisan,1000),1.4)&&g.clickPower(artisan,1000)===1);
check('offline extends watcher to15h',g.offlineHours(fresh({specialization:'watcher',mastery:ranks({rest:3})}))===15);
const gifts=fresh({buildings:[0,10],mastery:ranks({gifts:3,rush:3})});check('flying gifts boosted30percent',near(g.cookieEventReward(gifts,6000),260));check('golden rush max86s',g.goldenRushSeconds(gifts)===86);
const reb=fresh({runEarned:1e9,lifetime:1e9,achievements:all,mastery:ranks({starter:3,grants:3,plans:3}),followedGoal:{kind:'building',id:'oven',target:10,run:0},followRevision:1});
g.applyCookieAction(reb,{kind:'prestige'},1000);check('starter boosted and snapshotted once',reb.balance===687&&reb.rebuild.starterAmount===687&&g.masteryStarter(reb)===687);const record=JSON.stringify(reb.mastery);g.settle(reb,1000);check('sync does not repeat starter',reb.balance===687);check('mastery and tracked goal survive prestige',JSON.stringify(reb.mastery)===record&&reb.followedGoal.id==='oven'&&reb.followRevision===1);
reb.mastery.ranks={};check('rebuild bonuses frozen across respec',g.rebuildReward(reb,500)===962);reb.buildings[0]=5;const life=reb.lifetime,run=reb.runEarned;g.applyCookieAction(reb,{kind:'rebuild',mission:'r1',run:reb.resets},1000);check('rebuild bonus never production',reb.lifetime===life&&reb.runEarned===run&&reb.balance===1649);
const trial=fresh({lifetime:1e12,mastery:ranks(Object.fromEntries(g.MASTERY_TALENTS.map(t=>[t.id,3])))});g.applyCookieAction(trial,{kind:'trialStart',scenario:'hands',cycle:0},1000);g.applyCookieAction(trial,{kind:'trialClick',runId:1,count:12},1000);check('trial clicks stay isolated',trial.trials.active.produced===300&&trial.lifetime===1e12);
const pref=fresh();g.applyCookieAction(pref,{kind:'followGoal',revision:0,goal:{kind:'building',id:'oven',target:10,run:0}},1000);check('follow saves revision',pref.followRevision===1);check('stale clear rejected',throws(()=>g.applyCookieAction(pref,{kind:'followGoal',revision:0,goal:null},1000)));check('missing contract rejected',throws(()=>g.applyCookieAction(pref,{kind:'followGoal',revision:1,goal:{kind:'contract',id:'undefined',target:1,run:0}},1000)));
const newbie=fresh();check('new player has achievable first goal',goals.recommendGoals(newbie,false).some(x=>x.goal.id==='spoon'));check('building goal finishes at target',goals.describeGoal(fresh({buildings:[10]}),{kind:'building',id:'spoon',target:10,run:0},false).complete);
const veteran=fresh({lifetime:4e18,balance:3e18,buildings:[212,210,184,165,147,130,108,101,99,90,1,0,0,0,0,0],upgrades:g.UPGRADES.slice(0,40).map(u=>u.id),missions:g.COOKIE_MISSIONS.slice(0,24).map(m=>m.id),trials:{cycle:0,bests:{}}});const recommendations=goals.recommendGoals(veteran,true);check('veteran gets a trial or cosmic target',recommendations.some(x=>x.goal.kind==='trial'||['dimension','stable'].includes(x.goal.id)));check('rebuild goal cannot point at previous run',!goals.describeGoal(fresh({resets:2}),{kind:'rebuild',id:'r1',target:1,run:1},false));check('trial goal bronze→silver',goals.describeGoal(fresh({trials:{cycle:1,bests:{hands:{seconds:300,medal:1}}}}),{kind:'trial',id:'hands',target:2,run:0},false).complete===false);
// Same synthetic mature workshop, pure model only: report timing, never assert a noisy speed ratio.
const bench=fresh({buildings:g.BUILDINGS.map(()=>100),upgrades:g.UPGRADES.map(u=>u.id),prestige:39445});const measure=fn=>{for(let i=0;i<1000;i++)fn(bench);const at=performance.now();for(let i=0;i<10000;i++)fn(bench);return performance.now()-at;};const timing={v17ms:measure(old.baseProduction),v18ms:measure(g.baseProduction),iterations:10000};
const name='TestMastery18',key=name.toLowerCase(),quote=s=>"'"+String(s).replaceAll("'","''")+"'";let owned=false;
function db(sql){const r=spawnSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--command',sql,'--json'],{encoding:'utf8',maxBuffer:2e6});if(r.status!==0)throw Error(r.stderr||r.stdout);return JSON.parse(r.stdout);}
async function req(action,id=crypto.randomUUID()){const r=await fetch(base+'/api/cookie',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({author:name,id,action})});return {status:r.status,...await r.json()};}
try{
 if(db('SELECT author_key FROM cookie_players WHERE author_key='+quote(key))[0].results.length)throw Error('Pre-existing fixture; refusing overwrite');
 await req({kind:'sync'});owned=true;const seed=fresh({updated:Date.now()+60000,achievements:all,balance:1e9});db('UPDATE cookie_players SET data='+quote(JSON.stringify(seed))+',updated='+seed.updated+',version=version+1 WHERE author_key='+quote(key));
 const id=crypto.randomUUID(),same=await Promise.all([req({kind:'mastery',revision:0,ranks:{variety:2}},id),req({kind:'mastery',revision:0,ranks:{variety:2}},id)]);check('duplicate UUID allocates once',same.every(x=>x.status===200&&x.player.mastery.revision===1));
 const concurrent=await Promise.all([req({kind:'mastery',revision:1,ranks:{variety:3}}),req({kind:'mastery',revision:1,ranks:{variety:2,gifts:1}})]);check('two tab allocations cannot overwrite',concurrent.filter(x=>x.status===200).length===1&&concurrent.filter(x=>x.status===400).length===1);
 for(const ranks of [{variety:4},{variety:-1},{variety:1.5},{surprise:1}])check('schema rejects forged ranks', (await req({kind:'mastery',revision:2,ranks})).status===400);
 const goal={kind:'building',id:'oven',target:10,run:0},follow=await req({kind:'followGoal',goal,revision:0});check('follow API saves',follow.status===200&&follow.player.followRevision===1);check('stale follow API rejects',(await req({kind:'followGoal',goal:null,revision:0})).status===400);
 const reread=await(await fetch(base+'/api/cookie?author='+name)).json();check('read preserves mastery and followed goal',reread.player.mastery.revision===2&&reread.player.followedGoal.id==='oven');
}finally{if(owned){db('DELETE FROM cookie_actions WHERE author_key='+quote(key));db('DELETE FROM cookie_players WHERE author_key='+quote(key));}}
const failed=checks.filter(c=>!c.pass);console.log(JSON.stringify({total:checks.length,passed:checks.length-failed.length,failed,timing},null,2));if(failed.length)process.exitCode=1;
