import fs from 'node:fs';import ts from 'typescript';import {spawnSync} from 'node:child_process';import crypto from 'node:crypto';
const base=process.env.COOKIE_TEST_URL||'http://localhost:5173';if(!['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname))throw Error('Local tests only');
const compile=(src,deps={})=>{const m={exports:{}};new Function('exports','module','require',ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,id=>deps[id]);return m.exports;};
const g=compile(fs.readFileSync('lib/cookie-game.ts','utf8')),ins=compile(fs.readFileSync('lib/cookie-insights.ts','utf8'),{'@/lib/cookie-game':g});
const checks=[],owned=[],issues=[],check=(name,pass,detail)=>checks.push({name,pass:!!pass,...(!pass?{detail}:{})}),near=(a,b)=>Math.abs(a-b)<Math.max(1e-7,Math.abs(b)*1e-10),fresh=(patch={})=>({...g.freshCookiePlayer(1000),...patch}),quote=s=>"'"+String(s).replaceAll("'","''")+"'";
function db(sql){const r=spawnSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--command',sql,'--json'],{encoding:'utf8',maxBuffer:2e6});if(r.status!==0)throw Error(r.stderr||r.stdout);return JSON.parse(r.stdout);}
async function req(author,action,id=crypto.randomUUID(),status=200){const r=await fetch(base+'/api/cookie',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({author,id,action})});const d=await r.json();if(status!==null)check(action.kind+' HTTP '+status,r.status===status,d);return {...d,status:r.status};}
const seed=(name,p)=>'UPDATE cookie_players SET data='+quote(JSON.stringify(p))+',version=version+1,updated='+p.updated+',last_action=\'\' WHERE author_key='+quote(name.toLowerCase())+';';
const world=async()=>await(await fetch(base+'/api/wonder')).json();
try{
 const previous=compile(spawnSync('git',['show','HEAD:lib/cookie-game.ts'],{encoding:'utf8'}).stdout);check('old stage IDs and content stable',JSON.stringify(g.WONDER_STAGES.slice(0,previous.WONDER_STAGES.length))===JSON.stringify(previous.WONDER_STAGES));
 const p=fresh({buildings:g.BUILDINGS.map(()=>20),upgrades:g.UPGRADES.map(u=>u.id),clicks:100000,trialBoostUntil:11000}),plain={...p,trialBoostUntil:0};
 check('all production and clicks doubled',near(g.production(p,1000),2*g.production(plain,1000))&&near(g.clickPower(p,1000),2*g.clickPower(plain,1000))&&near(g.manualClickPower(p,1000),2*g.manualClickPower(plain,1000)));
 check('production claims are not inflated by reward',JSON.stringify(g.contractTerms(p,'produce'))===JSON.stringify(g.contractTerms(plain,'produce'))&&g.baseProduction(p)===g.baseProduction(plain));
 check('recommendation ROI excludes temporary boost',JSON.stringify(ins.recipeImpact({...p,upgrades:[]},g.UPGRADES[0]))===JSON.stringify(ins.recipeImpact({...plain,upgrades:[]},g.UPGRADES[0]))&&ins.steadyIncome(p,true)===ins.steadyIncome(plain,true));
 let accurate=true;for(const rush of [0,1000,5000,20000])for(const steam of [0,1000,5000,20000])for(const boost of [0,1000,5000,20000]){const save={...p,rushUntil:rush,eventBuffs:{steamUntil:steam},trialBoostUntil:boost};let expected=0;for(let t=1000;t<16000;t+=100)expected+=g.production(save,t+50)*.1;if(!near(expected,g.passiveGain(save,1000,16000)))accurate=false;}check('all 64 expiry overlaps integrate exactly',accurate);
 const finished=now=>({cycle:1,bests:{hands:{medal:3,seconds:1}},active:{id:1,scenario:'hands',rulesVersion:1,startedAt:now-300000,updated:now,balance:5000,produced:5000,spent:0,buildings:[0,0,0,0,0],clickCredit:0,finishedAt:now}});
 const rewarded=fresh({trials:finished(1000),trialBoostUntil:2000000});g.applyCookieAction(rewarded,{kind:'trialClaim',runId:1},1000);check('slower victory refreshes one hour without changing best',rewarded.trialBoostUntil===3601000&&rewarded.trials.bests.hands.seconds===1);
 rewarded.runEarned=1e9;rewarded.wonderDecor='jacuzzi';rewarded.wonder={completed:[0,1],active:{stage:2,target:567,progress:123,referenceRate:.945}};const saved=JSON.stringify(rewarded.wonder);g.applyCookieAction(rewarded,{kind:'prestige'},1000);check('prestige preserves reward and original active quota',rewarded.trialBoostUntil===3601000&&rewarded.wonderDecor==='jacuzzi'&&JSON.stringify(rewarded.wonder)===saved);
 check('expiry exact boundary',g.production(p,11000)===g.production(plain,11000));
 const initial=await world();if(initial.stage!==0)throw Error('Local collective world already progressed; refusing global fixture');
 for(let i=0;i<5;i++){const name='TestWonders20_'+i;if(db('SELECT author_key FROM cookie_players WHERE author_key='+quote(name.toLowerCase()))[0].results.length)throw Error('Pre-existing fixture');await req(name,{kind:'sync'});owned.push(name);}
 const at=Date.now()+120000,players=owned.map(()=>fresh({lifetime:1e12,updated:at}));db(owned.map((name,i)=>seed(name,players[i])).join('\n'));
 const guest=owned[4];await req(guest,{kind:'wonderStart',stage:0});await req(guest,{kind:'wonderStart',stage:12},undefined,400);await req(guest,{kind:'wonderDecor',decor:'invalid'},undefined,400);await req(guest,{kind:'wonderDecor',decor:'jacuzzi',wonderStage:12},undefined,400);
 for(let stage=0;stage<12;stage++){
  const starts=await Promise.all(owned.slice(0,4).map(name=>req(name,{kind:'wonderStart',stage})));for(const r of starts)r.player.wonder.active.progress=r.player.wonder.active.target;db(starts.map((r,i)=>seed(owned[i],r.player)).join('\n'));
  const project=g.wonderProjectAt(stage);await req(guest,{kind:'wonderDecor',decor:project.id},undefined,400);
  const id=crypto.randomUUID();const first=await Promise.all([req(owned[0],{kind:'wonderDeliver',stage},id),req(owned[0],{kind:'wonderDeliver',stage},id)]);check('duplicate delivery preserves one entry stage '+stage,first.every(r=>r.player.wonder.completed.filter(n=>n===stage).length===1));
  const partial=await world();check('one contributor never advances stage '+stage,partial.stage===stage);
  await Promise.all(owned.slice(1,4).map(name=>req(name,{kind:'wonderDeliver',stage})));const after=await world();check('four contributors advance stage '+stage,after.stage===stage+1&&after.stages[stage].contributors.length===4);
  await req(owned[0],{kind:'wonderStart',stage},undefined,400);
  if(stage+1===project.end){const equipId=crypto.randomUUID();const equipped=await Promise.all([req(guest,{kind:'wonderDecor',decor:project.id},equipId),req(guest,{kind:'wonderDecor',decor:project.id},equipId)]);check('collective reward available without personal contribution '+project.id,equipped.every(r=>r.player.wonderDecor===project.id&&r.player.wonder.completed.length===0));}
 }
 const end=await world();check('all 12 stages complete with final project accessible',end.stage===12&&g.wonderProjectAt(end.stage).id==='raceway');
 const late=(await req(guest,{kind:'sync'})).player;late.wonder.active.progress=late.wonder.active.target;db(seed(guest,late));const delivered=await req(guest,{kind:'wonderDeliver',stage:0});check('late contribution stays on original stage',delivered.player.wonder.completed.join(',')==='0'&&(await world()).stage===12);
 const trialSave=fresh({updated:at,lifetime:1e12,trials:finished(at),wonderDecor:'raceway'});db(seed(guest,trialSave));const claimId=crypto.randomUUID();const claims=await Promise.all([req(guest,{kind:'trialClaim',runId:1},claimId),req(guest,{kind:'trialClaim',runId:1},claimId)]);check('duplicate reward never extends expiry',claims[0].player.trialBoostUntil===claims[1].player.trialBoostUntil&&claims[0].player.trialBoostUntil>Date.now()+3590000);const again=await req(guest,{kind:'trialClaim',runId:1},claimId);check('later UUID retry retains same expiry',again.player.trialBoostUntil===claims[0].player.trialBoostUntil);await req(guest,{kind:'trialClaim',runId:1},undefined,400);
 check('claim does not replace equipped collective decor',again.player.wonderDecor==='raceway'&&!again.player.decor);
 const switched=await req(guest,{kind:'decor',decor:'hands'});check('trial selection clears collective decor',switched.player.decor==='hands'&&!switched.player.wonderDecor);
 const reset=await req(guest,{kind:'wonderDecor',decor:'default'});check('default clears both decors',!reset.player.decor&&!reset.player.wonderDecor);
 db(seed(guest,trialSave));const competing=await Promise.all([req(guest,{kind:'trialClaim',runId:1},undefined,null),req(guest,{kind:'trialClaim',runId:1},undefined,null)]);check('distinct concurrent claims award once',competing.filter(r=>r.status===200).length===1&&competing.filter(r=>r.status===400).length===1);
}catch(e){issues.push(String(e));}finally{for(const name of owned){const key=quote(name.toLowerCase());db('DELETE FROM cookie_actions WHERE author_key='+key+'; DELETE FROM cookie_players WHERE author_key='+key);}}
const result={total:checks.length,passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass),issues};fs.writeFileSync('.sites-runtime/wonders-v20-report.json',JSON.stringify({checks,...result},null,2));console.log(JSON.stringify(result,null,2));if(result.failed.length||issues.length)process.exitCode=1;
