import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const origin=process.argv[2]||'http://127.0.0.1:5173';
if(!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw new Error('Local tests only');
const author='Test API';const checks=[];
async function post(path,body,status=201){const r=await fetch(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,status,JSON.stringify(data));return data;}
const club=body=>post('/api/club',body);const social=(body,status)=>post('/api/social',body,status);const state=async()=>{const r=await fetch(origin+'/api/club');assert.equal(r.status,200);return r.json();};
const existing=await state();const movies=existing.proposals.filter(p=>p.kind==='movie'&&p.author===author);const first=movies[0]||await club({action:'propose',kind:'movie',title:'Film test 1',author});
const catalog=await (await fetch(origin+'/api/movies?q=Interstellar')).json();const movie=catalog.movies.find(m=>m.id==='157336');
const second=await club({action:'propose',kind:'movie',title:movie?.title||'Film test 2',author,movie});const activity=existing.proposals.find(p=>p.kind==='activity'&&p.author===author)||await club({action:'propose',kind:'activity',title:'Test API activité',author,url:'https://example.com',start:'2026-09-24T14:00:00+02:00',end:'2026-09-24T18:00:00+02:00'});
await social({action:'duel',id:crypto.randomUUID(),firstId:first.id,secondId:second.id,chosenId:first.id,author},400);
let current=await state();assert.equal('duelVotes' in current,false);assert.deepEqual(current.votes,existing.votes);checks.push('Removed duel endpoint rejects writes; no duel data exposed');
const comment={action:'comment',id:crypto.randomUUID(),proposalId:activity.id,author,body:'Ça va être incroyable ! <script>alert(1)</script>'};await social(comment);await social(comment);await social({...comment,id:crypto.randomUUID(),body:'   '},400);await social({...comment,id:crypto.randomUUID(),body:'a'.repeat(1501)},400);current=await state();assert.equal(current.comments.filter(c=>c.id===comment.id).length,1);assert.equal(current.comments.find(c=>c.id===comment.id).body,comment.body);checks.push('Comments preserve plain text and accents; empty/oversized rejected; retry idempotent');
const details={action:'details',proposalId:activity.id,author,costCents:null,address:'3 rue de la Huppe, 34480 Magalas',travel:'≈ 15 min en voiture',capacity:null,pricing:'Karaoké : 10 €/pers. Quiz : 10 €/pers.',notes:'Infos de test locales. Réservation à confirmer.'};await social(details);current=await state();assert.equal(current.activityDetails.find(d=>d.proposalId===activity.id).costCents,null);await social({...details,costCents:0,capacity:11});current=await state();assert.equal(current.activityDetails.find(d=>d.proposalId===activity.id).costCents,0);await social({...details,capacity:-1},400);await social({...details,proposalId:first.id},400);checks.push('Rich details preserve unknown versus free; invalid capacity and movie target rejected');
const plan={action:'select',id:crypto.randomUUID(),proposalId:activity.id,author,start:'2026-09-24T14:00:00+02:00',end:'2026-09-24T18:00:00+02:00'};await social(plan);await social(plan);await social({...plan,id:crypto.randomUUID(),end:'2026-09-24T12:00:00+02:00'},400);await social({...plan,id:crypto.randomUUID(),start:'2026-10-01T12:00:00+02:00',end:'2026-10-01T14:00:00+02:00'},400);current=await state();assert.equal(current.plans.filter(p=>p.id===plan.id).length,1);assert.equal(current.participants.filter(p=>p.planId===plan.id).length,0);checks.push('Explicit retained plan stable and idempotent; time bounds validated; votes never imply attendance');
const attendance={action:'attend',planId:plan.id,author,attending:true};await social(attendance);await social({...attendance,author:' TEST API '});current=await state();assert.equal(current.participants.filter(p=>p.planId===plan.id&&p.attending).length,1);await social({...attendance,attending:false});current=await state();assert.equal(current.participants.filter(p=>p.planId===plan.id&&p.attending).length,0);assert.deepEqual(current.votes,existing.votes);checks.push('Attendance normalized by declared name; repeated confirmation/updating does not duplicate or alter votes');
await social({action:'profile',author,avatar:11,imageUrl:''});await social({action:'profile',author:'TEST API',avatar:35,imageUrl:''});await social({action:'profile',author,avatar:36,imageUrl:''},400);await social({action:'profile',author,avatar:-1,imageUrl:''},400);await social({action:'profile',author,avatar:1.5,imageUrl:''},400);await social({action:'profile',author,avatar:0,imageUrl:'javascript:alert(1)'},400);current=await state();assert.equal(current.profiles.filter(p=>p.authorKey==='test api').length,1);assert.equal(current.profiles.find(p=>p.authorKey==='test api').avatar,35);checks.push('Shared kawaii avatar selection persists; invalid preset and unsafe URL rejected');
const denied=await fetch(origin+'/api/social',{method:'POST',headers:{Origin:'https://example.net','Content-Type':'application/json'},body:JSON.stringify(comment)});assert.equal(denied.status,403);checks.push('Cross-origin social writes rejected');
const report={passed:true,checkedAt:new Date().toISOString(),checks,fixtures:{firstId:first.id,secondId:second.id,activityId:activity.id,planId:plan.id}};writeFileSync('.sites-runtime/social-validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
