import fs from 'node:fs';import ts from 'typescript';import {spawnSync} from 'node:child_process';import crypto from 'node:crypto';
const base=process.env.COOKIE_TEST_URL||'http://localhost:5173';if(!['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname))throw Error('Local tests only');
function compile(source,deps={}){const m={exports:{}};new Function('exports','module','require',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,id=>deps[id]);return m.exports;}
const g=compile(fs.readFileSync('lib/cookie-game.ts','utf8')),ins=compile(fs.readFileSync('lib/cookie-insights.ts','utf8'),{'@/lib/cookie-game':g}),goals=compile(fs.readFileSync('lib/cookie-goals.ts','utf8'),{'@/lib/cookie-game':g,'@/lib/cookie-insights':ins});
const oldSource=spawnSync('git',['show','HEAD:lib/cookie-game.ts'],{encoding:'utf8'});if(oldSource.status!==0)throw Error('Previous model missing');const old=compile(oldSource.stdout);
const checks=[],check=(name,pass,detail)=>checks.push({name,pass:!!pass,...(!pass?{detail}:{})}),near=(a,b)=>Math.abs(a-b)<=Math.max(1e-8,Math.abs(b)*1e-10),throws=f=>{try{f();return false;}catch{return true;}},fresh=(patch={})=>({...g.freshCookiePlayer(1000),...patch}),clone=structuredClone;
for(let i=0;i<6;i++){const at=6000+i*1000;check('legacy scheduled identity '+i,g.cookieEvent(at).id===old.cookieEvent(at).id);}
for(const patch of [{},{buildings:g.BUILDINGS.map(()=>25),upgrades:g.UPGRADES.map(u=>u.id),prestige:39445,clicks:234000,lifetime:4e18,mastery:{revision:2,nextChangeAt:0,ranks:{variety:2,links:3,hands:2,gifts:3,rush:1,plans:3}}}]){const p=fresh(patch);check('v18 base, click, prices retained',near(g.baseProduction(p),old.baseProduction(p))&&near(g.manualClickPower(p,1000),old.manualClickPower(p,1000))&&g.BUILDINGS.every((_,i)=>g.buildingPrice(p,i,10,1000)===old.buildingPrice(p,i,10)));const a=clone(p),b=clone(p);g.settle(a,60000);old.settle(b,60000);check('v18 settle retained',near(a.balance,b.balance)&&near(a.lifetime,b.lifetime));}
const event=(id,choice)=>{const p=fresh({nextEventAt:1000,nextEventId:id,buildings:[0,10]});const result=g.applyCookieAction(p,{kind:'event',eventAt:1000,...(choice?{choice}:{})},1000);return {p,result};};
const gallop=event('gallop').p;check('galop manual only',g.manualClickPower(gallop,1000)===4&&g.clickPower(gallop,1000)===2&&g.production(gallop,1000)===10);check('galop exact expiry',g.manualClickPower(gallop,25999)===4&&g.manualClickPower(gallop,26000)===2);const clicks=g.applyCookieAction(gallop,{kind:'click',count:25},1000);check('manual cap still24 burst and12 per second',clicks.acceptedClicks===24&&g.applyCookieAction(gallop,{kind:'click',count:25},2000).acceptedClicks===12);
const steam=event('steam').p;check('steam only passive',g.production(steam,1000)===30&&g.manualClickPower(steam,1000)===2);check('steam expiry prorated',near(g.passiveGain(steam,1000,91000),2100));
for(const [rush,steamEnd,expected] of [[31000,61000,3300],[61000,31000,4500],[61000,61000,4500],[1000,1000,900]]){const p=fresh({buildings:[0,10],rushUntil:rush,eventBuffs:{manualMultiplier:2,steamUntil:steamEnd}});check('overlap integrates max '+rush+'/'+steamEnd,near(g.passiveGain(p,1000,91000),expected));const pieces=g.passiveGain(p,1000,20000)+g.passiveGain(p,20000,45000)+g.passiveGain(p,45000,91000);check('split settlement invariant',near(pieces,expected));}
const offline=fresh({buildings:[0,10],eventBuffs:{manualMultiplier:2,steamUntil:61000}});g.settle(offline,48*3600000+1000);check('offline cap and steam not extended',near(offline.balance,10*(8*3600+120)));
const merchant=event('merchant').p;merchant.balance=100000;const basePrice=g.buildingPrice({...merchant,eventBuffs:undefined},1,10,1000),discount=g.buildingPrice(merchant,1,10,1000);check('merchant discount before rounding',discount===Math.ceil(100*1.15**10*(1.15**10-1)/.15*.85));const money=merchant.balance;g.applyCookieAction(merchant,{kind:'buy',building:1,quantity:10},1000);check('one lot consumes entire offer',merchant.balance===money-discount&&!g.eventDiscount(merchant,1000));
const poor=event('merchant').p;poor.balance=0;check('failed buy preserves offer',throws(()=>g.applyCookieAction(poor,{kind:'buy',building:1,quantity:100},1000))&&g.eventDiscount(poor,1000));check('discount expires exactly',g.eventDiscount(poor,45999)&&!g.eventDiscount(poor,46000));
const architect=fresh({specialization:'architect',mastery:{revision:1,nextChangeAt:0,ranks:{plans:3}},eventBuffs:{manualMultiplier:2,discountUntil:2000}});check('all discounts multiply',g.buildingPrice(architect,1,10,1000)===Math.ceil(100*(1.15**10-1)/.15*.92*.97*.85));
const missing=fresh({nextEventAt:1000,nextEventId:'crossroads'});check('crossroad requires explicit choice',throws(()=>g.applyCookieAction(missing,{kind:'event',eventAt:1000},1000)));check('irrelevant choice rejected',throws(()=>g.applyCookieAction(fresh({nextEventAt:1000,nextEventId:'steam'}),{kind:'event',eventAt:1000,choice:'burst'},1000)));
const burst=event('crossroads','burst');check('choice burst3x20s no lump',g.manualClickPower(burst.p,1000)===6&&burst.p.eventBuffs.manualUntil===21000&&burst.result.eventReward===0);const harvest=event('crossroads','harvest');check('choice harvest90s no buff',harvest.result.eventReward===900&&harvest.p.balance===900&&!harvest.p.eventBuffs);
check('already caught event rejects',throws(()=>g.applyCookieAction(harvest.p,{kind:'event',eventAt:1000,choice:'harvest'},1000)));
const contract=fresh({nextEventAt:1000,nextEventId:'crossroads',buildings:[0,10],contracts:{cycle:1,nextAcceptAt:0,completed:0,byKind:{},bySchool:{},active:{id:1,kind:'produce',progress:0,target:1e6,reward:10,referenceRate:10,acceptedAt:1000}},wonder:{completed:[],active:{stage:0,progress:0,target:1e6,referenceRate:10}}});g.applyCookieAction(contract,{kind:'event',eventAt:1000,choice:'harvest'},1000);check('lump does not advance real production',contract.contracts.active.progress===0&&contract.wonder.active.progress===0);contract.eventBuffs={manualMultiplier:2,steamUntil:61000};g.settle(contract,61000);check('steam advances real production',contract.contracts.active.progress===1800&&contract.wonder.active.progress===1800);
const spending=event('merchant').p;spending.balance=1e9;spending.contracts={cycle:1,nextAcceptAt:0,completed:0,byKind:{},bySchool:{},active:{id:1,kind:'spend',progress:0,target:1e9,reward:10,referenceRate:10,acceptedAt:1000}};const paid=g.buildingPrice(spending,0,10,1000);g.applyCookieAction(spending,{kind:'buy',building:0,quantity:10},1000);check('spend contracts count actual discounted cost',spending.contracts.active.progress===paid);
const prestige=event('steam').p;Object.assign(prestige,{runEarned:1e9,lifetime:1e12,mastery:{revision:3,nextChangeAt:1234,ranks:{gifts:2}}});g.applyCookieAction(prestige,{kind:'prestige'},1000);check('prestige clears temporary buffs only',!prestige.eventBuffs&&prestige.mastery.revision===3&&prestige.mastery.ranks.gifts===2);
const trial=event('gallop').p;trial.lifetime=1e12;g.applyCookieAction(trial,{kind:'trialStart',scenario:'hands',cycle:0},1000);g.applyCookieAction(trial,{kind:'trialClick',runId:1,count:12},1000);check('event excluded from trial',trial.trials.active.produced===300);
const offer=fresh({buildings:[1,1,...Array(14).fill(0)],clicks:50000,balance:1000,missions:g.COOKIE_MISSIONS.map(m=>m.id)});const off=goals.recommendGoals(offer,false,1000),on=goals.recommendGoals(offer,true,1000);check('pilot OFF economic top not pure click',off[0].goal.kind==='building'||ins.recipeImpact(offer,g.UPGRADES.find(u=>u.id===off[0].goal.id)).production>0,off[0]);check('manual recipe still offered explicitly',off.some(x=>x.goal.kind==='upgrade'&&x.detail.includes('/ clic manuel')));check('pilot ON can prefer recipe',on[0].goal.kind==='upgrade',on[0]);
const craft={...offer,specialization:'artisan',mastery:{revision:1,nextChangeAt:0,ranks:{hands:3}}},whisk=g.UPGRADES.find(u=>u.id==='whisk'),impact=ins.recipeImpact(craft,whisk);check('separate auto/manual impact',near(impact.click,impact.autoClick*1.4)&&near(ins.impactIncome(craft,impact,true),impact.production+10*impact.autoClick));check('manual cadence not invented',ins.impactIncome(craft,impact,false)===impact.production);
const hot={...craft,rushUntil:999999,eventBuffs:{manualMultiplier:3,manualUntil:999999,steamUntil:999999}};check('temporary buffs excluded from impacts and steady income',JSON.stringify(ins.recipeImpact(hot,whisk))===JSON.stringify(impact)&&ins.steadyIncome(hot,true)===ins.steadyIncome(craft,true));
const all=goals.recommendGoals(craft,true,1000).filter(x=>x.goal.kind==='upgrade');check('recipe advice shows cost and gains',all.length>0&&all.every(x=>x.detail.includes('cookies')&&x.detail.includes('/ s')));
const expiredBuy=event('merchant').p;expiredBuy.balance=1e9;const displayed=g.buildingPrice(expiredBuy,0,1,45999);check('expired offer cannot silently overcharge',throws(()=>g.applyCookieAction(expiredBuy,{kind:'buy',building:0,quantity:1,maxCost:displayed},46000))&&expiredBuy.buildings[0]===0);
const slow=fresh({buildings:[10,0,...Array(14).fill(0)],eventBuffs:{manualMultiplier:2,discountUntil:46000}});check('ETA uses full price after discount expiry',ins.advisedBuildingPrice(slow,1,1,false,1000)===100);slow.balance=60;check('reachable offer keeps discounted price',ins.advisedBuildingPrice(slow,1,1,false,1000)===85);
// Real API: one event / one receipt, mutually exclusive choices, malicious payloads.
const name='TestEvents19',key=name.toLowerCase(),quote=s=>"'"+String(s).replaceAll("'","''")+"'";let owned=false;
function db(sql){const r=spawnSync(process.execPath,['--import','./scripts/sites-env.mjs','./node_modules/wrangler/bin/wrangler.js','d1','execute','DB','--config','dist/server/wrangler.json','--local','--persist-to','.wrangler/state','--command',sql,'--json'],{encoding:'utf8',maxBuffer:2e6});if(r.status!==0)throw Error(r.stderr||r.stdout);return JSON.parse(r.stdout);}
async function req(action,id=crypto.randomUUID()){const r=await fetch(base+'/api/cookie',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({author:name,id,action})});return {status:r.status,...await r.json()};}
function seed(id){const at=Date.now(),p=fresh({updated:at,nextEventAt:at,nextEventId:id,balance:1e9});db('UPDATE cookie_players SET data='+quote(JSON.stringify(p))+',updated='+at+',version=version+1 WHERE author_key='+quote(key));return at;}
try{if(db('SELECT author_key FROM cookie_players WHERE author_key='+quote(key))[0].results.length)throw Error('Pre-existing fixture');const created=await req({kind:'sync'});if(created.status!==200)throw Error('Fixture create failed');owned=true;
 let at=seed('crossroads');const invalid=await req({kind:'event',eventAt:at,choice:'both'});check('API rejects forged choice',invalid.status===400);check('API requires crossroad choice',(await req({kind:'event',eventAt:at})).status===400);
 const id=crypto.randomUUID(),same=await Promise.all([req({kind:'event',eventAt:at,choice:'burst'},id),req({kind:'event',eventAt:at,choice:'burst'},id)]);check('duplicate event UUID credited once',same.every(x=>x.status===200&&x.player.eventBuffs.manualMultiplier===3)&&same[0].player.eventBuffs.manualUntil===same[1].player.eventBuffs.manualUntil);check('caught alternate choice denied',(await req({kind:'event',eventAt:at,choice:'harvest'})).status===400);
 at=seed('crossroads');const race=await Promise.all([req({kind:'event',eventAt:at,choice:'burst'}),req({kind:'event',eventAt:at,choice:'harvest'})]);check('concurrent choices only one accepted',race.filter(x=>x.status===200).length===1&&race.filter(x=>x.status===400).length===1);
 at=seed('merchant');const caught=await req({kind:'event',eventAt:at});check('merchant API persists offer',caught.status===200&&caught.player.eventBuffs.discountUntil>at);const buyId=crypto.randomUUID(),action={kind:'buy',building:1,quantity:10},buys=await Promise.all([req(action,buyId),req(action,buyId)]);check('duplicate discounted purchase one lot',buys.every(x=>x.status===200&&x.player.buildings[1]===10&&!x.player.eventBuffs.discountUntil));
 const reread=await(await fetch(base+'/api/cookie?author='+name)).json();check('reload keeps consumed offer and next identity',!reread.player.eventBuffs.discountUntil&&!!reread.player.nextEventId);
}finally{if(owned){db('DELETE FROM cookie_actions WHERE author_key='+quote(key));db('DELETE FROM cookie_players WHERE author_key='+quote(key));}}
const failed=checks.filter(c=>!c.pass),report={total:checks.length,passed:checks.length-failed.length,failed};fs.writeFileSync('.sites-runtime/events-v19-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failed.length)process.exitCode=1;
