// Synthetic model compatibility and late-game progression; no database writes.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),ts=require('typescript');
const baseline='de0e0a5c30466b40a4d5b037b8d90b0217e2acf5';
function compile(source,game){const exports={},math=Object.create(Math);math.random=()=>.25;vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Math:math,require(id){if(id==='@/lib/cookie-game')return game;throw Error(id);}});return exports;}
const previous=execFileSync('git',['show',baseline+':lib/cookie-game.ts'],{encoding:'utf8'}),source=fs.readFileSync('lib/cookie-game.ts','utf8'),old=compile(previous),g=compile(source),insights=compile(fs.readFileSync('lib/cookie-insights.ts','utf8'),g);
const copy=x=>JSON.parse(JSON.stringify(x)),equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b)),near=(a,b)=>assert(Math.abs(a-b)<=Math.max(1e-7,Math.abs(b)*1e-11));
const checks=[],failures=[];function check(name,fn){try{fn();checks.push(name);}catch(e){failures.push({name,error:e.message});}}
for(const key of ['BUILDINGS','UPGRADES','COOKIE_MISSIONS','COOKIE_ACHIEVEMENTS','COOKIE_AVATARS','CHAPTER_THRESHOLDS','COSMIC_CHAPTERS','AUTO_TIERS','TRIALS','WONDER_PROJECTS','WONDER_STAGES','REBUILD_MISSIONS','MASTERY_TALENTS','SPECIALIZATIONS'])check(key+' preserves the complete v25 prefix',()=>equal(g[key].slice(0,old[key].length),old[key]));
check('persistence type unchanged',()=>equal(source.match(/^export type CookiePlayer=.*$/m)[0],previous.match(/^export type CookiePlayer=.*$/m)[0]));
const stripNew=p=>{const q=copy(p);q.buildings=q.buildings.slice(0,37);q.achievements=q.achievements.filter(id=>!id.startsWith('jubilee_'));return q;};
for(const lifetime of [0,1e20,1e30,1e60,1e72,1e90,1e119])for(const prestige of [0,39445,1e30])for(const rich of [false,true]){
 const p=old.freshCookiePlayer(1000);Object.assign(p,{lifetime,balance:lifetime,runEarned:lifetime,prestige,clicks:250000,autoCredit:20,resets:8,banked:prestige**2*1e9,goldenReadyAt:1000,nextEventAt:1e10,nextEventId:'comet',upgrades:rich?old.UPGRADES.map(u=>u.id):['thumb','hooves','rhythm'],missions:['m1'],achievements:['bake0'],mastery:{revision:4,nextChangeAt:1e8,ranks:{variety:2,hands:2,links:2}},rhythm:{cycle:3,boostUntil:16000,best:95,wins:2},trialBoostUntil:8000,contracts:{cycle:7,nextAcceptAt:1e8,completed:20,byKind:{produce:9,spend:8,catch:3},bySchool:{artisan:10,watcher:10}},trials:{cycle:5,bests:{hands:{seconds:30,medal:3}}},wonder:{completed:[0,1],active:{stage:2,target:1e35,progress:150,referenceRate:1e30}},followedGoal:{kind:'building',id:'oven',target:100,run:8},followRevision:3});p.buildings=old.BUILDINGS.map((_,i)=>rich?20+i:i<5?i+1:0);old.award(p);old.ensureRebuild(p);
 const tag=`life=${lifetime},stars=${prestige},rich=${rich}`;
 check('old income unchanged '+tag,()=>near(g.baseProduction(p),old.baseProduction(p)));
 for(const elapsed of [0,500,2500,8*3600000])check('settlement '+tag+','+elapsed,()=>{const a=copy(p),b=copy(p);near(g.settle(b,1000+elapsed),old.settle(a,1000+elapsed));equal(stripNew(b),a);assert.equal(b.buildings.length,47);assert(b.buildings.slice(37).every(n=>n===0));});
 for(const action of [{kind:'sync'},{kind:'click',count:12},{kind:'auto',count:20},{kind:'buy',building:0,quantity:1},{kind:'golden'},{kind:'prestige'}])check('action '+tag+','+action.kind,()=>{const a=copy(p),b=copy(p);let ea,eb,ra,rb;try{ra=old.applyCookieAction(a,copy(action),2500);}catch(e){ea=e.message;}try{rb=g.applyCookieAction(b,copy(action),2500);}catch(e){eb=e.message;}equal(ea,eb);equal(ra,rb);equal(stripNew(b),a);});
}
check('48 avatars append consecutive indices and unique late thresholds',()=>{assert.equal(g.COOKIE_AVATARS.length,78);g.COOKIE_AVATARS.slice(30).forEach((a,i)=>{assert.equal(a.index,90+i);assert.equal(g.latestCookieAvatar(a.threshold).index,a.index);assert.notEqual(g.latestCookieAvatar(a.threshold*(1-1e-10)).index,a.index);});});
for(let i=37;i<47;i++)check('new building + all recipes + advice '+i,()=>{
 const p=g.freshCookiePlayer(1000),threshold=g.buildingUnlock(i);p.balance=g.COOKIE_CAP;p.lifetime=threshold*(1-1e-10);assert(!g.buildingUnlocked(p,i));assert.throws(()=>g.applyCookieAction(p,{kind:'buy',building:i,quantity:1},1000));p.lifetime=threshold;g.applyCookieAction(p,{kind:'buy',building:i,quantity:50},1000);assert.equal(p.buildings[i],50);p.buildings[i-1]=100;p.buildings[i-2]=100;
 const before=g.baseProduction(p),recipes=g.UPGRADES.filter(u=>u.building===i||u.synergy?.target===i);assert.equal(recipes.length,5);const plan=g.recipePurchasePlan(p);assert(recipes.every(u=>plan.recipes.some(r=>r.id===u.id)));g.applyCookieAction(p,{kind:'buyRecipes',run:p.resets,maxCost:plan.cost},1000);assert(recipes.every(u=>p.upgrades.includes(u.id)));assert(g.baseProduction(p)>before*8);assert(Number.isFinite(insights.steadyIncome(p)));
 const beforeMission=p.missions.length;g.applyCookieAction(p,{kind:'mission',mission:'jubilee_m'+(i-37)},1000);assert.equal(p.missions.length,beforeMission+1);assert.throws(()=>g.applyCookieAction(p,{kind:'mission',mission:'jubilee_m'+(i-37)},1000));assert(p.achievements.includes('jubilee_bake'+(i-37)));
});
check('last horizon remains finite through prestige and normalization',()=>{const p=g.freshCookiePlayer(1000);Object.assign(p,{balance:g.COOKIE_CAP/10,lifetime:g.COOKIE_CAP,runEarned:g.COOKIE_CAP,buildings:g.BUILDINGS.map(()=>100),upgrades:g.UPGRADES.map(u=>u.id)});g.award(p);assert.equal(g.masteryPoints(p),Math.floor(p.achievements.length/5));g.applyCookieAction(p,{kind:'prestige'},1000);assert.equal(p.lifetime,g.COOKIE_CAP);assert(p.achievements.includes('jubilee_bake9'));assert(p.buildings.every(n=>n===0));assert(g.buildingUnlocked(p,46));assert(!JSON.stringify(p).includes('null'));});
check("earnings cross old cap and stop finitely at the new cap",()=>{const p=g.freshCookiePlayer(1000);Object.assign(p,{balance:old.COOKIE_CAP,lifetime:old.COOKIE_CAP,runEarned:old.COOKIE_CAP});g.earn(p,old.COOKIE_CAP);assert.equal(p.balance,2*old.COOKIE_CAP);assert.equal(p.lifetime,2*old.COOKIE_CAP);g.earn(p,g.COOKIE_CAP*10);assert.equal(p.balance,g.COOKIE_CAP);assert.equal(p.lifetime,g.COOKIE_CAP);assert.equal(p.runEarned,g.COOKIE_CAP);});
const report={baseline,total:checks.length+failures.length,passed:checks.length,failures};fs.mkdirSync('.sites-runtime',{recursive:true});fs.writeFileSync('.sites-runtime/jubilee-compat-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures.length)process.exitCode=1;
